import json
def D(cmd,kind,color,stt,blurb,ex):
    k=cmd.replace('-','_'); T='CMD_'+k.upper()
    N='Cmd'+''.join(p.capitalize() for p in k.split('_'))
    dk='cmd'+''.join(p.capitalize() for p in k.split('_'))
    return {"cmd":cmd,"type":T,"name":N,"dataKey":dk,"kind":kind,"color":color,"stageTitle":stt,"blurb":blurb,"example":ex}
def S(*x): return list(x)
def st(label,atWord,text="",detail="",sub=""):
    d={"label":label,"atWord":atWord}
    if text: d["text"]=text
    if sub: d["sub"]=sub
    if detail: d["detail"]=detail
    return d
def it(label,atWord,sub="",text="",color=None,value=None):
    d={"label":label,"atWord":atWord}
    if sub: d["sub"]=sub
    if text: d["text"]=text
    if color: d["color"]=color
    if value is not None: d["value"]=value
    return d

defs=[
# ── ACT 4 · processes ────────────────────────────────────────────────────
D("ps","rows","purple","a frozen snapshot","the process list as a single moment in time, with the PID every other tool needs.",
 {"headline":"ps is a [snapshot], not a feed","color":"purple","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("ps aux",2,"dev 4821 63.2 node","BSD style"),st("ps -ef",9,"dev 4821 1 node","UNIX style, same data")),
  "stage":S(it("PID 4821",4,"node","63% cpu","red"),it("PID 1140",6,"nginx","8% cpu"),it("PID 1",11,"systemd","0% cpu")),
  "verdict":"The PID is what you need","verdictSub":"every other tool asks for that number","verdictAtWord":14}),
D("pstree","tree","purple","who started whom","the same processes drawn as a lineage from PID 1 downward.",
 {"headline":"pstree shows [who started whom]","color":"purple","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("pstree -p",2,"systemd(1)-+-nginx(1140)","the whole family")),
  "stage":S(it("systemd (1)",4,"the ancestor of everything",value=0),
            it("nginx (1140)",6,"started by systemd",value=1),
            it("worker (1141)",8,"started by nginx",value=2,color="green"),
            it("orphan",11,"reparented to PID 1",value=1,color="orange")),
  "verdict":"Kill a parent, PID 1 adopts","verdictSub":"children are never left without one","verdictAtWord":14}),
D("top","rows","purple","the list, re-sorting","rows physically reordering as load moves, which is what separates it from ps.",
 {"headline":"top re-sorts [as you watch]","color":"purple","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("top",2,"","press q to leave, M to sort by memory")),
  "stage":S(it("node",4,"climbing","94%","red"),it("postgres",6,"steady","31%"),it("nginx",8,"idle","2%")),
  "verdict":"The first thing you open","verdictSub":"when a box feels slow and you do not know why","verdictAtWord":11}),
D("htop","rows","purple","the friendlier view","the same numbers with colour, per-core bars and a mouse you can actually click.",
 {"headline":"htop is top with [colour and a mouse]","color":"purple","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("htop",2,"","F9 kills, F6 sorts")),
  "stage":S(it("per-core bars",4,"one per CPU","visual","green"),it("mouse support",6,"click to select","yes","green"),
            it("F9 to kill",8,"no PID typing","yes","green")),
  "verdict":"Same data, far less squinting","verdictSub":"install it on every box you own","verdictAtWord":11}),
D("btop","meters","purple","graphs over time","rolling per-core and memory graphs rather than a single instant.",
 {"headline":"btop draws it [over time]","color":"purple","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("btop",2,"","the modern rewrite")),
  "stage":S(it("CPU",4,"last 60 seconds","","green",72),it("memory",6,"climbing steadily","","orange",64),it("network",8,"quiet","",None,12)),
  "verdict":"A spike you can see coming","verdictSub":"an instant reading hides the trend","verdictAtWord":11}),
D("atop","rows","purple","yesterday, replayed","the viewer that logged to disk, letting you scroll back to the incident.",
 {"headline":"atop already [recorded it]","color":"purple","atWord":1,"promptLabel":"dev@box","cwd":"~","highlight":"-r",
  "steps":S(st("atop -r /var/log/atop/atop_20260817",2,"","replay yesterday")),
  "stage":S(it("14:00",4,"normal","ok","green"),it("14:40",6,"the spike","found","red"),it("15:10",8,"recovered","ok","green")),
  "verdict":"Answers after the fact","verdictSub":"top can only ever show you now","verdictAtWord":11}),
D("glances","rows","purple","everything on one pane","every subsystem at once, colouring the ones in trouble first.",
 {"headline":"glances shows [everything] at once","color":"purple","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("glances",2,"","one screen, all subsystems")),
  "stage":S(it("CPU",4,"fine","28%","green"),it("memory",6,"fine","41%","green"),
            it("disk I/O",8,"saturated","98%","red"),it("network",10,"fine","12%","green")),
  "verdict":"The red one finds you","verdictSub":"no need to know which tool to open","verdictAtWord":13}),
D("nmon","rows","purple","panels you switch on","subsystem panels toggled by keypress until the view is the one you want.",
 {"headline":"nmon builds the view [you want]","color":"purple","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("nmon",2,"","then press c, m, d, n")),
  "stage":S(it("press c",4,"CPU panel","on","green"),it("press m",6,"memory panel","on","green"),
            it("press d",8,"disk panel","on","green"),it("press n",10,"network panel","on","green")),
  "verdict":"Built for capture, not just watching","verdictSub":"-f writes a file you can graph later","verdictAtWord":13}),
D("kill","hops","red","the signal arriving","a signal travelling from your terminal through the kernel to the process.",
 {"headline":"kill sends a [signal], not a bullet","color":"red","atWord":1,"promptLabel":"dev@box","cwd":"~","token":"SIGTERM (15)",
  "steps":S(st("kill 4821",2,"","the default is SIGTERM"),st("kill -9 4821",11,"","SIGKILL, when nothing else works")),
  "stage":S(it("your terminal",4,"","sends"),it("the kernel",6,"","delivers"),
            it("node (4821)",8,"catches it, saves, exits","clean","green"),it("with -9",13,"no chance to clean up","abrupt","red")),
  "verdict":"SIGTERM first, always","verdictSub":"-9 loses whatever was unsaved","verdictAtWord":16}),
D("killall","rows","red","everything with that name","one name resolving to every matching process at once.",
 {"headline":"killall hits [all of them]","color":"red","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("killall node",2,"","by name, not by PID")),
  "stage":S(it("node 4821",4,"yours","killed","red"),it("node 4822",6,"yours","killed","red"),
            it("node 5310",8,"a colleague's","killed too","red")),
  "verdict":"Fine on a laptop","verdictSub":"genuinely dangerous on a shared server","verdictAtWord":11}),
D("nohup","rows","green","surviving the logout","the hangup signal reaching every child except the one told to ignore it.",
 {"headline":"nohup ignores the [hangup]","color":"green","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("./backup.sh &",2,"","dies when you log out"),st("nohup ./backup.sh &",9,"nohup: ignoring input","survives")),
  "stage":S(it("you close the terminal",4,"SIGHUP is sent","signal"),
            it("plain background job",6,"receives it","dies","red"),
            it("under nohup",11,"ignores it","lives","green")),
  "verdict":"Output goes to nohup.out","verdictSub":"unless you redirect it yourself","verdictAtWord":14}),
D("sleep","flow","blue","a script, waiting","the clock advancing inside a script while nothing else happens.",
 {"headline":"sleep pauses [the script]","color":"blue","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("sleep 5",2,"","seconds by default"),st("sleep 2m",8,"","m, h and d also work")),
  "stage":S(it("start",4,"the script runs"),it("sleep 5",6,"nothing happens","5s","orange"),it("resume",10,"the next line","","green")),
  "verdict":"Blocks, never busy-waits","verdictSub":"it costs no CPU at all","verdictAtWord":13}),
D("wait","flow","blue","holding for the jobs","background jobs finishing at their own pace while the script waits for the last one.",
 {"headline":"wait holds until [they finish]","color":"blue","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("./a.sh & ./b.sh &",2,"","two jobs in the background"),st("wait",9,"","hold here until both are done")),
  "stage":S(it("job a",4,"running","3s"),it("job b",6,"running","7s"),
            it("without wait",11,"script exits early","bug","red"),it("with wait",13,"script waits for b","correct","green")),
  "verdict":"Without it, the script lies","verdictSub":"it reports done while work is running","verdictAtWord":16}),
D("lsof","rows","orange","who is holding it","the file, every process holding it open, and the unmount that keeps failing.",
 {"headline":"lsof names the [holder]","color":"orange","atWord":1,"promptLabel":"root@box","cwd":"/","highlight":"-i",
  "steps":S(st("umount /mnt/data",2,"target is busy","refused"),st("lsof /mnt/data",8,"tail 4821 api.log","there is your culprit"),
            st("lsof -i :443",14,"nginx 1140 LISTEN","works for ports too")),
  "stage":S(it("tail (4821)",5,"holding api.log","blocks unmount","red"),
            it("vim (5102)",10,"holding conf","blocks unmount","red"),
            it("nginx (1140)",16,"holding port 443","listening","green")),
  "verdict":"A socket counts as a file","verdictSub":"which is why -i finds port conflicts","verdictAtWord":19}),
D("strace","flow","yellow","the calls it really makes","each system call crossing into the kernel and the answer that comes back.",
 {"headline":"strace shows what it [really tried]","color":"yellow","atWord":1,"promptLabel":"dev@box","cwd":"~","highlight":"-e",
  "steps":S(st("strace ./app",2,"","thousands of lines"),st("strace -e openat ./app",10,"openat(...) = -1 ENOENT","filtered to what matters")),
  "stage":S(it("your program",4,"asks the kernel","openat()"),
            it("the kernel",6,"looks for the path","checking"),
            it("the answer",12,"no such file","ENOENT","red")),
  "verdict":"It failed on a missing file","verdictSub":"not on the thing the error claimed","verdictAtWord":15}),

# ── ACT 5 · watching ─────────────────────────────────────────────────────
D("uptime","meters","yellow","three numbers, one trend","load averaged over one, five and fifteen minutes, read against the core count.",
 {"headline":"Load is [three numbers], not one","color":"yellow","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("uptime",2,"load average: 4.10, 3.20, 1.90","and the box has 8 cores")),
  "stage":S(it("1 minute",4,"right now","4.10","orange",51),it("5 minutes",6,"settling","3.20","green",40),
            it("15 minutes",8,"was calm","1.90","green",24)),
  "verdict":"4 on 8 cores is half busy","verdictSub":"the same 4 on 2 cores is on fire","verdictAtWord":12}),
D("free","meters","yellow","why free looks alarming","cache drawn as reclaimable, so the frightening number turns out to be fine.",
 {"headline":"Low free memory is [normal]","color":"yellow","atWord":1,"promptLabel":"dev@box","cwd":"~","highlight":"-h",
  "steps":S(st("free -h",2,"free 312Mi  available 21Gi","two very different numbers")),
  "stage":S(it("used",4,"real programs","","orange",38),it("cache",6,"reclaimable instantly","","blue",54),
            it("free",8,"genuinely unused","","red",8),it("available",11,"what you can actually get","","green",62)),
  "verdict":"Read available, ignore free","verdictSub":"Linux spends spare memory on purpose","verdictAtWord":14}),
D("vmstat","rows","yellow","sampled on an interval","columns re-reading every second, with the first row being a lie about now.",
 {"headline":"vmstat's first row is [since boot]","color":"yellow","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("vmstat 1",2,"","one sample per second")),
  "stage":S(it("row 1",4,"average since boot","ignore","red"),it("row 2",6,"the last second","real","green"),
            it("si / so",8,"swap in and out","watch this","orange")),
  "verdict":"Non-zero swap is the red flag","verdictSub":"it means memory pressure, not just usage","verdictAtWord":11}),
D("iostat","meters","yellow","per device, per second","throughput and queue time for each disk, with await as the number that matters.",
 {"headline":"await is the number [that matters]","color":"yellow","atWord":1,"promptLabel":"dev@box","cwd":"~","highlight":"-x",
  "steps":S(st("iostat -x 1",2,"","extended stats, once a second")),
  "stage":S(it("sda read",4,"MB/s","","green",22),it("sda write",6,"MB/s","","orange",78),
            it("await",9,"ms per request","41ms","red",82)),
  "verdict":"High await means queuing","verdictSub":"the disk is the bottleneck, not the CPU","verdictAtWord":12}),
D("iotop","rows","yellow","which process is writing","the write storm traced back to the single process responsible for it.",
 {"headline":"iotop names the [writer]","color":"yellow","atWord":1,"promptLabel":"root@box","cwd":"~",
  "steps":S(st("iotop -o",2,"postgres 88 M/s","-o shows only active ones")),
  "stage":S(it("postgres",4,"88 M/s","the culprit","red"),it("rsync",6,"12 M/s","expected"),it("everything else",8,"~0","idle")),
  "verdict":"iostat says the disk is busy","verdictSub":"iotop says who made it busy","verdictAtWord":11}),
D("dstat","rows","yellow","several subsystems, one line","CPU, disk and network sampled together instead of in three separate tools.",
 {"headline":"dstat puts it [on one line]","color":"yellow","atWord":1,"promptLabel":"dev@box","cwd":"~",
  "steps":S(st("dstat -cdn",2,"","cpu, disk, network")),
  "stage":S(it("cpu",4,"user and system","31%"),it("disk",6,"read and write","74 M/s","orange"),
            it("net",8,"send and receive","12 M/s")),
  "verdict":"Correlation in one glance","verdictSub":"disk spikes and CPU waits line up visibly","verdictAtWord":11}),
D("sar","rows","yellow","yesterday, on disk","numbers recorded all day, recoverable long after the incident is over.",
 {"headline":"sar already [wrote it down]","color":"yellow","atWord":1,"promptLabel":"dev@box","cwd":"~","highlight":"-f",
  "steps":S(st("sar -u -f /var/log/sa/sa17",2,"14:40  us 91.2","yesterday afternoon")),
  "stage":S(it("14:00",4,"normal","12%","green"),it("14:40",6,"the spike","91%","red"),it("15:10",8,"recovered","14%","green")),
  "verdict":"Enable sysstat before you need it","verdictSub":"you cannot record the past afterwards","verdictAtWord":11}),
D("watch","flow","yellow","any command, on a loop","a command rerun on a timer with the differences between passes highlighted.",
 {"headline":"watch turns anything [into a dashboard]","color":"yellow","atWord":1,"promptLabel":"dev@box","cwd":"~","highlight":"-d",
  "steps":S(st("watch -n 2 df -h",2,"","every two seconds"),st("watch -d free -h",9,"","-d highlights what changed")),
  "stage":S(it("run",4,"the command"),it("show",6,"its output"),it("diff",11,"what changed","highlighted","green"),
            it("wait",13,"2 seconds, repeat")),
  "verdict":"A slow leak becomes obvious","verdictSub":"one reading never shows a trend","verdictAtWord":16}),

# ── ACT 6 · disks ────────────────────────────────────────────────────────
D("df","meters","red","space, and the other limit","fullness per filesystem, plus the inode gauge that fills independently.",
 {"headline":"df -i is the [trap] nobody checks","color":"red","atWord":1,"promptLabel":"dev@box","cwd":"~","highlight":"-i",
  "steps":S(st("df -h",2,"/dev/sda1  62% used","plenty of room"),st("df -i",9,"/dev/sda1  100% inodes","and yet writes fail")),
  "stage":S(it("space used",4,"gigabytes","62%","green",62),it("inodes used",11,"one per file","100%","red",100)),
  "verdict":"Space free, writes failing","verdictSub":"millions of tiny files exhausted the inodes","verdictAtWord":15}),
D("du","meters","red","which directory ate it","sizes summed upward per directory until the offender is obvious.",
 {"headline":"du finds [which directory] ate it","color":"red","atWord":1,"promptLabel":"root@box","cwd":"/","highlight":"-d 1",
  "steps":S(st("du -sh /var/*",2,"48G  /var/log","summed per directory"),st("du -h -d 1 /var/log",10,"44G  /var/log/nginx","one level down")),
  "stage":S(it("/var/log",4,"the biggest","48G","red",88),it("/home",6,"","26G","blue",48),
            it("/usr",8,"","18G",None,33),it("/var/log/nginx",12,"the real culprit","44G","red",80)),
  "verdict":"Walk down, never guess","verdictSub":"df says full, du says why","verdictAtWord":15}),
D("ncdu","rows","red","browse it interactively","the same walk, but navigable, so you descend into the biggest folder repeatedly.",
 {"headline":"ncdu lets you [walk down] into it","color":"red","atWord":1,"promptLabel":"root@box","cwd":"/var",
  "steps":S(st("ncdu /var",2,"","arrow keys to descend, d to delete")),
  "stage":S(it("/var/log",4,"press enter","48G","red"),it("/var/log/nginx",6,"press enter again","44G","red"),
            it("access.log.1",8,"the actual file","41G","red")),
  "verdict":"Three keystrokes to the file","verdictSub":"du needs three separate commands","verdictAtWord":11}),
D("fdisk","rows","red","the partition table","a raw disk being divided into numbered regions, written only on command.",
 {"headline":"fdisk writes [nothing] until you say w","color":"red","atWord":1,"promptLabel":"root@box","cwd":"~","highlight":"-l",
  "steps":S(st("fdisk -l /dev/sda",2,"","just look"),st("fdisk /dev/sda",9,"Command (m for help):","interactive")),
  "stage":S(it("sda1",4,"boot","512M"),it("sda2",6,"root","64G","green"),it("sda3",8,"swap","8G"),
            it("press w",11,"now it is written","committed","red")),
  "verdict":"Quit with q and nothing changed","verdictSub":"the table lives in memory until w","verdictAtWord":15}),
D("parted","rows","red","for the large disks","the same job on disks too big for the old partition table format.",
 {"headline":"parted handles [large disks]","color":"red","atWord":1,"promptLabel":"root@box","cwd":"~",
  "steps":S(st("parted /dev/sdb mklabel gpt",2,"","GPT, not MBR")),
  "stage":S(it("MBR limit",4,"the old format","2 TB","red"),it("GPT",6,"the modern one","9.4 ZB","green"),
            it("your 4TB disk",8,"needs GPT","required","orange")),
  "verdict":"Over 2TB, MBR simply cannot","verdictSub":"the address field is not wide enough","verdictAtWord":11}),
D("blkid","rows","blue","names move, UUIDs do not","each device with its UUID and type, and why fstab should use the UUID.",
 {"headline":"Use the [UUID] in fstab","color":"blue","atWord":1,"promptLabel":"root@box","cwd":"~",
  "steps":S(st("blkid",2,"/dev/sdb1: UUID=e5f6-a7b8 TYPE=xfs","identity, not position")),
  "stage":S(it("/dev/sdb1",4,"today","the name"),it("/dev/sdc1",6,"after a reboot","moved","red"),
            it("UUID e5f6-a7b8",8,"always the same disk","stable","green")),
  "verdict":"Device names are not promises","verdictSub":"plug in a USB stick and they shuffle","verdictAtWord":11}),
D("mkfs","rows","red","the filesystem being written","empty structure laid across a partition, erasing whatever lived there.",
 {"headline":"mkfs [erases] whatever was there","color":"red","atWord":1,"promptLabel":"root@box","cwd":"~",
  "steps":S(st("mkfs.ext4 /dev/sdb1",2,"Creating journal...","no confirmation prompt")),
  "stage":S(it("before",4,"your old data","present"),it("mkfs runs",6,"structure written","","orange"),
            it("after",8,"an empty filesystem","gone","red")),
  "verdict":"There is no undo here either","verdictSub":"check the device name twice","verdictAtWord":11}),
D("fsck","rows","orange","checks, then repairs","the structure swept for damage, with one check catching a fault.",
 {"headline":"fsck needs it [unmounted]","color":"orange","atWord":1,"promptLabel":"root@box","cwd":"~","highlight":"-y",
  "steps":S(st("fsck /dev/sdb1",2,"is mounted. Really continue?","say no"),
            st("umount /dev/sdb1 && fsck -y /dev/sdb1",10,"","now it is safe")),
  "stage":S(it("inodes",5,"scanned","ok","green"),it("block map",7,"scanned","ok","green"),
            it("directory tree",12,"orphan found","repaired","orange")),
  "verdict":"On a mounted disk it corrupts","verdictSub":"the kernel is writing while fsck reads","verdictAtWord":15}),
D("mount","tree","blue","two trees becoming one","another filesystem grafted into the tree, hiding whatever sat at that point.",
 {"headline":"mount [grafts] a second tree in","color":"blue","atWord":1,"promptLabel":"root@box","cwd":"/",
  "steps":S(st("mount /dev/sdb1 /mnt/data",2,"","attached at the mount point")),
  "stage":S(it("/",4,"the root filesystem",value=0),it("mnt",6,"",value=1),
            it("data",8,"now /dev/sdb1 lives here",value=2,color="green"),
            it("old contents",10,"hidden, not deleted",value=2,color="orange")),
  "verdict":"Files under a mount point hide","verdictSub":"unmount and they reappear untouched","verdictAtWord":13}),
D("umount","rows","blue","why it refuses","the unmount blocked by an open file, then succeeding once the holder lets go.",
 {"headline":"umount refuses while [something holds it]","color":"blue","atWord":1,"promptLabel":"root@box","cwd":"/",
  "steps":S(st("umount /mnt/data",2,"target is busy","blocked"),st("lsof /mnt/data",8,"tail 4821","there it is"),
            st("kill 4821 && umount /mnt/data",13,"","now it works")),
  "stage":S(it("tail (4821)",5,"holding a file open","blocks","red"),
            it("kill it",15,"the handle closes","released","green"),
            it("umount",17,"","succeeds","green")),
  "verdict":"Never reach for -f first","verdictSub":"a forced unmount can lose writes","verdictAtWord":20}),
D("dd","rows","red","what happens to the target","the block copy running with no confirmation, and one wrong letter erasing a disk.",
 {"headline":"dd is the [four characters]","color":"red","atWord":1,"promptLabel":"root@box","cwd":"~","highlight":"of=",
  "steps":S(st("dd if=/dev/sda of=backup.img",2,"","reads the disk into a file"),
            st("dd if=backup.img of=/dev/sdb",10,"","writes to the spare disk"),
            st("dd if=backup.img of=/dev/sda",17,"","one letter wrong")),
  "stage":S(it("if= is the source",5,"read from here","safe","green"),
            it("of= is the target",12,"written over","careful","orange"),
            it("/dev/sda",19,"your running system","destroyed","red")),
  "verdict":"No prompt. No progress. No undo.","verdictSub":"status=progress at least shows you something","verdictAtWord":22}),
]
json.dump(defs,open('briefs/linux/defs_a456.json','w'),indent=1)
print(len(defs),"definitions")
