import json
def D(cmd,kind,color,stt,blurb,ex,name=None):
    k=(name or cmd).replace('-','_'); T='CMD_'+k.upper()
    N='Cmd'+''.join(p.capitalize() for p in k.split('_'))
    dk='cmd'+''.join(p.capitalize() for p in k.split('_'))
    return {"cmd":cmd,"type":T,"name":N,"dataKey":dk,"kind":kind,"color":color,"stageTitle":stt,"blurb":blurb,"example":ex}
def S(*x): return list(x)
def st(label,atWord,text="",detail="",sub=""):
    d={"label":label,"atWord":atWord}
    if text: d["text"]=text
    if sub: d["sub"]=sub
    if detail: d["detail"]=detail
    return d
def it(label,atWord,sub="",text="",color=None,value=None):
    d={"label":label,"atWord":atWord}
    if sub: d["sub"]=sub
    if text: d["text"]=text
    if color: d["color"]=color
    if value is not None: d["value"]=value
    return d

defs=[
# ── ACT 7 · the network here ─────────────────────────────────────────────
D("ip","rows","blue","addresses, links, routes","the three questions one tool answers about this machine's networking.",
 {"headline":"ip replaced [ifconfig]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("ip addr",2,"inet 10.0.0.5/24","which addresses"),st("ip route",9,"default via 10.0.0.1","and where traffic leaves")),
  "stage":S(it("ip addr",4,"your addresses","10.0.0.5","green"),it("ip link",6,"the interfaces","eth0 up"),
            it("ip route",11,"the way out","via 10.0.0.1","blue")),
  "verdict":"One tool, three questions","verdictSub":"ifconfig cannot show modern routing","verdictAtWord":14}),
D("ping","hops","blue","out, and back again","an echo request leaving, arriving, and returning with the time it took.",
 {"headline":"ping answers [two questions]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~","token":"ICMP echo request",
  "steps":S(st("ping -c 4 1.1.1.1",2,"64 bytes  time=12.4 ms","four packets, then stop")),
  "stage":S(it("your box",4,"","sent"),it("the gateway",6,"","forwarded"),
            it("1.1.1.1",8,"replied","12.4 ms","green"),it("packet 3",11,"never came back","lost","red")),
  "verdict":"Alive, and how far away","verdictSub":"loss matters more than the average","verdictAtWord":14}),
D("traceroute","hops","blue","every hop on the way","packets expiring one step further each time, forcing each hop to answer.",
 {"headline":"traceroute makes each hop [answer]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~","token":"TTL 1, then 2, then 3",
  "steps":S(st("traceroute 1.1.1.1",2,"7  * * *","the stars are the problem")),
  "stage":S(it("hop 1",4,"your router","1 ms","green"),it("hop 4",6,"your ISP","9 ms","green"),
            it("hop 7",8,"no reply","* * *","red"),it("hop 9",10,"destination","14 ms","green")),
  "verdict":"Stars are not always a fault","verdictSub":"many routers simply refuse to reply","verdictAtWord":13}),
D("mtr","rows","blue","the same probe, forever","traceroute rerun continuously so a flapping hop shows up as a column of loss.",
 {"headline":"mtr keeps [probing]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("mtr 1.1.1.1",2,"7. 10.2.0.1   38.2%","loss builds over time")),
  "stage":S(it("hop 4",4,"0.0% loss","stable","green"),it("hop 7",6,"38.2% loss","the culprit","red"),
            it("hop 9",8,"0.0% loss","fine","green")),
  "verdict":"One run can lie, a hundred cannot","verdictSub":"intermittent loss needs repetition to see","verdictAtWord":11}),
D("netstat","rows","blue","the older socket view","the legacy tool and the modern flags that replace each of its own.",
 {"headline":"netstat still works, [ss is faster]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("netstat -tulpn",2,"tcp 0 0 :::443 LISTEN","the classic incantation")),
  "stage":S(it("netstat -tulpn",4,"reads /proc line by line","slow","orange"),
            it("ss -tulpn",6,"asks the kernel directly","fast","green"),
            it("same output",8,"the flags even match","identical")),
  "verdict":"Muscle memory still works","verdictSub":"but ss finishes on a busy box","verdictAtWord":11}),
D("ss","rows","blue","what is listening","sockets grouped by state, so listening and established read apart at a glance.",
 {"headline":"ss shows [what is listening]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-l",
  "steps":S(st("ss -tulpn",2,"tcp LISTEN 0 511 *:443","every listening socket"),
            st("ss -t state established",10,"","and the live connections")),
  "stage":S(it("LISTEN :443",4,"nginx","waiting","green"),it("LISTEN :22",6,"sshd","waiting","green"),
            it("ESTABLISHED",12,"to 10.0.0.9","active","blue")),
  "verdict":"LISTEN means it is up","verdictSub":"if nobody connects, look at the firewall","verdictAtWord":15}),
D("nmcli","rows","blue","profiles, not hardware","a saved connection profile brought up and down independently of the device.",
 {"headline":"A profile is not the [device]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("nmcli device status",2,"eth0  connected  wired-1","device and profile"),
            st("nmcli con up wired-1",10,"Connection activated","bring the profile up")),
  "stage":S(it("eth0",4,"the physical device","hardware"),it("wired-1",6,"a saved profile","config","green"),
            it("wired-backup",12,"another profile, same device","config","blue")),
  "verdict":"One device, many profiles","verdictSub":"switch networks without touching hardware","verdictAtWord":15}),
D("iftop","rows","blue","by connection","bandwidth broken down per connection pair, heaviest rising to the top.",
 {"headline":"iftop sorts by [connection]","color":"blue","atWord":1,"promptLabel":"root@box","cwd":"~",
  "steps":S(st("iftop -i eth0",2,"10.0.0.5 => 10.0.0.9  38Mb","live, per pair")),
  "stage":S(it("=> 10.0.0.9",4,"the backup target","38 Mb","red"),it("=> 1.1.1.1",6,"dns","0.1 Mb"),
            it("=> 10.0.0.2",8,"monitoring","0.4 Mb")),
  "verdict":"Tells you where, not who","verdictSub":"for the process, use nethogs","verdictAtWord":11}),
D("nethogs","rows","blue","by process","the same bandwidth attributed to the program actually responsible for it.",
 {"headline":"nethogs blames a [process]","color":"blue","atWord":1,"promptLabel":"root@box","cwd":"~",
  "steps":S(st("nethogs eth0",2,"4821 rsync  38.2 KB/s","per program, not per socket")),
  "stage":S(it("rsync (4821)",4,"the backup job","38 MB/s","red"),it("nginx (1140)",6,"serving","2 MB/s"),
            it("sshd (980)",8,"your session","0.1 MB/s")),
  "verdict":"The question you actually had","verdictSub":"which program is eating the line","verdictAtWord":11}),
D("nload","meters","blue","just the totals","incoming and outgoing throughput, and nothing else at all.",
 {"headline":"nload is [two numbers]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("nload eth0",2,"Incoming 41 Mbit/s","in and out, that is it")),
  "stage":S(it("incoming",4,"","41 Mbit/s","green",41),it("outgoing",6,"","88 Mbit/s","orange",88)),
  "verdict":"When you only need the shape","verdictSub":"is the pipe full, yes or no","verdictAtWord":9}),

# ── ACT 8 · other machines ───────────────────────────────────────────────
D("dig","hops","green","a name becoming an address","the query travelling to a resolver and the typed record coming back.",
 {"headline":"dig gives you the [whole answer]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~","token":"example.com  A?",
  "steps":S(st("dig example.com",2,"example.com. 300 IN A 93.184.216.34","the ANSWER section"),
            st("dig +short example.com",11,"93.184.216.34","just the address")),
  "stage":S(it("your resolver",4,"1.1.1.1","asked"),it("the answer",6,"A record","93.184.216.34","green"),
            it("TTL 300",8,"cache for 5 minutes","timing")),
  "verdict":"The tool that shows its working","verdictSub":"TTL, authority and all","verdictAtWord":14}),
D("host","rows","green","one line, done","the same lookup answered as briefly as possible.",
 {"headline":"host is the [one-line] answer","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("host example.com",2,"example.com has address 93.184.216.34","that is the whole output")),
  "stage":S(it("host",4,"one readable line","brief","green"),it("dig",6,"the full record","detailed"),
            it("dig +short",8,"just the value","brief","green")),
  "verdict":"For a quick sanity check","verdictSub":"when you do not need the ceremony","verdictAtWord":11}),
D("nslookup","rows","orange","the older one","the interactive lookup, and why its output misleads about who answered.",
 {"headline":"nslookup can [mislead] you","color":"orange","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("nslookup example.com",2,"Non-authoritative answer:","that line confuses everyone")),
  "stage":S(it("Server: 1.1.1.1",4,"who you asked","fine"),
            it("Non-authoritative",6,"just means cached","normal","orange"),
            it("people read it as",8,"something is wrong","untrue","red")),
  "verdict":"Non-authoritative is not an error","verdictSub":"it means the answer came from a cache","verdictAtWord":11}),
D("whois","rows","green","who owns the name","registrar, expiry and nameservers pulled from the registry record.",
 {"headline":"whois tells you when it [expires]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("whois example.com",2,"Registry Expiry Date: 2026-09-14","28 days away")),
  "stage":S(it("registrar",4,"who it was bought from","IANA"),
            it("expiry",6,"28 days away","2026-09-14","red"),
            it("nameservers",8,"who answers for it","a.iana-servers")),
  "verdict":"Certificates outlive domains","verdictSub":"an expired domain breaks everything at once","verdictAtWord":11}),
D("ssh","hops","green","which key goes where","the key pair, with the public half living on the server and the private half never leaving.",
 {"headline":"The [public] half goes on the server","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~","token":"ed25519 key pair",
  "steps":S(st("ssh-keygen -t ed25519",2,"","makes both halves"),
            st("ssh-copy-id deploy@prod",9,"","sends the public one"),
            st("ssh deploy@prod",15,"Welcome to prod","no password")),
  "stage":S(it("id_ed25519",4,"private — stays on your laptop","never sent","red"),
            it("id_ed25519.pub",11,"public — goes to the server","copied","green"),
            it("authorized_keys",17,"on prod","matched","green")),
  "verdict":"Send the private key and you are done for","verdictSub":"the .pub suffix is the one that travels","verdictAtWord":20}),
D("scp","flow","green","a file over that tunnel","a file riding the encrypted channel ssh already established.",
 {"headline":"scp rides the [ssh channel]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":":",
  "steps":S(st("scp dist.tar.gz prod:/srv/",2,"dist.tar.gz  100%  41MB","the colon separates host from path")),
  "stage":S(it("local file",4,"./dist.tar.gz"),it("encrypted channel",6,"same keys as ssh","secure","green"),
            it("prod:/srv/",8,"the remote path","arrived","green")),
  "verdict":"Forget the colon and it copies locally","verdictSub":"you get a file literally named prod","verdictAtWord":11}),
D("rsync","rows","green","only what changed","a comparison first, then just the differences crossing the wire.",
 {"headline":"rsync sends only the [difference]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"--dry-run",
  "steps":S(st("rsync -av --dry-run ./src/ prod:/srv/",2,"","always look first"),
            st("rsync -av ./src/ prod:/srv/",11,"sent 2.1M  total 4.2G","0.05% of the data")),
  "stage":S(it("14,208 files",4,"unchanged","skipped","green"),
            it("3 files",6,"modified","sent","orange"),
            it("1 file",8,"new","sent","orange"),
            it("total on the wire",13,"instead of 4.2 GB","2.1 MB","green")),
  "verdict":"Trailing slash changes everything","verdictSub":"src/ copies contents, src copies the folder","verdictAtWord":16}),
D("nc","rows","blue","does anything answer","a raw socket opened to a port with no protocol in the way at all.",
 {"headline":"nc asks one [blunt question]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-zv",
  "steps":S(st("nc -zv prod 5432",2,"succeeded!","open"),st("nc -zv prod 6379",9,"Connection refused","closed")),
  "stage":S(it("port 5432",4,"postgres","open","green"),it("port 6379",11,"nothing listening","refused","red"),
            it("no reply at all",13,"a firewall dropping it","timeout","orange")),
  "verdict":"Refused and timeout differ","verdictSub":"refused means reached; timeout means blocked","verdictAtWord":16}),
D("wget","flow","green","fetch, and keep fetching","a download that retries by itself and can walk a whole site of links.",
 {"headline":"wget is built to [finish]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-c",
  "steps":S(st("wget https://ex.com/big.iso",2,"","one file"),st("wget -c https://ex.com/big.iso",9,"","-c resumes where it stopped")),
  "stage":S(it("connection drops",4,"at 61%","interrupted","red"),
            it("with -c",11,"resumes from 61%","continues","green"),
            it("-r",13,"follows links","mirrors a site","blue")),
  "verdict":"Made for downloading things","verdictSub":"curl is made for talking to things","verdictAtWord":16}),
D("curl","flow","green","talking to an API","a request assembled flag by flag and the status that comes back.",
 {"headline":"curl is for [talking], not downloading","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-X",
  "steps":S(st("curl https://api.ex.com/health",2,"{\"ok\":true}","a plain GET"),
            st("curl -X POST -d '{}' api.ex.com/jobs",10,"201 Created","method, headers and body")),
  "stage":S(it("-X POST",5,"the method","set","green"),it("-H",7,"a header","set","green"),
            it("-d",12,"the body","set","green"),it("201 Created",14,"the response","","green")),
  "verdict":"-i shows the headers too","verdictSub":"the fastest way to see what a server says","verdictAtWord":17}),

# ── ACT 9 · archives, jobs, sessions ─────────────────────────────────────
D("tar","flow","purple","two jobs, not one","files gathered into a single stream, and then that stream compressed.",
 {"headline":"czvf is [four instructions]","color":"purple","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-czvf",
  "steps":S(st("tar -czvf logs.tar.gz /var/log",2,"","create, gzip, verbose, file")),
  "stage":S(it("c",4,"create an archive","gather","green"),it("z",6,"compress it with gzip","shrink","green"),
            it("v",8,"print each name","verbose"),it("f logs.tar.gz",10,"name the output","file","green")),
  "verdict":"x replaces c to extract","verdictSub":"the other three letters stay the same","verdictAtWord":13}),
D("gzip","meters","purple","fast, and in place","a file shrinking, and the surprise that the original is replaced.",
 {"headline":"gzip [replaces] the original","color":"purple","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log","highlight":"-k",
  "steps":S(st("gzip api.log",2,"","api.log is gone, api.log.gz remains"),st("gzip -k api.log",10,"","-k keeps a copy")),
  "stage":S(it("before",4,"api.log","41 MB",None,100),it("after",6,"api.log.gz","6 MB","green",15)),
  "verdict":"Fast, and everywhere","verdictSub":"the default choice unless size is critical","verdictAtWord":13}),
D("bzip2","meters","purple","smaller, and slower","the same file squeezed harder at the cost of time.",
 {"headline":"bzip2 trades [time] for size","color":"purple","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log",
  "steps":S(st("bzip2 api.log",2,"","noticeably slower")),
  "stage":S(it("gzip",4,"1.2 seconds","6.0 MB","green",40),it("bzip2",6,"8.4 seconds","4.4 MB","orange",29)),
  "verdict":"Worth it for archives, not logs","verdictSub":"you write once and read almost never","verdictAtWord":9}),
D("zip","rows","purple","the portable one","an archive carrying its own directory, openable on any machine.",
 {"headline":"zip is the [portable] one","color":"purple","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-r",
  "steps":S(st("zip -r report.zip report/",2,"adding: report/ (deflated 68%)","one step, not two")),
  "stage":S(it("tar.gz",4,"needs tar to open","Linux","orange"),
            it("zip",6,"opens by double-click","everywhere","green"),
            it("its own index",8,"extract one file fast","random access","green")),
  "verdict":"Send zip to people, tar.gz to servers","verdictSub":"tar cannot extract one file without scanning","verdictAtWord":11}),
D("cron","rows","purple","five fields, in order","the schedule columns decoded one at a time against a real clock.",
 {"headline":"cron is [five fields]","color":"purple","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("30 2 * * 1 /opt/backup.sh",2,"","every Monday at 02:30")),
  "stage":S(it("30",4,"minute","30","green"),it("2",6,"hour","02","green"),
            it("*",8,"day of month","any"),it("*",10,"month","any"),it("1",12,"day of week","Monday","green")),
  "verdict":"A star means every one of them","verdictSub":"five stars is every single minute","verdictAtWord":15}),
D("crontab","rows","purple","your table, installed","the per-user table opened, edited and installed as one operation.",
 {"headline":"crontab -e, never [edit the file]","color":"purple","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-e",
  "steps":S(st("crontab -e",2,"","opens your table in an editor"),st("crontab -l",9,"30 2 * * 1 /opt/backup.sh","list what is installed")),
  "stage":S(it("crontab -e",4,"validates before installing","safe","green"),
            it("editing the file",6,"no validation at all","risky","red"),
            it("crontab -l",11,"what is actually loaded","truth","green")),
  "verdict":"A bad line silently skips the job","verdictSub":"crontab -e catches it, the file does not","verdictAtWord":14}),
D("bashscript","flow","green","a file becoming a program","the interpreter line, the execute bit, and the path you invoke it by.",
 {"headline":"Three lines and a [permission bit]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"+x",
  "steps":S(st("./backup.sh",2,"Permission denied","not executable yet"),
            st("chmod +x backup.sh",8,"","now it can run"),
            st("./backup.sh",13,"backup complete","./ because . is not in PATH")),
  "stage":S(it("#!/usr/bin/env bash",4,"which interpreter","shebang","green"),
            it("chmod +x",10,"the execute bit","set","green"),
            it("./backup.sh",15,"the leading ./ matters","runs","green")),
  "verdict":"The current folder is not in PATH","verdictSub":"deliberately — it is a security choice","verdictAtWord":18}),
D("alias","rows","green","a short name that sticks","a long command bound to a short one, and the file that makes it survive.",
 {"headline":"An alias dies unless you [save it]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("alias ll='ls -lah'",2,"","works right now"),st("echo \"alias ll='ls -lah'\" >> ~/.bashrc",10,"","and after a reboot")),
  "stage":S(it("typed at the prompt",4,"this session only","temporary","orange"),
            it("in ~/.bashrc",12,"every new shell","permanent","green")),
  "verdict":"Scripts do not see your aliases","verdictSub":"they run a non-interactive shell","verdictAtWord":15}),
D("env","rows","blue","what the command inherits","the variables a process is handed, and one changed for a single run.",
 {"headline":"env changes it for [one command]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("env",2,"PATH=/usr/bin  HOME=/home/santhu","everything inherited"),
            st("env DEBUG=1 ./app",9,"","just for this run")),
  "stage":S(it("PATH",4,"where commands are found","inherited"),
            it("HOME",6,"your home directory","inherited"),
            it("DEBUG=1",11,"only inside this process","temporary","green")),
  "verdict":"Nothing else on the box sees it","verdictSub":"the next command has no DEBUG at all","verdictAtWord":14}),
D("history","rows","blue","what you already typed","the numbered command history and the two ways to run something again.",
 {"headline":"history plus [Ctrl-R]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("history | tail -3",2,"9410  rsync -av ./src/ prod:/srv/","numbered"),
            st("!9410",9,"","runs 9410 again"),st("!!",13,"","runs the last one")),
  "stage":S(it("!9410",5,"by number","reruns","green"),it("!!",11,"the previous command","reruns","green"),
            it("Ctrl-R",15,"search backwards","interactive","green")),
  "verdict":"sudo !! is the one you will use","verdictSub":"rerun the last command with privilege","verdictAtWord":18}),
D("screen","rows","orange","the session outlives you","a session that keeps running when the connection drops, waiting to be reattached.",
 {"headline":"screen survives your [dropped wifi]","color":"orange","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-r",
  "steps":S(st("screen -S backup",2,"","start a named session"),st("screen -r backup",11,"","reattach after reconnecting")),
  "stage":S(it("job starts",4,"inside the session","running","green"),
            it("connection drops",6,"session keeps going","alive","green"),
            it("screen -r",13,"you are back","reattached","green")),
  "verdict":"Ctrl-A then d to detach","verdictSub":"closing the window would have been fine too","verdictAtWord":16}),
D("tmux","rows","orange","panes inside the session","one terminal split into panes and windows, all inside a surviving session.",
 {"headline":"tmux adds [panes] to the same idea","color":"orange","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"attach",
  "steps":S(st("tmux new -s work",2,"","a named session"),st("tmux attach -t work",10,"","come back to it")),
  "stage":S(it("pane 1",4,"the editor","split","green"),it("pane 2",6,"the logs","split","green"),
            it("the session",12,"survives disconnect","alive","green")),
  "verdict":"Ctrl-B is the prefix for everything","verdictSub":"screen uses Ctrl-A instead","verdictAtWord":15}),
D("systemctl","flow","purple","start, and enable","two different transitions people constantly mistake for one.",
 {"headline":"start is now. [enable] is after reboot","color":"purple","atWord":1,"promptLabel":"root@box","cwd":"~","highlight":"enable",
  "steps":S(st("systemctl start nginx",2,"","running right now"),
            st("systemctl enable nginx",8,"Created symlink...","and after a reboot"),
            st("systemctl status nginx",15,"active (running)","check both")),
  "stage":S(it("stopped",4,"nothing running","before","red"),
            it("start",6,"running now","active","green"),
            it("enable",10,"comes back on boot","persistent","green"),
            it("reboot",17,"only enabled survives","proof","orange")),
  "verdict":"You almost always want both","verdictSub":"enable --now does the pair in one go","verdictAtWord":20}),
D("journalctl","rows","purple","the log, narrowed","four filters composing until only the lines you need are left.",
 {"headline":"journalctl is [filters], not scrolling","color":"purple","atWord":1,"promptLabel":"root@box","cwd":"~","highlight":"-u",
  "steps":S(st("journalctl -u nginx",2,"","just that service"),
            st("journalctl -u nginx -b -p err",9,"","this boot, errors only"),
            st("journalctl -u nginx -f",16,"","and follow it live")),
  "stage":S(it("-u nginx",5,"one service","filter","green"),it("-b",11,"since this boot","filter","green"),
            it("-p err",13,"errors and worse","filter","green"),it("-f",18,"follow live","tail","green")),
  "verdict":"Compose them, do not scroll","verdictSub":"a journal is a database, not a file","verdictAtWord":21}),
D("dmesg","rows","orange","the kernel's own buffer","a fixed-size ring where the oldest messages fall off the end.",
 {"headline":"dmesg is a [ring buffer]","color":"orange","atWord":1,"promptLabel":"root@box","cwd":"~","highlight":"-T",
  "steps":S(st("dmesg -T | tail",2,"[Aug 17 09:14] usb 1-2: new device","-T makes the timestamps readable")),
  "stage":S(it("newest",4,"just arrived","in","green"),it("older",6,"still here","kept"),
            it("oldest",8,"pushed off the end","lost","red")),
  "verdict":"Hardware trouble lands here first","verdictSub":"before any log file gets written","verdictAtWord":11}),

# ── ACT 10 · getting unstuck ─────────────────────────────────────────────
D("man","rows","blue","the numbered sections","the same name living in two sections, meaning two different things.",
 {"headline":"man passwd and man [5] passwd differ","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"5",
  "steps":S(st("man passwd",2,"PASSWD(1)","the command"),st("man 5 passwd",9,"PASSWD(5)","the file format")),
  "stage":S(it("section 1",4,"user commands","the program","green"),
            it("section 5",11,"file formats","/etc/passwd","green"),
            it("section 8",13,"admin commands","root's tools")),
  "verdict":"The number in brackets is the section","verdictSub":"man -k shows which sections exist","verdictAtWord":16}),
D("apropos","rows","blue","search by description","the manual searched by what a command does rather than what it is called.",
 {"headline":"apropos searches [descriptions]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("apropos \"disk usage\"",2,"du (1) - estimate file space usage","found by meaning")),
  "stage":S(it("you know",4,"the job","disk usage"),it("you do not know",6,"the name","?","orange"),
            it("apropos finds",8,"du, df, ncdu","answer","green")),
  "verdict":"man -k is the same command","verdictSub":"exactly the same tool, shorter to type","verdictAtWord":11}),
D("tldr","rows","green","examples, not prose","the practical examples the manual buries under exhaustive detail.",
 {"headline":"tldr gives you the [normal] usage","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("tldr tar",2,"tar -czvf target.tar.gz file","five examples, that is all")),
  "stage":S(it("man tar",4,"1,241 lines","complete","orange"),
            it("tldr tar",6,"8 lines","practical","green"),
            it("what you wanted",8,"the common case","found","green")),
  "verdict":"man for truth, tldr for speed","verdictSub":"you need both, at different moments","verdictAtWord":11}),
D("cheat","rows","green","the notes you wrote","your own sheets, kept for the things you personally keep forgetting.",
 {"headline":"cheat stores [your own] notes","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("cheat -e rsync",2,"","edit your own sheet"),st("cheat rsync",9,"rsync -av --dry-run src/ host:/dst/","recall it later")),
  "stage":S(it("tldr",4,"community examples","shared"),it("cheat",11,"your own notes","personal","green"),
            it("the flag you forget",13,"written down once","solved","green")),
  "verdict":"Write it down the second time","verdictSub":"the third time will come","verdictAtWord":16}),
D("lspci","rows","blue","what is on the bus","the hardware physically present, with the driver bound to each device.",
 {"headline":"lspci shows the [driver] too","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-k",
  "steps":S(st("lspci -k",2,"00:02.0 VGA  Kernel driver in use: i915","-k adds the driver line")),
  "stage":S(it("device present",4,"the card exists","yes","green"),
            it("driver in use",6,"i915","bound","green"),
            it("no driver line",8,"present but unusable","the bug","red")),
  "verdict":"Present is not the same as working","verdictSub":"no driver means nothing will use it","verdictAtWord":11}),
D("lsusb","tree","blue","the USB tree","devices nested by bus and port, exactly as they are physically plugged.",
 {"headline":"lsusb shows the [tree]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"-t",
  "steps":S(st("lsusb -t",2,"","-t draws the hierarchy")),
  "stage":S(it("Bus 001",4,"the root hub",value=0),it("Port 2: hub",6,"an external hub",value=1),
            it("Port 2.1: keyboard",8,"through the hub",value=2,color="green"),
            it("Port 2.2: drive",10,"sharing the bandwidth",value=2,color="orange")),
  "verdict":"A shared hub shares bandwidth","verdictSub":"which is why the drive slowed down","verdictAtWord":13}),
]
json.dump(defs,open('briefs/linux/defs_a78910.json','w'),indent=1)
print(len(defs),"definitions")
