import json
def D(cmd,kind,color,st,blurb,ex):
    k=cmd.replace('-','_'); T='CMD_'+k.upper()
    N='Cmd'+''.join(p.capitalize() for p in k.split('_'))
    dk='cmd'+''.join(p.capitalize() for p in k.split('_'))
    return {"cmd":cmd,"type":T,"name":N,"dataKey":dk,"kind":kind,"color":color,
            "stageTitle":st,"blurb":blurb,"example":ex}
def S(*st): return list(st)
def st(label,atWord,text="",detail="",sub=""): 
    d={"label":label,"atWord":atWord}
    if text: d["text"]=text
    if sub: d["sub"]=sub
    if detail: d["detail"]=detail
    return d
def it(label,atWord,sub="",text="",color=None,value=None):
    d={"label":label,"atWord":atWord}
    if sub: d["sub"]=sub
    if text: d["text"]=text
    if color: d["color"]=color
    if value is not None: d["value"]=value
    return d

defs=[
# ── ACT 2 ────────────────────────────────────────────────────────────────
D("cat","rows","green","the whole file, at once","a file's entire contents arriving in one go, and what that means for a large log.",
 {"headline":"cat prints [everything], instantly","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"/etc",
  "steps":S(st("cat hosts",2,"127.0.0.1 localhost","fine: 3 lines"),st("cat api.log",9,"... 10,241 lines flew past","not fine: 10k lines")),
  "stage":S(it("hosts",4,"3 lines","readable","green"),it("api.log",11,"10,241 lines","unreadable","red")),
  "verdict":"cat has no brakes","verdictSub":"that is what less is for","verdictAtWord":15}),
D("tac","rows","green","the same file, reversed","the file's lines arriving bottom-up, newest entry first.",
 {"headline":"tac is cat, [backwards]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log",
  "steps":S(st("cat api.log",2,"09:01 started","oldest first"),st("tac api.log",8,"09:47 crashed","newest first")),
  "stage":S(it("09:47 crashed",10,"line 3","first now","green"),it("09:30 warning",12,"line 2"),it("09:01 started",14,"line 1","last now")),
  "verdict":"Newest first, no flags","verdictSub":"handy when the tail is what matters","verdictAtWord":16}),
D("more","rows","blue","a one-way window","a long file shown a screen at a time, with no way to travel back up.",
 {"headline":"more only goes [forward]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log",
  "steps":S(st("more api.log",2,"--More--(24%)","space for the next screen")),
  "stage":S(it("screen 1",4,"lines 1-40","shown"),it("screen 2",6,"lines 41-80","shown"),it("go back?",9,"not possible","no","red")),
  "verdict":"Reaches the end and quits","verdictSub":"which is why less replaced it","verdictAtWord":12}),
D("less","rows","blue","travel in both directions","the same paging, now able to scroll back and search inside the file.",
 {"headline":"less goes [both ways]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log","highlight":"/",
  "steps":S(st("less api.log",2,"","arrow keys move freely"),st("/timeout",8,"line 412 matched","slash searches inside")),
  "stage":S(it("scroll down",4,"page forward","yes","green"),it("scroll up",6,"page back","yes","green"),it("/pattern",10,"search in file","yes","green")),
  "verdict":"Never loads the whole file","verdictSub":"so it opens a 10GB log instantly","verdictAtWord":13}),
D("tail","rows","orange","the live end of a log","the last lines of a file, then new lines arriving as the service writes them.",
 {"headline":"tail -f watches it [happen]","color":"orange","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log","highlight":"-f",
  "steps":S(st("tail -n 20 api.log",2,"","the last 20 lines"),st("tail -f api.log",9,"","and now it stays open")),
  "stage":S(it("GET /health 200",11,"","arrived"),it("POST /login 200",13,"","arrived"),it("upstream timeout",15,"","arrived","red")),
  "verdict":"The command you leave running","verdictSub":"while you reproduce the bug","verdictAtWord":18}),
D("vi","flow","purple","which mode you are in","the two modes and the keys that move between them, including the way out.",
 {"headline":"vi has [two modes]","color":"purple","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"i",
  "steps":S(st("vi notes.md",2,"","opens in command mode"),st("i",7,"-- INSERT --","now keys are text"),st(":wq",13,"","write and quit")),
  "stage":S(it("command mode",4,"keys are commands","start"),it("press i",9,"keys become text","insert","green"),it("press Escape",11,"back to commands","command"),it(":wq",15,"write, then quit","out","green")),
  "verdict":"Escape, colon, w, q","verdictSub":"the sequence worth memorising once","verdictAtWord":18}),
D("diff","rows","yellow","only what changed","two files compared line by line with just the differences surfacing.",
 {"headline":"diff shows [only the change]","color":"yellow","atWord":1,"promptLabel":"santhu@box","cwd":"/etc/nginx",
  "steps":S(st("diff old.conf new.conf",2,"< listen 80;","> listen 443 ssl;")),
  "stage":S(it("listen 80;",5,"removed","-","red"),it("listen 443 ssl;",7,"added","+","green"),it("everything else",10,"identical","skipped")),
  "verdict":"Two lines, not two files","verdictSub":"diff -u is what patches are made of","verdictAtWord":13}),
D("find","tree","green","what survives every test","the tree being walked and each candidate tested against the criteria you gave.",
 {"headline":"find [tests] every single file","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log","highlight":"-mtime",
  "steps":S(st("find . -name '*.log'",2,"","by name"),st("find . -name '*.log' -mtime -2",10,"","and by age")),
  "stage":S(it("api.log",5,"1 hour old",value=0,color="green"),it("web.log",7,"2 hours old",value=0,color="green"),
            it("old.log",12,"90 days old",value=0,color="red"),it("notes.md",14,"not a .log",value=0,color="red")),
  "verdict":"Slow because it really looks","verdictSub":"no index, no guessing","verdictAtWord":17}),
D("locate","rows","orange","an index, not the disk","an overnight database answering instantly while the real tree has already moved on.",
 {"headline":"locate is fast, and can be [wrong]","color":"orange","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("locate notes.md",2,"/home/santhu/notes.md","instant"),st("locate new.md",9,"(no results)","created an hour ago")),
  "stage":S(it("index built",4,"03:00 last night","9h ago"),it("notes.md",6,"in the index","found","green"),it("new.md",11,"made at 08:00","missing","red")),
  "verdict":"Run updatedb to refresh","verdictSub":"or use find when it must be current","verdictAtWord":14}),
D("grep","rows","orange","every line that matches","a pattern sweeping the file with matching lines lighting and the rest falling away.",
 {"headline":"grep finds the [matching lines]","color":"orange","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log","highlight":"-v",
  "steps":S(st("grep timeout api.log",2,"412: upstream timeout","every matching line"),
            st("grep -c timeout api.log",9,"4","just the count"),
            st("grep -v timeout api.log",15,"","everything that does not match")),
  "stage":S(it("-i",5,"ignore case","flag"),it("-r",7,"walk directories","flag"),
            it("-c",11,"count matches","4","green"),it("-v",17,"invert the match","flag","purple")),
  "verdict":"-v is the one people forget","verdictSub":"show me everything except this","verdictAtWord":20}),
D("awk","rows","blue","one column, pulled out","each line splitting into numbered fields so a single column can be printed or summed.",
 {"headline":"awk splits a line into [fields]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("df -h | awk '{print $3}'",2,"28G","the third column only"),
            st("awk '{s+=$3} END {print s}'",10,"119G","and the sum of it")),
  "stage":S(it("$1 filesystem",5,"/dev/sda1"),it("$2 size",7,"40G"),it("$3 used",9,"28G","","green")),
  "verdict":"Whitespace splits it for free","verdictSub":"no parsing code required","verdictAtWord":14}),
D("sed","flow","purple","text changing as it passes","a stream flowing through a substitution and coming out altered, one line at a time.",
 {"headline":"sed edits the [stream]","color":"purple","atWord":1,"promptLabel":"santhu@box","cwd":"~","highlight":"g",
  "steps":S(st("sed 's/8080/443/' app.conf",2,"","first match on each line"),
            st("sed 's/8080/443/g' app.conf",10,"","g means every match")),
  "stage":S(it("read a line",4,"from the file"),it("match s/8080/443/",6,"the pattern"),
            it("emit the change",8,"altered line","","green"),it("add g",12,"every match, not the first","","purple")),
  "verdict":"-i edits the file in place","verdictSub":"without it, nothing is saved","verdictAtWord":15}),
D("xargs","flow","green","a list becoming arguments","names arriving on standard input being handed to a command that only reads arguments.",
 {"headline":"xargs turns input into [arguments]","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"/var/log",
  "steps":S(st("find . -name '*.log' | rm",2,"rm: missing operand","rm reads arguments, not input"),
            st("find . -name '*.log' | xargs rm",11,"","now the names become arguments")),
  "stage":S(it("find prints names",4,"on standard input"),it("rm expects arguments",6,"nothing arrives","fails","red"),
            it("xargs converts",13,"input becomes arguments","","green"),it("rm a.log b.log",15,"one call, all names","runs","green")),
  "verdict":"-print0 with -0 for odd names","verdictSub":"spaces in filenames break the naive form","verdictAtWord":18}),

# ── ACT 3 ────────────────────────────────────────────────────────────────
D("chmod","perms","orange","the nine switches","the permission triples flipping and the octal digits resolving beneath them.",
 {"headline":"chmod flips [nine switches]","color":"orange","atWord":1,"promptLabel":"santhu@box","cwd":"~/bin",
  "perms":"rwxr-xr-x","permsAtWord":6,
  "steps":S(st("chmod 755 deploy.sh",2,"","numeric form"),st("chmod u=rwx,go=rx deploy.sh",11,"","the same thing, spelled out")),
  "stage":S(),"verdict":"7 is read plus write plus execute","verdictSub":"5 drops the write. That is all 755 means.","verdictAtWord":15}),
D("chown","rows","orange","who the file answers to","the owner and group labels changing hands, and the access that follows them.",
 {"headline":"chown hands the file [to someone]","color":"orange","atWord":1,"promptLabel":"root@box","cwd":"/srv",
  "steps":S(st("chown deploy app.py",2,"","new owner"),st("chown deploy:www app.py",9,"","owner and group")),
  "stage":S(it("owner",4,"was santhu","now deploy","green"),it("group",11,"was staff","now www","green"),
            it("the first rwx triple",14,"now applies to deploy","moved")),
  "verdict":"Permissions did not change","verdictSub":"but who they apply to did","verdictAtWord":17}),
D("umask","flow","yellow","what new files are born with","the default bits meeting the mask, and the permissions that survive it.",
 {"headline":"umask decides what [new files] get","color":"yellow","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("umask",2,"0022","your current mask"),st("touch fresh.txt",8,"-rw-r--r--","644, not 666")),
  "stage":S(it("666",4,"the default for a file","start"),it("- 022",6,"your mask","subtract"),
            it("= 644",10,"what you actually get","result","green")),
  "verdict":"Directories start from 777","verdictSub":"so the same mask yields 755","verdictAtWord":13}),
D("sudo","rows","red","one command, borrowed power","a single command carried past a rule check, with the log entry it leaves behind.",
 {"headline":"sudo lends power for [one command]","color":"red","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("systemctl restart nginx",2,"Access denied","not privileged"),
            st("sudo systemctl restart nginx",8,"[sudo] password for santhu:","checked against sudoers")),
  "stage":S(it("the sudoers rule",5,"is santhu allowed?","yes","green"),it("the command",10,"runs as root","once"),
            it("the audit log",13,"santhu ran this","recorded","orange")),
  "verdict":"Power ends with the command","verdictSub":"you are not root afterwards","verdictAtWord":16}),
D("useradd","rows","orange","everything it touches","the four separate places a single account creation writes to.",
 {"headline":"useradd writes to [four places]","color":"orange","atWord":1,"promptLabel":"root@box","cwd":"~","highlight":"-m",
  "steps":S(st("useradd deploy",2,"","account, but no home"),st("useradd -m -s /bin/bash deploy",9,"","-m makes the home directory")),
  "stage":S(it("/etc/passwd",4,"the account line","written","green"),it("/etc/shadow",6,"the password hash","written","green"),
            it("a primary group",11,"same name as the user","created","green"),it("/home/deploy",13,"only with -m","conditional","orange")),
  "verdict":"No -m means no home directory","verdictSub":"and the first login lands in /","verdictAtWord":16}),
D("usermod","rows","red","append, or replace","the difference between adding a group and overwriting every group the user had.",
 {"headline":"-aG appends. [-G replaces]","color":"red","atWord":1,"promptLabel":"root@box","cwd":"~","highlight":"-aG",
  "steps":S(st("usermod -aG docker deploy",2,"","appends docker"),st("usermod -G docker deploy",9,"","replaces everything")),
  "stage":S(it("before",4,"sudo, www, dev","3 groups"),it("after -aG",6,"sudo, www, dev, docker","4 groups","green"),
            it("after -G",11,"docker","1 group","red")),
  "verdict":"Forgetting the a locks people out","verdictSub":"including out of sudo","verdictAtWord":14}),
D("userdel","rows","red","what gets left behind","the account record disappearing while the home directory quietly stays.",
 {"headline":"userdel leaves the [home directory]","color":"red","atWord":1,"promptLabel":"root@box","cwd":"/home","highlight":"-r",
  "steps":S(st("userdel deploy",2,"","account gone"),st("userdel -r deploy",9,"","-r takes the home too")),
  "stage":S(it("/etc/passwd entry",4,"removed","gone","green"),it("/home/deploy",6,"still on disk","orphan","orange"),
            it("with -r",11,"home removed too","gone","green")),
  "verdict":"Orphaned folders owned by a number","verdictSub":"the user id outlives the name","verdictAtWord":14}),
D("passwd","flow","green","what actually gets stored","a password becoming a one-way hash, with the plaintext never written anywhere.",
 {"headline":"passwd stores a [hash], never the word","color":"green","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("passwd",2,"New password:","typed, never echoed")),
  "stage":S(it("what you type",5,"hunter2","plaintext"),it("one-way hash",7,"sha512-crypt","transform"),
            it("what is saved",9,"$6$rounds$9fa3...","in /etc/shadow","green")),
  "verdict":"Nobody can hand it back","verdictSub":"a reset is the only way in","verdictAtWord":12}),
D("chpasswd","rows","green","a hundred at once","user and password pairs arriving on standard input and being set in bulk.",
 {"headline":"chpasswd sets them [in bulk]","color":"green","atWord":1,"promptLabel":"root@box","cwd":"~",
  "steps":S(st("cat users.txt | chpasswd",2,"","one pair per line")),
  "stage":S(it("deploy:s3cret",4,"line 1","set","green"),it("ci:b0tpass",6,"line 2","set","green"),it("...98 more",8,"","set","green")),
  "verdict":"Scriptable, unlike passwd","verdictSub":"passwd insists on a terminal","verdictAtWord":11}),
D("w","rows","blue","who is on the box now","the current sessions with what each person is running right this second.",
 {"headline":"w shows who is on [right now]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("w",2,"santhu  pts/0  vim","one row per live session")),
  "stage":S(it("santhu",4,"pts/0","vim","green"),it("deploy",6,"pts/1","rsync","green"),it("load average",9,"the header line","0.42")),
  "verdict":"Sessions, not accounts","verdictSub":"one person logged in twice is two rows","verdictAtWord":12}),
D("last","rows","blue","who was here before","login history read back from the wtmp record, reaching weeks into the past.",
 {"headline":"last reads the [login history]","color":"blue","atWord":1,"promptLabel":"santhu@box","cwd":"~",
  "steps":S(st("last -n 5",2,"root pts/0 Tue 03:12","from /var/log/wtmp")),
  "stage":S(it("root",4,"Tue 03:12","suspicious","red"),it("santhu",6,"Mon 09:01","normal"),it("reboot",8,"Sun 22:40","system")),
  "verdict":"First place to look after a breach","verdictSub":"and the first thing an attacker clears","verdictAtWord":11}),
D("chroot","rows","orange","what the process can see","a false root that hides everything above it, and the caveat that root walks out.",
 {"headline":"chroot is a fence, [not a wall]","color":"orange","atWord":1,"promptLabel":"root@box","cwd":"/mnt",
  "steps":S(st("chroot /mnt/recovery /bin/bash",2,"","a new root for this shell")),
  "stage":S(it("ls /",5,"shows the jail only","works","green"),it("cd ..",7,"cannot climb out","blocked","green"),
            it("root escapes",10,"with the right syscalls","possible","red")),
  "verdict":"Isolation, never security","verdictSub":"use containers when you mean security","verdictAtWord":13}),
]
json.dump(defs,open('briefs/linux/defs_a23.json','w'),indent=1)
print(len(defs),"definitions")
