# -*- coding: utf-8 -*-
# The caption above the right-hand stage. One per command: a generic "what happens"
# on all 110 is the card-with-a-label feel the owner rejected.
CAP = {
"s07":"where you are standing","s08":"the trail from the root","s09":"what the listing becomes",
"s10":"the tree growing","s11":"the file's two clocks","s12":"two sets of bytes",
"s13":"one inode, a new name","s14":"the delete gate","s15":"names pointing at data",
"s16":"screen, and scrollback","s20":"the whole file, at once","s21":"the order reversed",
"s22":"one screen, forwards only","s23":"the viewport, both ways","s24":"new lines arriving",
"s25":"the two modes","s26":"only what changed","s27":"every file, tested",
"s28":"index versus disk","s29":"the lines that match","s30":"the line, split into fields",
"s31":"lines through the transform","s32":"the pipe, adapted","s36":"nine switches",
"s37":"who the switches apply to","s38":"666 minus your mask","s39":"the gate, and the badge",
"s40":"four files written","s41":"the group list","s42":"what stays on disk",
"s43":"the one-way hash","s44":"pairs down the pipe","s45":"one card per session",
"s46":"the login ledger","s47":"the new root boundary","s51":"the snapshot, and the PID",
"s52":"who started whom","s53":"the rows re-sorting","s54":"one bar per core",
"s55":"the last sixty seconds","s56":"rewinding to the spike","s57":"the one that turns red",
"s58":"the panels you choose","s59":"the signal's path","s60":"everything that matches",
"s61":"the hangup signal","s62":"the script, paused","s63":"three timelines",
"s64":"who holds the handle","s65":"across the kernel line","s69":"load against cores",
"s70":"one bar, four segments","s71":"the rows, and the swap","s72":"the queue in front",
"s73":"sorted by disk","s74":"one time axis","s75":"yesterday, replayed","s76":"the loop",
"s80":"space, and inodes","s81":"the treemap narrowing","s82":"browsing down",
"s83":"in memory until w","s84":"the address field","s85":"names versus UUIDs",
"s86":"structure written over","s87":"the sweep","s88":"grafted into one tree",
"s89":"the handles holding it","s90":"source, target, arrow","s95":"three layers",
"s96":"there, and back","s97":"hop by hop","s98":"loss per hop",
"s99":"two routes, same answer","s100":"doors, and live pipes","s101":"one device, many profiles",
"s102":"traffic by pair","s103":"traffic by process","s104":"in, and out",
"s108":"the answer, and its TTL","s109":"three depths","s110":"the cache in between",
"s111":"the registry record","s112":"which half travels","s113":"the colon does the work",
"s114":"compared, then sent","s115":"three different answers","s116":"resuming at 61%",
"s117":"the request, assembled","s121":"four letters, four actions","s122":"the original, consumed",
"s123":"the trade, timed","s124":"stream versus index","s125":"five fields, one clock",
"s126":"validated, or not","s127":"the execute bit","s128":"which shell sees it",
"s129":"the scope of a variable","s130":"reaching back","s131":"the session survives",
"s132":"panes in one session","s133":"two separate switches","s134":"filters narrowing",
"s135":"the ring, wrapping","s139":"numbered shelves","s140":"searched by description",
"s141":"1,241 lines versus 8","s142":"your own shelf","s143":"present, and bound",
"s144":"the USB tree",
}
