# -*- coding: utf-8 -*-
# An anchor-free LANDING LINE for every command beat.
#
# Two rules met at once. LAW 8: the last anchor must sit before the final 15% or the
# payoff animates into the scene tail with no time to read it. LAW 0f rule 8: "Land
# it — end the beat on the sentence you'd want them to repeat to a colleague." The
# first cut had neither; the verdict was the last thing said and the scene stopped.
LAND = {
"s07":"So a path is just directions to a place that was already there, and cd walks them for you.",
"s08":"When a script needs to know where it is, pwd is the answer it can rely on.",
"s09":"Reach for ls dash L H by default, because the extra columns cost you nothing.",
"s10":"Type mkdir dash P out of habit and you'll never meet that error again.",
"s11":"Touch exists to move a clock forward, and that turns out to be worth a whole command.",
"s12":"Copy when you want two things. Move when you want one thing somewhere else.",
"s13":"That's also why moving a file to another disk takes time when renaming it never does.",
"s14":"Type the path out in full before you press return, every single time.",
"s15":"Use a hard link for a second real name, and a symlink when you want a pointer.",
"s16":"On somebody else's machine, assume clear removed nothing at all.",
"s20":"Use cat for a config file you can see all of, and less for anything bigger.",
"s21":"It's a one-word change from cat, and on a log it saves you a scroll every time.",
"s22":"You'll still meet more on a stripped-down system, so it's worth knowing why it annoys you.",
"s23":"Less is the reader you should reach for by default, whatever the size of the file.",
"s24":"Two windows, tail dash F in one of them, and the bug tells you about itself.",
"s25":"And if you ever land in vi by accident, that same sequence is how you get out.",
"s26":"Before you edit any config on a live server, diff it against the one that worked.",
"s27":"When correctness matters more than speed, find is the tool that will not lie to you.",
"s28":"Reach for locate when you're guessing, and find when you need to be certain.",
"s29":"Grep is the tool you'll type more than any other, so the flags repay learning properly.",
"s30":"Any time you catch yourself about to write a script to read columns, try awk first.",
"s31":"Run it without dash I once, read the output, then run it again with dash I.",
"s32":"Whenever a pipe seems to do nothing at all, xargs is usually the missing piece.",
"s36":"Read any permission string in threes and the number stops being something you memorise.",
"s37":"So when a service can't read its own config, check the owner before you change the mode.",
"s38":"You'll rarely change your umask, but knowing it exists explains every new file you make.",
"s39":"Use sudo for the one command that needs it, and stay yourself for everything else.",
"s40":"Use useradd dash M dash S, or use adduser, which asks you the questions instead.",
"s41":"Read that flag out loud before you press return: dash A capital G, append.",
"s42":"If you're removing somebody properly, remove their files deliberately rather than leaving them behind.",
"s43":"So when somebody asks you to look up their password, the honest answer is that you can't.",
"s44":"Use passwd for a person at a keyboard, and chpasswd for a machine doing it in bulk.",
"s45":"Run w before you reboot anything, because somebody else may be halfway through something.",
"s46":"Read last early, save the output somewhere else, and then start investigating.",
"s47":"Keep chroot for rescue work, and let containers do the job it was never built for.",
"s51":"Get comfortable finding a PID quickly, because almost everything after this needs one.",
"s52":"Whenever a process seems to have no parent, pstree shows you it was adopted rather than orphaned.",
"s53":"Watch top for ten seconds before you conclude anything, because one frame tells you very little.",
"s54":"Install htop on any machine you'll spend real time on. You'll stop opening top entirely.",
"s55":"Use btop when the question is where this is heading rather than where it is.",
"s56":"Install atop today, and the next outage will be one you can actually investigate.",
"s57":"Glances is the one to reach for when you know something is wrong but not what.",
"s58":"Leave nmon recording overnight and you'll have a graph instead of a guess in the morning.",
"s59":"If sig term hasn't worked after ten seconds, the process is stuck, and only then use dash nine.",
"s60":"On anything shared, find the PIDs and kill those. It takes ten more seconds and costs nobody an afternoon.",
"s61":"Better still, use screen or tmux, which we'll get to, and you keep the output as well.",
"s62":"Sleep is what makes a retry loop polite instead of a machine hammering a server.",
"s63":"One word at the end of a script is the difference between a real result and a lie.",
"s64":"Lsof is the tool that turns a useless error message into a process you can name.",
"s65":"Strace is a big hammer, so reach for it when the error message has already lied to you.",
"s69":"Load is a queue length, not a percentage, and that one sentence fixes most of the confusion.",
"s70":"Free memory on a Linux box is wasted memory, and the kernel is doing you a favour.",
"s71":"Watch the swap columns for ten seconds, and you'll know whether memory is the real problem.",
"s72":"When the CPU looks idle and everything feels slow, await is the number to go and read.",
"s73":"Iostat and iotop are a pair: one finds the problem, the other names who caused it.",
"s74":"Dstat is what you leave running while you reproduce something, because the columns line up.",
"s75":"Turn sysstat on across your machines this week, and thank yourself during the next incident.",
"s76":"Any time you find yourself pressing up and return repeatedly, watch is the command you wanted.",
"s80":"So when writes fail on a disk with space left, df dash I is the second thing you run.",
"s81":"Df then du then ncdu is the sequence, and it narrows the answer every step.",
"s82":"Install ncdu on every server. The first time a disk fills up, it pays for itself.",
"s83":"Because nothing is written until W, fdisk dash L is safe to run anywhere, any time.",
"s84":"Use parted for anything modern, and treat MBR as something you only meet on old disks.",
"s85":"Anything you want mounted at boot goes in fstab by UUID, and it will still be there next year.",
"s86":"Read the device name out loud, check it against lsblk, and only then press return.",
"s87":"Unmount, then check, then mount again. In that order, fsck is a repair rather than a risk.",
"s88":"Mount an empty directory, always, and you'll never wonder where your files went.",
"s89":"When a disk won't unmount, lsof answers it in one command, so reach for that instead of force.",
"s90":"Read the of= argument twice, out loud, before you press return. Every single time.",
"s95":"Learn ip addr, ip route and ip link, and you can describe any machine's networking.",
"s96":"Run ping with dash C four, read the loss line first, and the latency second.",
"s97":"Traceroute tells you where the path goes; it takes judgement to say where it breaks.",
"s98":"Leave mtr running for a minute before you phone anybody about a network problem.",
"s99":"Learn the ss flags now, because netstat isn't installed by default on newer systems.",
"s100":"Ss dash T U L P N is worth committing to memory. You'll type it weekly.",
"s101":"Think of it as a device and a set of profiles, and nmcli stops being confusing.",
"s102":"Iftop and nethogs together answer the whole question, so install both while you're there.",
"s103":"Nethogs is the one that ends the argument about whose job is saturating the link.",
"s104":"When you already know the question, a small tool beats a dashboard every time.",
"s108":"Dig is the tool to reach for the moment you suspect DNS, which is more often than you'd think.",
"s109":"Host for a quick yes or no, dig the moment that answer surprises you.",
"s110":"So if somebody sends you that output as evidence of a fault, it usually isn't one.",
"s111":"Put every domain you own in a calendar, because nobody reads the registrar's email.",
"s113":"Check the colon, then check the destination path, and scp will do exactly what you meant.",
"s114":"Dry run, read the plan, then run it properly. That habit will save you a restore.",
"s115":"One nc command tells you whether to debug the application or the network, which saves an hour.",
"s117":"Curl is worth learning properly, because it's how you find out what a server truly returned.",
"s121":"Tar dash X Z V F to extract, tar dash C Z V F to create, and you're done with tar.",
"s122":"Use dash K whenever a script downstream still expects the original file to be there.",
"s123":"Gzip for anything you touch often, bzip2 or xz for anything you're storing and forgetting.",
"s125":"Read the five fields left to right, and any cron line becomes plain English.",
"s126":"Always use crontab dash E, then crontab dash L to confirm what actually got installed.",
"s127":"Shebang, chmod plus X, then dot slash. Three things, and your script runs anywhere.",
"s128":"Put your aliases in bashrc, and put the real command in your scripts.",
"s129":"Setting a variable in front of a command is the safest way to try something once.",
"s130":"Sudo bang bang will save you more typing this year than any other two words here.",
"s131":"Start anything long inside screen or tmux, and a dropped connection stops mattering.",
"s132":"Tmux is worth an afternoon of practice, because it changes how you work on servers.",
"s133":"Systemctl enable dash dash now is the command you actually wanted, nearly every time.",
"s134":"Compose the filters and journalctl goes from overwhelming to the fastest log tool you own.",
"s135":"Dmesg dash T piped into tail is worth running whenever a machine behaves strangely.",
"s139":"When a manual page seems to answer the wrong question, check the section number first.",
"s140":"Apropos is the command to remember for the days you've forgotten every other one.",
"s141":"Install tldr today. It'll save you the twelve hundred lines you didn't want to read.",
"s142":"Your own notes, written once, beat re-reading somebody else's documentation three times.",
"s143":"Present and working are two different states, and lspci dash K is what tells them apart.",
"s144":"Before you replace a slow drive, look at the tree and try a different port.",
}
