// Archify — VERTICAL CUT (~50s). Cut from the same four takes as the wide cut; every claim
// is in briefs/archify/00-dossier.md. The short's job is one idea: the map is generated from
// your own source AND checked before you see it.
import {cut} from '../../scripts/lib/apple-build.mjs';

const c = cut();

const wordIndex = (narration, phrase) => {
  const norm = (x) => x.replace(/[^\w']/g, '').toLowerCase();
  const w = narration.split(/\s+/), p = phrase.split(/\s+/);
  for (let i = 0; i < w.length; i++) if (p.every((x, j) => norm(w[i + j] ?? '') === norm(x))) return i + 1;
  throw new Error(`camera phrase not found in narration: "${phrase}"`);
};

const LOCAL = 'Generated by Archify · one self-contained HTML file';
const LOCALDEV = 'VS Code for the Web · Claude Code, live';

const rec = (defTake) => (transition, bg, narration, source, clips) =>
  c.add('RECORDED_STEP', transition, bg, narration, (A) => ({
    clips: clips.map((k) => ({
      ref: `rec:${k.take ?? defTake}#${k.step}`, label: k.label, focus: k.focus ?? false, atWord: A(k.at ?? 0.05),
      ...(k.pivot ? {wantAtWord: wordIndex(narration, k.pivot)} : {}),
      zooms: (k.camera ?? []).map((m) => (m.frame === 'full'
        ? {at: 'full', wantAtWord: wordIndex(narration, m.at)}
        : {marks: [].concat(m.frame), ...(m.band ? {band: true} : {}), wantAtWord: wordIndex(narration, m.at)})),
      callouts: [],
    })),
    sourceNote: source,
  }));

const live = rec('archify-live');
const art = rec('archify-artifact');

c.add('HOOK', 'dip', 'zoneA',
  "Archify draws your architecture from your own code.",
  (A) => ({
    headline: 'Archify: your system, drawn',
    subtext: 'One prompt, one checked map',
    heroAsset: 'img:archify_map_hero.png',
    hookVariant: 'reveal',
    atWord: A(0.5),
  }));

// Prompt -> the JSON written and repaired -> the delivered report. Pieces cut from the one
// recorded run (scripts/split-rec-step.mjs); nothing is reordered or sped up.
live('fade', 'zoneB',
  "I gave Claude Code one prompt: use Archify on this repository, twelve nodes at most, one primary path, and " +
  "these files as evidence. It reads that code, writes a typed JSON file — there it is in the explorer — and " +
  "validates it straight away. The first attempt fails, so the agent reads what the checker reported, fixes it, " +
  "and runs the check again, one fix at a time. Three rounds of fixes later, every check passes. It delivers one " +
  "HTML file, with a hash for both files, and three architecture insights about this project. " +
  "The one I'd read twice is the second insight: every safety check lives in one script, so " +
  "calling Remotion directly skips all of them.",
  LOCALDEV,
  [
    {step: 'prompt-s', pivot: 'I gave Claude Code one prompt', label: 'one prompt'},
    {step: 'write-s', pivot: 'It reads that code', label: 'write, validate, repair'},
    {step: 'result-s2', pivot: 'Three rounds of fixes later', label: 'delivered, with insights'},
  ]);

art('iris', 'zoneB',
  "And what you get is one HTML file you can actually interrogate — this is our own video pipeline, drawn from " +
  "our own source. Press slash, type a name, and the map jumps straight to that node and shows you what it " +
  "connects to, with every relationship on screen coming out of the typed file the agent wrote. Nothing was " +
  "invented later to make the picture look tidier than the system really is. That is the difference between a " +
  "diagram you present once and a map your team can actually rely on.",
  LOCAL,
  [
    {step: 'map', pivot: 'And what you get', label: 'one HTML file', camera: [
      {at: 'this is our own video pipeline', frame: 'full'}]},
    {step: 'findhit', pivot: 'Press slash, type a name', label: 'type a name'},
  ]);

c.add('OUTRO_CTA', 'fade', 'zoneA',
  "Archify is MIT licensed, and the full walkthrough is on the channel. What would you map first?",
  (A) => ({
    headline: 'What would you map first?',
    subtext: 'github.com/tt-a1i/archify — MIT',
    atWord: A(0.5),
  }));

const spec = {
  meta: {
    topic: 'Archify — one prompt, one checked architecture map',
    format: 'shorts',
    fps: 30,
    subject: 'Archify',
    audioPrefix: 'archify-live-map_shorts',
    onePayoff: 'an architecture map generated from your own source and validated before you see it',
    openLoop: 'Can an agent draw your architecture and prove it is right?',
    topicAxes: ['entity-novelty'],
    screenplay: 'documentary',
    seo: {
      title: 'System architects, you are missing this #architecture #softwareengineering',
      hook:
        'Archify is an MIT-licensed agent skill: your coding agent writes a typed JSON file, and Archify compiles ' +
        'it into one self-contained interactive architecture map — validated before you ever see it.',
      description:
        'Nine checks, zero errors, one HTML file you can search and trace. Full walkthrough on the channel.',
      breakdown: 'the prompt, the live run, and the map you can interrogate',
      pinned: 'Write the prompt like a spec: scope, node budget, evidence files. What would you map first?',
      tags: ['Archify', 'architecture diagram', 'diagrams as code', 'system design', 'Claude Code',
        'agent skills', 'software architecture', 'developer tools', 'shorts'],
      queries: ['how to generate architecture diagrams from code', 'Archify tutorial'],
      sources: [
        'github.com/tt-a1i/archify — Archify by tt-a1i (MIT)',
        'github.com/san-gitlogin/iauteur — the repository mapped in the demo',
      ],
    },
  },
  brand: c.brand(),
  thumbnail: {
    title: 'ARCHITECTS ARE MISSING THIS',
    badge: 'Archify',
    note: 'MAPPED LIVE · MIT',
    asset: 'img:archify_map_hero.png',
    art: 'img:archify_map_hero.png',
  },
  cover: {
    title: 'ARCHITECTS ARE MISSING THIS',
    badge: 'Archify',
    asset: 'img:archify_map_hero.png',
    art: 'img:archify_map_hero.png',
    frames: 2,
  },
  scenes: c.S,
};

c.emit('topics/archify-live-map/shorts.json', spec);
