// Archify — the agent skill that draws your system. WIDE CUT.
//
// Every claim comes from briefs/archify/00-dossier.md (the repo's own README and SKILL.md) or
// from the four takes recorded for this video. The rule that governs the script is in the
// dossier under "THE PROMPT IS THE SPEC": the map exists in the shape it does because of how
// the instruction was written, and the narration says so out loud.
//
// Takes: archify-gh (the repository), archify-live (Claude Code running the skill),
// archify-verify (what it produced), archify-artifact (driving the generated HTML).
import {cut} from '../../scripts/lib/apple-build.mjs';

const c = cut();

const wordIndex = (narration, phrase) => {
  const norm = (x) => x.replace(/[^\w']/g, '').toLowerCase();
  const w = narration.split(/\s+/), p = phrase.split(/\s+/);
  for (let i = 0; i < w.length; i++) if (p.every((x, j) => norm(w[i + j] ?? '') === norm(x))) return i + 1;
  throw new Error(`camera phrase not found in narration: "${phrase}"`);
};

const ARCHIFY = 'tt-a1i · github.com/tt-a1i/archify · MIT';
const IAUTEUR = 'github.com/san-gitlogin/iauteur — the repository being mapped';
const LOCALDEV = 'VS Code for the Web · this project';
const LOCAL = 'Generated by Archify from that repository · one self-contained HTML file';

// A recorded beat. Clips may come from different takes (`take`), and each carries its own
// credit when it quotes a different page. The camera is scripted by the exact phrase that
// names what it frames; `band` lays the quiet highlight on it, `full` pulls back.
const rec = (defTake) => (transition, bg, narration, source, clips) =>
  c.add('RECORDED_STEP', transition, bg, narration, (A) => ({
    clips: clips.map((k) => ({
      ref: `rec:${k.take ?? defTake}#${k.step}`, label: k.label, focus: true, atWord: A(k.at ?? 0.05),
      ...(k.pivot ? {wantAtWord: wordIndex(narration, k.pivot)} : {}),
      ...(k.source ? {sourceNote: k.source} : {}),
      zooms: (k.camera ?? []).map((m) => (m.frame === 'full'
        ? {at: 'full', wantAtWord: wordIndex(narration, m.at)}
        : {marks: [].concat(m.frame), ...(m.band ? {band: true} : {}), wantAtWord: wordIndex(narration, m.at)})),
      callouts: [],
    })),
    sourceNote: source,
  }));

const gh = rec('archify-gh');
const live = rec('archify-live');
const verify = rec('archify-verify');
const art = rec('archify-artifact');

// ── 1 · HOOK ─────────────────────────────────────────────────────────────────────────
c.add('HOOK', 'dip', 'zoneA',
  "Archify turns one sentence into a system map you can actually explore.",
  (A) => ({
    headline: 'Archify: your system, drawn',
    subtext: 'The agent skill architects have been waiting for',
    heroAsset: 'lucide:workflow',
    hookVariant: 'ask',
    atWord: A(0.5),
  }));

// ── 2 · Greeting, intent, the loop ───────────────────────────────────────────────────
c.add('TITLE_CARD', 'fade', 'zoneA',
  "Welcome back. Today we're going to install Archify, point it at a real repository, and watch it produce an " +
  "architecture map you can search, trace and hand to your team. And the interesting part isn't the picture. " +
  "It's that the picture is checked before you ever see it.",
  (A) => ({
    title: 'One prompt. One checked map.',
    subtitle: 'Archify, installed and driven live',
    atWord: A(0.4),
  }));

// ═══ I · WHAT IT IS ═══════════════════════════════════════════════════════════════════
gh('letterbox', 'zoneB',
  "So, what is Archify? This is its page on GitHub, and the description is refreshingly plain: an agent skill for " +
  "architecture, workflow, sequence, data-flow and lifecycle diagrams. Read the line under the title and you get " +
  "the whole idea in one sentence — your agent writes a small typed file, and Archify compiles that file into an " +
  "interactive map. Typed simply means every field has a declared shape, so the tool can check the file instead of " +
  "trusting it. Installing Archify is one line, and that's the entire setup: no service to sign up for, no server " +
  "to run. Scroll to the installation table and you'll see where the skill lands for each agent. For Claude Code " +
  "it's a skills folder, either in your home directory or inside the project itself, and I'll use the project, " +
  "because a skill that travels with the repository is a skill your teammates get for free.",
  ARCHIFY,
  [
    {step: 'repo', label: 'the repository', camera: [
      {at: 'the description is refreshingly plain', frame: 'what', band: true},
      {at: 'Read the line under the title', frame: 'full'}]},
    {step: 'pitch', pivot: 'Read the line under the title', label: 'the idea in one line', camera: [
      {at: 'your agent writes a small typed file', frame: 'turn', band: true},
      {at: 'Typed simply means', frame: 'full'}]},
    {step: 'install', pivot: 'Installing Archify is one line', label: 'one line to install', camera: [
      {at: 'Installing Archify is one line', frame: 'cmd', band: true},
      {at: 'no service to sign up for', frame: 'full'}]},
    {step: 'installs', pivot: 'Scroll to the installation table', label: 'the installation table', camera: [
      {at: 'For Claude Code', frame: 'cc', band: true},
      {at: 'because a skill that travels', frame: 'full'}]},
  ]);

gh('fade', 'zoneA',
  "Before we run anything, two tables are worth your attention. The first one tells you which diagram to ask for: " +
  "architecture for components and boundaries, workflow for approvals and runbooks, sequence for one interaction " +
  "over time, data flow for pipelines and sensitivity, lifecycle for states and retries. Pick the wrong one and " +
  "you'll fight the layout all afternoon. The second table is the part most diagram tools never give you: " +
  "everything the reader can do once the map exists — find a node, trace what reaches it, probe a route between " +
  "two things, compare roles.",
  ARCHIFY,
  [
    {step: 'types', label: 'five diagram types', camera: [
      {at: 'which diagram to ask for', frame: 'table', band: true},
      {at: 'Pick the wrong one', frame: 'full'}]},
    {step: 'keys', pivot: 'The second table', label: 'the second table', camera: [
      {at: 'find a node, trace what reaches it', frame: 'controls', band: true},
      {at: 'compare roles', frame: 'full'}]},
  ]);

// The mechanism, drawn: this is what the next ten minutes actually does.
c.add('PIPELINE', 'iris', 'zoneA',
  "The whole mechanism is four moves. You describe what you want, the agent writes typed JSON, Archify validates " +
  "it against schema and layout rules, and only a passing candidate is delivered as HTML.",
  (A) => ({
    headline: 'How a request becomes a map',
    stages: [
      {label: 'You ask', sub: 'plain English'},
      {label: 'Agent writes', sub: 'typed JSON IR'},
      {label: 'Validate', sub: 'schema + layout'},
      {label: 'Deliver', sub: 'one HTML file', color: 'green'},
    ],
    tokenLabel: 'your request',
    atWord: A(0.25),
  }));

// ═══ II · THE LIVE RUN ════════════════════════════════════════════════════════════════
c.add('CHAPTER', 'push', 'zoneA',
  "Right. Enough reading — let's point Archify at a real codebase and see what comes out.",
  (A) => ({
    number: 'I',
    title: 'Mapping a real repository',
    subtitle: 'Claude Code, in VS Code for the web',
    atWord: A(0.4),
  }));

live('letterbox', 'zoneB',
  "This is the repository we're going to map: iauteur, the open-source project that renders the videos on this " +
  "channel. Nobody has ever drawn its architecture, including me. And here's the skill sitting inside that " +
  "project, in a dot-claude folder: there's a SKILL.md, which is the instruction file the agent reads, and a " +
  "schemas folder, which is what makes the checking possible.",
  IAUTEUR,
  [
    {step: 'target', take: 'archify-gh', pivot: 'This is the repository', label: 'the repository', source: IAUTEUR, camera: [
      {at: 'iauteur, the open-source project', frame: 'name', band: true},
      {at: 'Nobody has ever drawn', frame: 'full'}]},
    {step: 'skill', pivot: "And here's the skill sitting", label: 'the skill, in the project', source: LOCALDEV, camera: [
      {at: "there's a SKILL.md", frame: 'skillmd', band: true},
      {at: 'and a schemas', frame: 'schemas', band: true}]},
  ]);

live('fade', 'zoneB',
  "Now watch this, because it is the part I want you to take away. I'm asking Claude Code, in plain English, to " +
  "use the Archify skill on this repository. Notice how specific the request is: map the video pipeline, keep it " +
  "to ten nodes, show one primary path, and read these particular files as evidence. That specificity is not " +
  "decoration — it is the specification. A vague prompt gives you a vague diagram, every single time. The agent " +
  "loads the skill, then reads the schema so it knows the exact shape it is allowed to produce. It writes a typed " +
  "JSON file describing the system, and then validates that file. Where the checker complains — a label sitting " +
  "too close to a route, a node that needs more room — the agent repairs it and validates again, and keeps going " +
  "until every check passes. Nothing here is drawn by hand. The agent writes a specification, and Archify " +
  "compiles it. And that difference is why this scales past a whiteboard: the map is derived from the source, so " +
  "when the code moves, you run the same sentence again and get a map that matches.",
  null,
  [
    {step: 'ask', pivot: 'Now watch this', label: 'one sentence to the agent'},
  ]);

// The artefact the team reviews — real lines from the file the agent wrote.
c.add('CODE_WINDOW', 'fade', 'zoneB',
  "This is what it wrote. Each node is a few fields: a stable id, a type, the label you see on the map, and where " +
  "it sits. That's the whole trick — your architecture becomes lines you can read in a pull request, diff against " +
  "last month, and argue about properly.",
  (A) => ({
    filename: 'pipeline.architecture.json',
    language: 'json',
    lines: [
      {text: '{ "id": "spec", "type": "edge",'},
      {text: '  "label": "Topic Spec",'},
      {text: '  "sub": "long.json · shorts.json" },'},
      {text: '{ "id": "bake", "type": "backend",'},
      {text: '  "label": "bake-rec.mjs" },'},
      {text: '{ "id": "voice", "type": "backend",'},
      {text: '  "label": "voiceover.py" }'},
    ],
    runLabel: 'the typed source',
    atWord: A(0.3),
  }));

verify('iris', 'zoneB',
  "When the run finishes you have two files: the typed JSON source, and one HTML file. And here's the receipt that " +
  "matters. Archify validated the source at showcase quality, and reports nine artifact checks with zero errors " +
  "and zero warnings. That is the whole argument for this tool. A map that fails its checks never replaces the good " +
  "one on disk, so you cannot accidentally ship a broken diagram. And the source itself stays readable, which " +
  "is the part your reviewers care about, because a map nobody can check is just a picture with confidence. " +
  "Look at the names it chose: here's bake-rec, and here's voiceover — the same steps that turn a script into " +
  "the video you are watching right now.",
  null,
  [
    {step: 'files', label: 'what it produced', camera: [
      {at: 'the typed JSON source', frame: 'json', band: true},
      {at: 'and one HTML file', frame: 'html', band: true}]},
    {step: 'receipt', pivot: "here's the receipt that", label: 'the validation receipt', camera: [
      {at: 'nine artifact checks', frame: 'checks', band: true},
      {at: 'That is the whole argument', frame: 'full'}]},
    {step: 'ir', pivot: 'And the source itself stays readable', label: 'the typed source', camera: [
      {at: 'Look at the names it chose', frame: ['bake', 'voice'], band: true}]},
  ]);

c.add('STAT_PANELS', 'fade', 'zoneA',
  "Three numbers are worth holding on to from that receipt. Nine checks ran. Zero of them failed. And what you " +
  "hand to a colleague is a single file — no server, no account, no login wall between them and the diagram.",
  (A) => ({
    stats: [
      {kicker: 'Checks run', value: '9', atWord: A(0.24)},
      {kicker: 'Failures', value: '0', color: 'green', atWord: A(0.44)},
      {kicker: 'Files to share', value: '1', color: 'green', atWord: A(0.64)},
    ],
    verdict: {text: 'Validated before you see it', color: 'green', atWord: A(0.86)},
    source: 'archify deliver --json, this run',
  }));

// ═══ III · THE ARTIFACT ═══════════════════════════════════════════════════════════════
c.add('CHAPTER', 'push', 'zoneA',
  "So that's the map made. Now let's open it, because this is where Archify stops being a diagram tool.",
  (A) => ({
    number: 'II',
    title: 'The map you can interrogate',
    subtitle: 'One file, no server, no account',
    atWord: A(0.4),
  }));

art('letterbox', 'zoneB',
  "There it is — our pipeline, drawn from our own source. A topic spec goes in on the left, and a rendered video " +
  "comes out on the right. Look at the panel on the side: the agent also authored guided views, small chapters " +
  "through the system, so a newcomer can be walked through it instead of being handed a wall of boxes. Press the " +
  "slash key and you get a node finder. I'll type sync, hit enter, and the map jumps straight to the sync " +
  "step and shows you exactly what it connects to. That sounds small until you're staring at somebody else's platform diagram with " +
  "sixty components on it, hunting for the one service you were paged about at two in the morning. And here is " +
  "the part I trust: every relationship you can trace was written by the agent into that typed source — the " +
  "viewer never invents a connection to make the picture tidier. Play the story and those chapters run in order, " +
  "chapter one, spec preparation, with the diagram itself moving rather than a slide sitting beside it. Exports " +
  "are the last piece: a share card sized for a README or a release post, the full diagram as a picture for " +
  "people who will never open the HTML, and one key that flips the whole thing to a light theme, which matters " +
  "more than it should when your deck is white. And every export carries the whole diagram, not the part you " +
  "happened to be looking at when you pressed the key.",
  LOCAL,
  [
    {step: 'map', pivot: 'There it is', label: 'the generated map', camera: [
      {at: 'A topic spec goes in', frame: 'spec', band: true},
      {at: 'comes out on the right', frame: 'render', band: true}]},
    {step: 'chapters', pivot: 'Look at the panel on the side', label: 'the panel on the side', camera: [
      {at: 'the agent also authored guided views', frame: 'views', band: true},
      {at: 'instead of being handed', frame: 'full'}]},
    {step: 'findtype', pivot: "I'll type sync", label: 'type a name'},
    {step: 'findhit', pivot: 'and the map jumps straight', label: 'straight to that node', camera: [
      {at: 'to the sync step', frame: 'sync', band: true}]},
    {step: 'storygo', pivot: 'Play the story', label: 'play the story'},
    {step: 'story', pivot: 'chapter one, spec preparation', label: 'the story plays', camera: [
      {at: 'with the diagram itself moving', frame: 'ch1', band: true}]},
    {step: 'export', pivot: 'Exports are the last piece', label: 'canonical exports', camera: [
      {at: 'a share card sized for a', frame: 'share', band: true},
      {at: 'the full diagram as a picture', frame: 'full'}]},
    {step: 'theme', pivot: 'that flips the whole thing'},
  ]);

// ═══ IV · THE HONEST LIMITS ═══════════════════════════════════════════════════════════
c.add('QUOTE_SPOTLIGHT', 'fade', 'zoneA',
  "I like that the project says this in its own README: Archify is not a drawing editor. So if you want to nudge " +
  "a box three pixels left with a mouse, this is the wrong tool — you change the typed source and compile again.",
  (A) => ({
    quote: '…general-purpose auto-layout, hosted sharing, and WYSIWYG editing are intentionally outside the current scope.',
    attribution: 'Archify README — tt-a1i',
    source: 'github.com/tt-a1i/archify — README',
    atWord: A(0.35),
  }));

// ── RECAP ────────────────────────────────────────────────────────────────────────────
c.add('RECAP', 'fade', 'zoneA',
  "So here's what to take away. Install the skill next to your code, not just on your laptop, so your teammates " +
  "inherit it. Write the prompt like a specification — name the scope, the node budget, and the files that count " +
  "as evidence. Review the typed JSON in the pull request, the way you review anything else. And let the checks " +
  "fail loudly, because a diagram nobody trusts is worse than no diagram at all.",
  (A) => ({
    heading: 'Four things to take away',
    points: [
      {text: 'Install the skill in the repository', atWord: A(0.16)},
      {text: 'Prompt like a spec: scope, budget, evidence', atWord: A(0.44)},
      {text: 'Review the typed JSON, not the picture', atWord: A(0.68)},
      {text: 'Let validation fail loudly', atWord: A(0.88)},
    ],
  }));

// The link, on screen, with the mark — not just a line in the description.
c.add('REPO_CTA', 'push', 'zoneA',
  "Archify is on GitHub under the MIT licence, written by tt-a1i. The repository carries the skill, the schemas " +
  "and a gallery of checked examples, so you can read exactly what your agent will be asked to produce.",
  (A) => ({
    headline: 'Read it, then point it at your own system',
    mark: 'si:github',
    owner: 'tt-a1i',
    repo: 'archify',
    description: 'Agent skill for architecture, workflow, sequence, data-flow and lifecycle diagrams.',
    facts: [
      {label: 'MIT licence', atWord: A(0.2)},
      {label: 'Five diagram types', atWord: A(0.62)},
    ],
    url: 'github.com/tt-a1i/archify',
    atWord: A(0.08),
  }));

c.add('OUTRO_CTA', 'fade', 'zoneA',
  "Archify is MIT licensed and the link is in the description — go and point it at something you own. And tell me " +
  "what you map first: a service you inherited, or the one nobody has ever drawn?",
  (A) => ({
    headline: 'What will you map first?',
    subtext: 'github.com/tt-a1i/archify — MIT',
    atWord: A(0.5),
  }));

const spec = {
  meta: {
    topic: 'Archify — the agent skill that draws your system',
    format: 'long',
    fps: 30,
    subject: 'Archify',
    // render-long derives the audio prefix from the slug; ours is what voiceover.py was given
    audioPrefix: 'archify-live-map_long',
    onePayoff: 'how one plain-English prompt becomes a checked, explorable architecture map of a real repository',
    openLoop: 'Can an agent draw your architecture and prove it is right?',
    topicAxes: ['entity-novelty', 'workflow'],
    screenplay: 'documentary',
    seo: {
      title: 'If You Design Systems, You Are Missing This — Archify, Tested Live',
      altTitles: [
        'Archify: One Prompt, One Checked Architecture Map (Live Demo)',
        'System Architects Are Going To Love This — Archify On A Real Repo',
        'Everything A System Architect Needs In One File — Archify',
      ],
      hook:
        'Architecture diagrams rot the moment they are drawn. Archify takes a different route: your coding agent ' +
        'writes a small typed JSON file, and Archify deterministically compiles it into one self-contained, ' +
        'interactive HTML map — validated before you ever see it. We install the skill, point Claude Code at a ' +
        'real open-source repository, and drive the result: node finder, guided story, exports and themes.',
      description:
        'Archify is an MIT-licensed agent skill by tt-a1i for architecture, workflow, sequence, data-flow and ' +
        'lifecycle diagrams. In this tutorial we install it into a project, ask Claude Code to map a real ' +
        'repository, read the validation receipt, review the typed JSON source, and explore the generated HTML.',
      breakdown:
        'what Archify actually is, the one-line install, choosing between the five diagram types, a live mapping ' +
        'run on a real repository, the validation receipt, the typed source your team reviews, and the viewer: ' +
        'node finder, guided story, share cards and themes',
      pinned: 'Write the prompt like a spec: scope, node budget, one primary path, and the files that count as evidence. What will you map first?',
      tags: [
        'Archify', 'architecture diagram', 'system architecture', 'software architecture', 'diagrams as code',
        'architecture as code', 'Claude Code', 'agent skills', 'AI coding agent', 'Mermaid alternative',
        'system design', 'sequence diagram', 'data flow diagram', 'developer tools', 'code visualization',
        'technical documentation', 'VS Code', 'open source', 'software engineering', 'solution architect',
      ],
      queries: [
        'how to generate architecture diagrams from code',
        'Archify tutorial',
        'Mermaid alternative for architecture diagrams',
        'Claude Code skills explained',
        'diagrams as code for system design',
      ],
      sources: [
        'github.com/tt-a1i/archify — Archify by tt-a1i (MIT)',
        'tt-a1i.github.io/archify — project page, scenario guide and Proof Lab',
        'github.com/san-gitlogin/iauteur — the repository mapped in the demo',
      ],
    },
  },
  brand: c.brand(),
  thumbnail: {
    title: 'ARCHITECTS ARE MISSING THIS',
    badge: 'Archify',
    note: 'MAPPED LIVE · MIT',
    asset: 'img:archify_map_hero.png',
    art: 'img:archify_map_hero.png',
  },
  scenes: c.S,
};

c.emit('topics/archify-live-map/long.json', spec);
