// COMPONENT CATALOG — the single source of truth the critic reads.
// For every scene type: what it's for, how it lays out per aspect, how colour /
// fonts / motion behave, what assets it needs and from WHERE, and which scenes
// sit well before/after it. Also: the full 81-template (RVE) coverage matrix so
// nothing from the reference library goes unconsidered.

export const ASSET_SOURCES = {
  'lucide:': 'Lucide icon set — ISC licensed, bundled via lucide-react. Free, no attribution.',
  'si:': 'simple-icons brand mark — official logo, NOMINATIVE use only (identify, never imply endorsement).',
  'img:': 'Local file in public/assets/ — MUST be your own capture or CC0/public-domain. Linter blocks if missing.',
};

// Per-type spec. aspect.wide / aspect.vertical describe the layout in each
// orientation (the critic reports the difference). assets.slots lists the data
// paths that accept an icon/logo/image and whether one is required.
export const CATALOG = {
  HOOK: {
    category: 'structure',
    purpose: 'First 8s. State the stake so the viewer cannot scroll.',
    useWhen: 'Always scene 1.',
    aspect: {wide: 'hero glyph + huge centered headline (110px)', vertical: 'larger glyph (200px) + 96px headline, same center stack'},
    color: 'headline = theme text; subtext = accent3. Dark & light both via theme tokens; glow only if theme.style.glow>0.',
    fonts: 'display (headline), accent/Caveat (subtext aside).',
    motion: 'hero springPop @heroAtWord; headline springPop @headlineAtWord; subtext fadeUp.',
    layout: 'centered column, 80px padding. Nothing near edges.',
    assets: {slots: [{path: 'heroAsset', kind: 'icon', required: false}], note: 'usually a lucide: glyph naming the topic.'},
    goodAfter: [], goodBefore: ['TITLE_CARD', 'CHAT_MOCKUP', 'SPLIT_PATHS', 'STAT_CALLOUT'],
  },
  TITLE_CARD: {
    category: 'structure',
    purpose: 'Name the topic for 2-3s after the hook.',
    useWhen: 'Right after HOOK.',
    aspect: {wide: 'centered title + subtitle', vertical: 'same, scaled'},
    color: 'title = text, subtitle = muted. Theme-driven; both modes fine.',
    fonts: 'display title, body/mono subtitle.',
    motion: 'fadeUp / springPop entrance.',
    layout: 'dead-center; safe both aspects.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['HOOK'], goodBefore: ['CONCEPT_DIAGRAM', 'STEP_FLOW', 'LIST_BUILD', 'CHAT_MOCKUP'],
  },
  CONCEPT_DIAGRAM: {
    category: 'diagram',
    purpose: 'How-it-works chain of 2-4 nodes + edges.',
    useWhen: 'Explain a mechanism/flow.',
    aspect: {wide: 'horizontal node row with dotted connectors', vertical: 'nodes stack; connectors vertical'},
    color: 'nodes neutral panels; edges accent. Both modes via tokens.',
    fonts: 'body labels, mono kickers.',
    motion: 'nodes springPop @atWord; edges DottedConnector draw.',
    layout: 'centered; watch node label width on vertical.',
    assets: {slots: [{path: 'nodes[].asset', kind: 'icon', required: false}], note: 'lucide: per node.'},
    goodAfter: ['TITLE_CARD'], goodBefore: ['STAT_PANELS', 'SPLIT_PATHS', 'CODE_WINDOW'],
  },
  DIAGRAM: {
    category: 'diagram',
    purpose: 'System-architect diagramming: flow / sequence / block / tree / hub.',
    useWhen: 'sequence=protocols/handshakes; tree=hierarchy/cert-chain/DNS; block=architecture; hub=one-to-many; flow=pipeline.',
    aspect: {wide: 'coordinate layout, dotted connectors', vertical: 'flow auto-stacks; other layouts reflow'},
    color: 'node panels neutral; connectors + accents via tokens. Both modes.',
    fonts: 'body node labels, mono message labels.',
    motion: 'nodes entrance @atWord; dotted edges draw-on + marching ants; arrowheads pop.',
    layout: 'centered canvas with side/top/bottom margins; heading top; source bottom.',
    assets: {slots: [{path: 'diagram.nodes[].asset', kind: 'icon', required: false}], note: 'lucide: per node.'},
    goodAfter: ['CHAPTER', 'TITLE_CARD'], goodBefore: ['STAT_PANELS', 'CODE_WINDOW', 'QUOTE_SPOTLIGHT'],
  },
  KINETIC_TEXT: {
    category: 'text',
    purpose: 'A single line as a dynamic moment: 8 FX (typewriter/glitch/split/char-spin/highlight/bounce/wave/outline).',
    useWhen: 'A punch, breather, statement, or intro title — anywhere static text would feel flat.',
    aspect: {wide: 'big centered line, fitText', vertical: 'smaller cap, wraps'},
    color: 'text = theme; one accent phrase via color. Both modes.',
    fonts: 'display (or mono for typewriter/glitch).',
    motion: 'per-FX, deterministic.',
    layout: 'dead-center, generous padding.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['CHAPTER', 'STAT_CALLOUT'], goodBefore: ['CONCEPT_DIAGRAM', 'DIAGRAM', 'LIST_BUILD'],
  },
  PHOTO: {
    category: 'media',
    purpose: 'Full-bleed image with a deterministic Ken Burns move + caption.',
    useWhen: 'Set a scene, show a real place/thing, or a breather with an image.',
    aspect: {wide: 'cover-fill 16:9', vertical: 'cover-fill 9:16'},
    color: 'scrim for legibility; accent kicker chip. Both modes.',
    fonts: 'display caption, mono kicker.',
    motion: 'slow zoom/pan (frame-driven); caption fade-up.',
    layout: 'text bottom-left over scrim; nothing clipped.',
    assets: {slots: [{path: 'photo.asset', kind: 'image', required: true}], note: 'img: from public/assets (fetch-asset.mjs records provenance).'},
    goodAfter: ['CHAPTER', 'HOOK'], goodBefore: ['STAT_CALLOUT', 'DIAGRAM'],
  },
  SOUND_WAVE: {
    category: 'media',
    purpose: 'Animated audio waveform bars.',
    useWhen: 'Audio / podcast / "listen" beats.',
    aspect: {wide: '44 bars', vertical: '28 bars'},
    color: 'accent + purple bars with glow. Both modes.',
    fonts: 'mono label.',
    motion: 'seeded sine bars, staggered reveal.',
    layout: 'centered; optional headline top.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['TITLE_CARD'], goodBefore: ['STAT_CALLOUT', 'QUOTE_SPOTLIGHT'],
  },
  REVEAL: {
    category: 'structure',
    purpose: 'Spotlight iris opens to reveal a statement (kicker + big line + sub).',
    useWhen: 'A cinematic "here is the point" moment or act reveal.',
    aspect: {wide: 'centered statement', vertical: 'smaller cap'},
    color: 'gradient reveal + accent bars/glow. Both modes.',
    fonts: 'display statement, mono kicker.',
    motion: 'clip-circle grow + glow ring + text fade-up (deterministic).',
    layout: 'dead-center.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['CHAPTER', 'STAT_CALLOUT'], goodBefore: ['RECAP', 'OUTRO_CTA'],
  },
  LOGO_REVEAL: {
    category: 'structure',
    purpose: 'Branded mark strokes on + icon + wordmark.',
    useWhen: 'Intro sting or outro branding.',
    aspect: {wide: 'centered mark', vertical: 'same, scaled'},
    color: 'accent gradient mark. Both modes.',
    fonts: 'display wordmark, mono tagline.',
    motion: 'SVG stroke-draw + fill/icon/name fade (deterministic).',
    layout: 'dead-center.',
    assets: {slots: [{path: 'logo.asset', kind: 'icon', required: false}], note: 'lucide:/si: mark.'},
    goodAfter: ['HOOK'], goodBefore: ['TITLE_CARD', 'OUTRO_CTA'],
  },
  CAROUSEL: {
    category: 'structure',
    purpose: 'A 3D rotating ring of cards — "the toolkit / the ecosystem / the options".',
    useWhen: 'Show a set of 3-6 related components with depth and motion.',
    aspect: {wide: 'wide horizontal ring, front card dominant', vertical: 'bigger cards, tighter radius, nudged below headline'},
    color: 'card panels neutral; per-item accent border/glow. Both modes.',
    fonts: 'display labels, mono subs.',
    motion: 'continuous slow spin; depth = scale + opacity + z-index (deterministic).',
    layout: 'centered ring; headline top; source bottom.',
    assets: {slots: [{path: 'carousel.items[].asset', kind: 'icon', required: false}], note: 'lucide: per card.'},
    goodAfter: ['CHAPTER', 'TITLE_CARD'], goodBefore: ['RECAP', 'STAT_PANELS'],
  },
  CREDITS_ROLL: {
    category: 'structure',
    purpose: 'Movie-style scrolling role/name rows — a stylish sign-off.',
    useWhen: 'Recap the cast of concepts, or a cinematic outro before the CTA.',
    aspect: {wide: 'centered column scroll', vertical: 'same, scaled'},
    color: 'title = text; role = accent mono; name = text. Both modes.',
    fonts: 'display title/names, mono roles.',
    motion: 'rows scroll up; top/bottom fade gradient (deterministic).',
    layout: 'dead-center column; fades at edges.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['REVEAL', 'RECAP'], goodBefore: ['OUTRO_CTA'],
  },
  SUBSCRIBE_REMINDER: {
    category: 'structure',
    purpose: 'Compact mid-roll subscribe nudge — shaking bell + SUBSCRIBE button + one-line ask.',
    useWhen: 'A light reminder partway through (NOT the branded end-card — that is CHANNEL_CARD).',
    aspect: {wide: 'centered stack', vertical: 'larger bell + button, same stack'},
    color: 'accent bell + button; text = theme. Both modes.',
    fonts: 'display text, mono handle.',
    motion: 'bell springs in then rings (decaying wobble); button + copy fade up.',
    layout: 'dead-center; safe both aspects.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['STAT_CALLOUT', 'REVEAL', 'BAR_COMPARE'], goodBefore: ['CHAPTER', 'DIAGRAM'],
  },
  LIST_BUILD: {
    category: 'list', purpose: '"N things this changes" — icon list, two-tier rows.',
    useWhen: 'Enumerate 3-5 points.',
    aspect: {wide: 'rows ~72% width', vertical: 'rows ~94% width'},
    color: 'icons cycle semantic; text = theme text/muted. Both modes fine.',
    fonts: 'body bold lead + muted detail.',
    motion: 'rows stackIn @atWord.',
    layout: 'centered column; two-tier bold+detail.',
    assets: {slots: [{path: 'items[].icon', kind: 'icon', required: false}], note: 'lucide: per row.'},
    goodAfter: ['TITLE_CARD', 'STEP_FLOW'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  STAT_CALLOUT: {
    category: 'data', purpose: 'ONE hero number counting up (+ optional logo strip).',
    useWhen: 'A single number is the story.',
    aspect: {wide: '240px number', vertical: '200px number; logos wrap'},
    color: 'number = accent2; label = text; logos mono-white on dark.',
    fonts: 'mono tabular number, body label.',
    motion: 'counterValue count-up; logos stackIn.',
    layout: 'centered; number auto-compacts (compactNumber) so it never overflows.',
    assets: {slots: [{path: 'logos[]', kind: 'logo', required: false}], note: 'si: brand marks (proof-by-recognition).'},
    goodAfter: ['SPLIT_PATHS', 'BAR_COMPARE'], goodBefore: ['RECAP', 'QUOTE_SPOTLIGHT'],
  },
  STEP_FLOW: {
    category: 'diagram', purpose: 'Pipeline of 3-5 named stages.',
    useWhen: 'Sequential process (RAG, CI/CD).',
    aspect: {wide: 'horizontal step cards + connectors', vertical: 'vertical step stack'},
    color: 'per-step semantic; success step = green. Both modes fine.',
    fonts: 'mono titles, body subs, mono kickers.',
    motion: 'cards springPop @atWord; connectors draw.',
    layout: 'centered; caption pill below.',
    assets: {slots: [], note: 'none (tokens as text).'},
    goodAfter: ['TITLE_CARD', 'CONCEPT_DIAGRAM'], goodBefore: ['STAT_PANELS', 'CODE_WINDOW', 'BAR_COMPARE'],
  },
  PIPELINE: {
    category: 'diagram', purpose: 'A staged flow with a token advancing; the engine behind the CI/boot/serverless/journey variants.',
    useWhen: 'Any staged flow. variant:"ci"=CI/CD run (status+ms+reason); "boot"=init sequence (ms chips); "serverless"=event chain (badges+travelling token); "journey"=E2E user journey (system badge + pass/fail).',
    aspect: {wide: 'horizontal cards + arrows', vertical: 'vertical card stack'},
    color: 'per-stage semantic; status colours green=pass/running, red=fail, orange=pending.',
    fonts: 'display labels, body subs, mono status/ms/badge chips.',
    motion: 'cards springPop staggered; flow token dwells (flow/serverless); status cards resolve left→right; failed card glows red.',
    layout: 'centered; status cards are taller to fit chips + a one-line reason.',
    assets: {slots: [{path: 'stages[].asset', kind: 'icon', required: false}], note: 'lucide: per stage.'},
    variants: {ci: 'CI_BOARD', boot: 'BOOT_SEQUENCE', serverless: 'SERVERLESS_FLOW', journey: 'E2E_JOURNEY'},
    goodAfter: ['TITLE_CARD', 'DIAGRAM'], goodBefore: ['STAT_PANELS', 'CODE_WINDOW'],
  },
  CHAT_MOCKUP: {
    category: 'mockup', purpose: 'Show a conversation/failure happening.',
    useWhen: 'AI answer, support thread, DM.',
    aspect: {wide: 'chat panel + side card', vertical: 'chat stacks; side card below'},
    color: 'user vs agent bubbles; error = red. Both modes fine.',
    fonts: 'body messages, mono side-card lines.',
    motion: 'messages stackIn @atWord.',
    layout: 'middle-band; source footer.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['HOOK', 'TITLE_CARD'], goodBefore: ['STEP_FLOW', 'SPLIT_PATHS'],
  },
  STAT_PANELS: {
    category: 'data', purpose: 'Myth-bust / tradeoff: 2-3 metrics + verdict.',
    useWhen: 'Compare metrics with a conclusion.',
    aspect: {wide: 'grid visual + stat column side by side', vertical: 'grid on top, stats below'},
    color: 'per-stat semantic; verdict green. Both modes fine.',
    fonts: 'mono values, body notes.',
    motion: 'stats stackIn; verdict fadeUp.',
    layout: 'centered; source footer.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['STEP_FLOW', 'LIST_BUILD'], goodBefore: ['QUOTE_SPOTLIGHT', 'RECAP'],
  },
  QUOTE_SPOTLIGHT: {
    category: 'editorial', purpose: 'An insight/quote anchors the argument.',
    useWhen: 'A person or principle carries weight.',
    aspect: {wide: 'quote + person card side', vertical: 'quote top, person below'},
    color: 'accent phrase in quote; person role = mono kicker.',
    fonts: 'display quote, mono role.',
    motion: 'fadeUp; transformation pill.',
    layout: 'centered; source footer.',
    assets: {slots: [{path: 'person.asset', kind: 'image', required: false}], note: 'img: a REAL photo you have rights to (own/CC0). Never a random web headshot.'},
    goodAfter: ['STAT_PANELS'], goodBefore: ['RECAP', 'OUTRO_CTA'],
  },
  SPLIT_PATHS: {
    category: 'diagram', purpose: 'One system, two behaviours (router, hit/miss).',
    useWhen: 'Branching / either-or.',
    aspect: {wide: 'left/right cards flank a center node', vertical: 'center on top, cards stack'},
    color: 'each branch semantic; center purple. Both modes fine.',
    fonts: 'display titles, mono badges/lines.',
    motion: 'center springPop; cards stackIn.',
    layout: 'centered; badge budget smaller (in-card).',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['CHAT_MOCKUP', 'TITLE_CARD'], goodBefore: ['BAR_COMPARE', 'STAT_CALLOUT'],
  },
  BAR_COMPARE: {
    category: 'chart', purpose: 'Benchmarks/rankings: 2-4 horizontal bars.',
    useWhen: 'Compare magnitudes with values.',
    aspect: {wide: 'wide bars', vertical: 'shorter bars, same rows'},
    color: 'per-bar semantic; leader can stay neutral. Both modes fine.',
    fonts: 'body labels, mono values.',
    motion: 'bars grow @atWord.',
    layout: 'centered; label<=16, display<=8.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['STEP_FLOW', 'SPLIT_PATHS'], goodBefore: ['STAT_CALLOUT', 'RECAP'],
  },
  CHANNEL_CARD: {
    category: 'branding', purpose: 'Designed subscribe moment.',
    useWhen: 'Near the end, once.',
    aspect: {wide: 'logo ring + name row', vertical: 'same, centered higher (UI-safe)'},
    color: 'brand accents; logo mono on dark.',
    fonts: 'display name, mono handle.',
    motion: 'glow ring pulse; chip pop.',
    layout: 'centered, end-screen safe.',
    assets: {slots: [{path: 'brand.logo', kind: 'image', required: false}], note: 'img:channel_logo.png — your own mark.'},
    goodAfter: ['RECAP'], goodBefore: ['OUTRO_CTA'],
  },
  RECAP: {
    category: 'structure', purpose: 'Close the hook loop: 3-4 points.',
    useWhen: 'Penultimate.',
    aspect: {wide: 'point list', vertical: 'same, wider rows'},
    color: 'neutral; theme text. Both modes fine.',
    fonts: 'body points.',
    motion: 'points stackIn @atWord.',
    layout: 'centered column.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['STAT_PANELS', 'BAR_COMPARE'], goodBefore: ['OUTRO_CTA', 'CHANNEL_CARD'],
  },
  OUTRO_CTA: {
    category: 'structure', purpose: 'Final <=5s, one CTA, centered.',
    useWhen: 'Last scene.',
    aspect: {wide: 'centered message + sub', vertical: 'centered, end-screen safe'},
    color: 'message = text; accent on CTA. Both modes fine.',
    fonts: 'display message, body sub.',
    motion: 'fadeUp.',
    layout: 'dead-center, corners clear.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['RECAP', 'CHANNEL_CARD'], goodBefore: [],
  },
  // ---- data-viz (WS-2) ----
  LINE_CHART: {
    category: 'chart', purpose: 'Trends over time, 1-3 series (+ area).',
    useWhen: 'Something changes across time.',
    aspect: {wide: '1440x600 plot + legend', vertical: '940x820 plot, legend below'},
    color: 'series cycle blue/purple/green; gridlines = panelBorder; both modes via useSem.',
    fonts: 'mono axis labels, mono legend.',
    motion: 'line draws L→R (clip); points reveal on sweep.',
    layout: 'headline top, plot center, source bottom.',
    assets: {slots: [], note: 'none — pure SVG.'},
    goodAfter: ['TITLE_CARD', 'STEP_FLOW'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  DONUT: {
    category: 'chart', purpose: 'Parts of a whole (2-6 segments). variant:pie = solid wedges.',
    useWhen: 'Composition/share of total.',
    aspect: {wide: 'donut + legend side by side', vertical: 'donut on top, legend below'},
    color: 'segments cycle semantic; center metric = text. Both modes.',
    fonts: 'mono center value, body legend.',
    motion: 'segments sweep clockwise in sequence @atWord.',
    layout: 'centered; legend right/below.',
    assets: {slots: [], note: 'none — pure SVG.'},
    goodAfter: ['STAT_CALLOUT'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  PROGRESS: {
    category: 'chart', purpose: 'Rings or bars filling to targets.',
    useWhen: 'Completion / coverage / scores.',
    aspect: {wide: 'up to 4 rings in a row', vertical: '2 per row, wraps'},
    color: 'per-item semantic; track = alpha of same hue. Both modes.',
    fonts: 'mono value in ring, body label.',
    motion: 'each ring/bar fills @ its atWord.',
    layout: 'centered; wraps on vertical.',
    assets: {slots: [], note: 'none — pure SVG.'},
    goodAfter: ['LIST_BUILD', 'STEP_FLOW'], goodBefore: ['RECAP', 'OUTRO_CTA'],
  },
  TIMELINE: {
    category: 'chart', purpose: 'Ordered dated milestones (history/roadmap).',
    useWhen: 'A sequence of dates matters.',
    aspect: {wide: 'HORIZONTAL spine, nodes alternate above/below', vertical: 'VERTICAL spine, nodes down the left'},
    color: 'per-node semantic; spine = panelBorder. Both modes.',
    fonts: 'mono dates, display titles.',
    motion: 'nodes springPop @atWord.',
    layout: 'centered; biggest wide↔vertical layout change in the set.',
    assets: {slots: [], note: 'none — pure SVG.'},
    goodAfter: ['TITLE_CARD'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  QUADRANT: {
    category: 'chart', purpose: '2x2 positioning map / scatter.',
    useWhen: 'Landscape of options on two axes.',
    aspect: {wide: '720px square, centered', vertical: '900px square fills width'},
    color: 'points cycle semantic; axes = panelBorder dashed. Both modes.',
    fonts: 'mono axis captions, body point labels.',
    motion: 'points springPop @atWord.',
    layout: 'centered square; captions on all 4 sides (mind rotation on left/right).',
    assets: {slots: [], note: 'none — pure SVG.'},
    goodAfter: ['LIST_BUILD'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  CODE_WINDOW: {
    category: 'mockup', purpose: 'Editor/terminal that types code then shows output.',
    useWhen: 'Technical topic: show real code + result.',
    aspect: {wide: '1180px window', vertical: '960px window, same chrome'},
    color: 'syntax from theme: strings=green, keywords=purple, numbers=orange, comments=muted; output prompt=green. Both modes read theme tokens.',
    fonts: 'mono throughout.',
    motion: 'line-by-line typewriter + blinking caret; output panel fades after typing.',
    layout: 'centered window; no headline (window IS the focus); source footer optional.',
    assets: {slots: [], note: 'none — code is text.'},
    goodAfter: ['STEP_FLOW', 'CONCEPT_DIAGRAM'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  // ---- widgets (media/intro/content wave) ----
  LOWER_THIRD: {
    category: 'branding', purpose: 'Broadcast name/role bar — introduce a person, tool, or entity.',
    useWhen: 'Name who/what is on screen.',
    aspect: {wide: 'card slides in bottom-left', vertical: 'card centered-lower'},
    color: 'accent left-border = semantic; text = theme. Both modes fine.',
    fonts: 'display title, mono subtitle, mono kicker.',
    motion: 'slideIn from left @atWord.',
    layout: 'lower third; stays clear of center content.',
    assets: {slots: [{path: 'lowerThird.asset', kind: 'icon', required: false}], note: 'lucide: glyph or si: logo of the entity; img: only if you own it.'},
    goodAfter: ['HOOK', 'TITLE_CARD'], goodBefore: ['CHAT_MOCKUP', 'STEP_FLOW', 'QUOTE_SPOTLIGHT'],
  },
  CHAPTER: {
    category: 'structure', purpose: 'Section divider: big number + title + rules.',
    useWhen: 'Break a longer video into parts.',
    aspect: {wide: '300px number centered', vertical: '260px number, same stack'},
    color: 'accent rules + kicker semantic; number = text. Both modes.',
    fonts: 'display number/title, mono kicker.',
    motion: 'number springPop; rules extend from center; title fadeUp.',
    layout: 'dead-center; safe both aspects.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['TITLE_CARD', 'RECAP'], goodBefore: ['STEP_FLOW', 'LIST_BUILD', 'CONCEPT_DIAGRAM'],
  },
  NOTIFICATION: {
    category: 'mockup', purpose: 'Stack of toast notifications popping in (reactions, alerts).',
    useWhen: 'Show reactions/alerts/DMs arriving.',
    aspect: {wide: 'toasts ~54% width', vertical: 'toasts ~88% width'},
    color: 'per-toast semantic accent on app name + icon tile. Both modes.',
    fonts: 'mono app name, body title/body.',
    motion: 'each toast bubblePop @ its atWord.',
    layout: 'centered column; optional headline top.',
    assets: {slots: [{path: 'notifications[].icon', kind: 'icon', required: false}], note: 'lucide: or si: per toast (defaults to lucide:bell).'},
    goodAfter: ['HOOK', 'STAT_CALLOUT'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  COUNTDOWN: {
    category: 'structure', purpose: 'Number ticking from N down to GO.',
    useWhen: 'Build tension to a launch/reveal.',
    aspect: {wide: '380px digits', vertical: '320px digits'},
    color: 'digits = accent; GO = green (semantic). Both modes.',
    fonts: 'display tabular digits, mono label.',
    motion: 'each tick springPop; glow if theme.glow>0.',
    layout: 'dead-center.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['HOOK', 'TITLE_CARD'], goodBefore: ['STAT_CALLOUT', 'CONCEPT_DIAGRAM'],
  },
  FLIP_CARD: {
    category: 'editorial', purpose: 'Card flips 180° to reveal its back (myth→fact, before→after).',
    useWhen: 'Overturn a claim / reveal the twist.',
    aspect: {wide: '1080x520 card', vertical: '900x620 card'},
    color: 'front usually red (myth), back green (fact) — semantic. Both modes.',
    fonts: 'display face text, mono face label.',
    motion: '3D rotateY flip @atWord (easeInOutCubic); backface-hidden faces.',
    layout: 'centered; optional headline top.',
    assets: {slots: [], note: 'none.'},
    goodAfter: ['CHAT_MOCKUP', 'STAT_PANELS'], goodBefore: ['STAT_CALLOUT', 'RECAP'],
  },
  GALLERY: {
    category: 'media', purpose: 'A grid of image/logo tiles revealing in a stagger.',
    useWhen: 'Show a set of tools/logos/screenshots.',
    aspect: {wide: 'tiles wrap ~80% width', vertical: 'tiles wrap ~92% width'},
    color: 'tiles = asset native (si: brand colour / lucide: theme). Both modes.',
    fonts: 'mono tile labels.',
    motion: 'each tile springPop (staggered or @atWord).',
    layout: 'centered grid; headline top, source bottom.',
    assets: {slots: [{path: 'gallery.tiles[].asset', kind: 'image', required: true}], note: 'si: logos or lucide: icons need no files; img: must be your own/CC0.'},
    goodAfter: ['LIST_BUILD', 'TITLE_CARD'], goodBefore: ['STAT_CALLOUT', 'RECAP'],
  },
  COMPARISON_SLIDER: {
    category: 'media', purpose: 'Before/after box; divider wipes to reveal after.',
    useWhen: 'Show a transformation (old vs new UI, before/after).',
    aspect: {wide: '1280x620 box', vertical: '940x900 box'},
    color: 'before = red-ish, after = green-ish (semantic). Both modes.',
    fonts: 'display side labels, mono captions/kickers.',
    motion: 'divider wipes L→R (drawProgress); after clip-reveals.',
    layout: 'centered framed box; corner BEFORE/AFTER kickers.',
    assets: {slots: [{path: 'comparison.before.asset', kind: 'image', required: false}, {path: 'comparison.after.asset', kind: 'image', required: false}], note: 'img: your own screenshots ideally; si:/lucide: work as stand-ins.'},
    goodAfter: ['CHAT_MOCKUP', 'STEP_FLOW'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  PHOTO_STACK: {
    category: 'media', purpose: 'Overlapping cards that fan out as they drop in.',
    useWhen: 'A pile of evidence/screenshots/receipts.',
    aspect: {wide: '460x540 cards', vertical: '520x620 cards'},
    color: 'per-card semantic border. Both modes.',
    fonts: 'display card labels.',
    motion: 'each card springPop @atWord with rotation offset.',
    layout: 'centered fan; headline top.',
    assets: {slots: [{path: 'photoStack.cards[].asset', kind: 'image', required: false}], note: 'img:/si:/lucide: per card.'},
    goodAfter: ['HOOK', 'STAT_CALLOUT'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
  IMAGE_SCENE: {
    category: 'media', purpose: 'A single framed image — tilted polaroid or picture-in-picture.',
    useWhen: 'Feature ONE screenshot/photo (a result, a scene, a demo).',
    aspect: {wide: 'polaroid ~520w / pip 1240x640', vertical: 'polaroid ~560w / pip 940x700'},
    color: 'polaroid = paper white (deliberate, off-theme); pip = theme panel + green inset. Both modes.',
    fonts: 'accent (handwritten) caption for polaroid; mono label for pip.',
    motion: 'polaroid bounceIn + tilt; pip springPop, inset pops after.',
    layout: 'centered; headline top, source bottom.',
    assets: {slots: [{path: 'image.asset', kind: 'image', required: true}, {path: 'image.pip.asset', kind: 'image', required: false}], note: 'img: your own screenshot/photo ideally; si:/lucide: work as stand-ins.'},
    goodAfter: ['HOOK', 'TITLE_CARD'], goodBefore: ['STAT_PANELS', 'RECAP'],
  },
};

// ---------------------------------------------------------------------------
// 81-TEMPLATE (RVE) COVERAGE MATRIX — every reference template, considered.
// status: core=already a scene | added=new scene/primitive | motion=available as
// a motion helper | planned=approved-next | deferred=out of channel grammar (reason).
// ---------------------------------------------------------------------------
export const RVE_81 = {
  'Charts & Data': {
    'bar-chart': {status: 'core', via: 'BAR_COMPARE'},
    'line-chart': {status: 'added', via: 'LINE_CHART'},
    'pie-chart': {status: 'added', via: 'DONUT variant:pie (fat-stroke wedges)'},
    'donut-chart': {status: 'added', via: 'DONUT'},
    'area-chart': {status: 'added', via: 'LINE_CHART area:true'},
    'progress-bars': {status: 'added', via: 'PROGRESS variant:bar'},
    'stat-counter': {status: 'core', via: 'STAT_CALLOUT'},
    'comparison-chart': {status: 'core', via: 'STAT_PANELS / BAR_COMPARE'},
    'circular-progress': {status: 'added', via: 'PROGRESS variant:ring'},
  },
  'Text': {
    'animated-text': {status: 'motion', via: 'revealAt / charSpin (per-char spin, ported)'},
    'bounce-text': {status: 'motion', via: 'bounceIn'},
    'bubble-pop-text': {status: 'motion', via: 'bubblePop'},
    'floating-text-chip': {status: 'motion', via: 'floaty'},
    'glitch-text': {status: 'motion', via: 'glitchText (+ cyberpunk GlitchHeadline)'},
    'popping-scale-text': {status: 'motion', via: 'scalePop / outlineText (4-way outline, ported)'},
    'pulsing-text': {status: 'motion', via: 'pulse'},
    'slide-text': {status: 'motion', via: 'slideIn'},
    'typewriter-subtitle': {status: 'motion', via: 'typewriter + caretVisible'},
  },
  'Content Animation': {
    'animated-list': {status: 'core', via: 'LIST_BUILD'},
    'card-flip': {status: 'added', via: 'FLIP_CARD'},
    'countdown-timer': {status: 'added', via: 'COUNTDOWN'},
    'notification-pop': {status: 'added', via: 'NOTIFICATION'},
    'particle-explosion': {status: 'motion', via: 'particle (burst overlay)'},
    'progress-steps': {status: 'core', via: 'STEP_FLOW / PROGRESS'},
    'rotating-carousel': {status: 'deferred', reason: '3D carousel rarely reads in an infographic explainer; use LIST_BUILD/GALLERY.'},
    'sound-wave': {status: 'motion', via: 'waveBar (visualiser)'},
    'text-highlight': {status: 'motion', via: 'highlightAt'},
  },
  'Background': {
    'bokeh-circles': {status: 'added', via: 'brand.background:bokeh'},
    'geometric-patterns': {status: 'added', via: 'brand.background:geo (+ pack Chromes)'},
    'gradient-shift': {status: 'added', via: 'brand.background:gradient'},
    'grid-pulse': {status: 'added', via: 'brand.background:grid-pulse'},
    'liquid-wave': {status: 'added', via: 'brand.background:wave'},
    'matrix-rain': {status: 'core', via: 'terminalcli/cyberpunk Chrome (rain-like)'},
    'noise-grain': {status: 'motion', via: 'grainOpacity (+ several pack Chromes)'},
    'pixel-transition': {status: 'added', via: 'scene.transition:pixel'},
    'starfield': {status: 'added', via: 'brand.background:starfield'},
  },
  'Cinematic': {
    'camera-shake': {status: 'motion', via: 'shake (two-frequency, ported)'},
    'film-burn': {status: 'deferred', reason: 'warm light-leak fights semantic colour system; use vignettePulse.'},
    'ken-burns': {status: 'motion', via: 'kenBurns'},
    'letterbox-reveal': {status: 'motion', via: 'letterbox'},
    'parallax-pan': {status: 'motion', via: 'parallax'},
    'spotlight-reveal': {status: 'motion', via: 'spotlightReveal'},
    'vignette-pulse': {status: 'motion', via: 'vignettePulse'},
    'whip-pan': {status: 'motion', via: 'whipPan (scaleX stretch, ported)'},
    'zoom-pulse': {status: 'motion', via: 'zoomPulse'},
  },
  'Transition': {
    'blinds': {status: 'added', via: 'scene.transition:blinds'},
    'clock-wipe': {status: 'added', via: 'scene.transition:clock'},
    'cross-dissolve': {status: 'core', via: 'SceneTransition fade (default)'},
    'fade-through-black': {status: 'added', via: 'scene.transition:dip'},
    'iris': {status: 'added', via: 'scene.transition:iris'},
    'morph': {status: 'added', via: 'scene.transition:morph'},
    'push': {status: 'added', via: 'scene.transition:push'},
    'slide-wipe': {status: 'added', via: 'scene.transition:wipe'},
    'zoom-through': {status: 'added', via: 'scene.transition:zoom'},
  },
  'Logo & Branding': {
    'logo-blur-reveal': {status: 'motion', via: 'blurIn'},
    'logo-bounce-drop': {status: 'motion', via: 'squashDrop (squash-and-stretch, ported)'},
    'logo-fade-reveal': {status: 'motion', via: 'fadeUp'},
    'logo-glitch-reveal': {status: 'motion', via: 'glitchText'},
    'logo-scale-rotate': {status: 'motion', via: 'scaleRotate'},
    'logo-spin-reveal': {status: 'deferred', reason: '3D spin off-brand for explainers.'},
    'logo-split-reveal': {status: 'motion', via: 'splitOffset (mode:out)'},
    'logo-stroke-draw': {status: 'motion', via: 'pathDraw'},
    'logo-typewriter': {status: 'core', via: 'CHANNEL_CARD + typewriter'},
  },
  'Intro & Outro': {
    'chapter-title': {status: 'added', via: 'CHAPTER'},
    'cinematic-title-intro': {status: 'core', via: 'TITLE_CARD'},
    'countdown-intro': {status: 'added', via: 'COUNTDOWN'},
    'credits-roll': {status: 'deferred', reason: 'not used in short explainers.'},
    'end-card': {status: 'core', via: 'OUTRO_CTA'},
    'lower-third': {status: 'added', via: 'LOWER_THIRD'},
    'quote-card': {status: 'core', via: 'QUOTE_SPOTLIGHT'},
    'subscribe-reminder': {status: 'core', via: 'CHANNEL_CARD'},
    'title-split': {status: 'motion', via: 'splitOffset (mode:in) on TITLE_CARD'},
  },
  'Image & Media': {
    'gallery-grid': {status: 'added', via: 'GALLERY'},
    'image-carousel': {status: 'deferred', reason: 'carousel weak for stills; use GALLERY.'},
    'image-comparison-slider': {status: 'added', via: 'COMPARISON_SLIDER'},
    'image-zoom-reveal': {status: 'motion', via: 'kenBurns / spotlightReveal'},
    'masonry-gallery': {status: 'added', via: 'GALLERY (wrap layout)'},
    'photo-stack': {status: 'added', via: 'PHOTO_STACK'},
    'picture-in-picture': {status: 'added', via: 'IMAGE_SCENE variant:pip'},
    'polaroid-frame': {status: 'added', via: 'IMAGE_SCENE variant:polaroid'},
    'split-screen': {status: 'core', via: 'SPLIT_PATHS (concept) / GALLERY (media)'},
  },
};

export const classifyAsset = (s) => {
  if (typeof s !== 'string') return null;
  for (const p of Object.keys(ASSET_SOURCES)) if (s.startsWith(p)) return {prefix: p, name: s.slice(p.length), source: ASSET_SOURCES[p]};
  return null;
};

export const rveSummary = () => {
  const counts = {};
  let total = 0;
  for (const cat of Object.values(RVE_81)) {
    for (const item of Object.values(cat)) {
      counts[item.status] = (counts[item.status] ?? 0) + 1;
      total++;
    }
  }
  return {total, counts};
};
