#!/usr/bin/env node
// PHASE A — MATRIX CONTRACT GENERATOR.
// Derives audit/matrix.md from audit/census.json (NEVER a hand-list). One row per
// (type × variant). Columns: MIN | MAX | MIX props × {16:9, 9:16} × {material,
// neobrutalism, + a rotating third pack per family}. Every cell starts UNVIEWED.
// Re-running REGENERATES the skeleton but PRESERVES any verdicts already recorded
// in the existing matrix.md (so viewing progress is never lost).
import fs from 'node:fs';
import path from 'node:path';
import {FAMILIES, THIRD, famOf} from './families.mjs';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const census = JSON.parse(read('audit/census.json'));

// third rotating pack — families.mjs THIRD covers built families; the new Phase-B
// families + misc get their own so all packs earn coverage across the program.
const THIRD_ALL = {...THIRD, 'L · media-image': 'academia', 'M · charts-new': 'newsprint', 'N · icon-logo': 'flatdesign', 'O · topic-general': 'organic'};

// ── build rows: one per (type × variant) ─────────────────────────────────
const rowsByFam = {};
for (const r of census.rows) {
  const fam = famOf(r.type);
  const subs = r.variants.length ? r.variants.map((v) => `${r.type}:${v}`) : [r.type];
  (rowsByFam[fam] ??= []).push(...subs.map((sub) => ({type: r.type, sub, fam})));
}

// ── preserve existing viewing-log + per-row verdicts if matrix.md exists ──
const prevPath = path.join(root, 'audit/matrix.md');
const prev = fs.existsSync(prevPath) ? fs.readFileSync(prevPath, 'utf8') : '';
// the viewing-log blockquote (all leading `>` lines) is human-maintained — keep it.
const prevLog = prev.split('\n').filter((l) => l.startsWith('>')).join('\n');
// per (sub-type) verdict cells: a data row is `| `sub` | c1 | … | c6 |` (exactly 6 cells).
const prevRows = new Map();
for (const m of prev.matchAll(/^\| `([^`]+)` \| (.+) \|\s*$/gm)) {
  const cells = m[2].split('|').map((s) => s.trim());
  if (cells.length === 6) prevRows.set(m[1].trim(), cells);
}

const PACKS = (fam) => ['material', 'neobrutalism', THIRD_ALL[fam] || 'monochrome'];
const PROPS = ['MIN', 'MAX', 'MIX'];
const ASPECTS = ['16:9', '9:16'];

let out = `# audit/matrix.md — FULL VISUAL MATRIX (Program 3, Phase A)
${prevLog ? '\n' + prevLog + '\n' : ''}
Generated by \`scripts/gen-matrix.mjs\` from \`audit/census.json\` — never hand-listed.
One row per (type × variant). Each row's cells = MIN | MAX | MIX props, each rendered
in **16:9** and **9:16**, in **material** + **neobrutalism** + a rotating third pack
(per family). Verdict per cell: \`UNVIEWED\` → \`PASS\` or \`DEFECT-n\`. A cell is a viewed
still at a meaningful frame (entrance settle / emphasis / exit start). Re-running PRESERVES
existing verdicts + the viewing log; new (type×variant) rows enter as UNVIEWED.

Rows: ${census.rows.length} types → ${Object.values(rowsByFam).reduce((a, b) => a + b.length, 0)} sub-type rows.
Cells per row: ${PROPS.length} props × ${ASPECTS.length} aspects × 3 packs = ${PROPS.length * ASPECTS.length * 3}.

`;

let totalCells = 0;
for (const [famName] of [...FAMILIES, ['Z · misc', []]]) {
  const rows = rowsByFam[famName];
  if (!rows || !rows.length) continue;
  const packs = PACKS(famName);
  out += `\n## FAMILY ${famName}  ·  third pack: ${packs[2]}\n\n`;
  out += `| sub-type | ${PROPS.flatMap((p) => ASPECTS.map((a) => `${p} ${a}`)).join(' | ')} |\n`;
  out += `|${'---|'.repeat(1 + PROPS.length * ASPECTS.length)}\n`;
  for (const row of rows) {
    const cells = prevRows.get(row.sub) ?? PROPS.flatMap(() => ASPECTS.map(() => 'UNVIEWED'));
    totalCells += cells.length * 3; // 3 packs collapsed per printed cell (pack noted in verdict)
    out += `| \`${row.sub}\` | ${cells.join(' | ')} |\n`;
  }
}

out += `\n---\n\n**Total cells (props×aspect×pack): ${totalCells}.** Verdicts + viewing log preserved across re-runs.\n`;
out += `Packs are collapsed per printed cell; a cell flips to PASS only when material+neobrutalism+third are all viewed clean for that (prop,aspect). A defect names the pack: e.g. \`DEFECT-3 (neo 9:16)\`.\n`;

fs.writeFileSync(prevPath, out);
console.log(`wrote audit/matrix.md — ${Object.values(rowsByFam).reduce((a, b) => a + b.length, 0)} rows, ${totalCells} cells`);
