#!/usr/bin/env node
// GEN-TYPES — derive per-type scene typing from the component MANIFEST, so the
// TypeScript surface can narrow a scene's `data` by its `type`. ADDITIVE by
// design: this writes a NEW file (src/sceneTypes.generated.ts) and does NOT touch
// the hand-written SceneData bag — existing components keep compiling. New code
// can opt into `SceneOf<'BITS'>` for compile-time safety. Same one-source story
// as gen-schema.mjs (the manifest) and the same --check gate guard.
//
// Usage:
//   node scripts/gen-types.mjs           → write src/sceneTypes.generated.ts
//   node scripts/gen-types.mjs --check   → verify it is up to date (in the gate)

import fs from 'node:fs';
import {MANIFEST, MANIFEST_TYPES} from './lib/manifest.mjs';

const OUT = 'src/sceneTypes.generated.ts';

// field type `t` → a TypeScript type expression.
const tsType = (t) => {
  switch (t) {
    case 'string':
    case 'asset': return 'string';
    case 'anchor':
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'string[]': return 'string[]';
    case 'number[]': return 'number[]';
    case 'items': return 'Array<Record<string, unknown>>';
    case 'object': return 'Record<string, unknown>';
    default: return 'unknown';
  }
};

const fieldsBlock = (fields, indent) => {
  const lines = [];
  for (const [name, f] of Object.entries(fields ?? {})) {
    const opt = f.req ? '' : '?';
    lines.push(`${indent}${name}${opt}: ${tsType(f.t)};`);
  }
  return lines.join('\n');
};

// one type's `data` shape. data_root → fields directly; data_key → wrapped.
const dataShape = (entry) => {
  const inner = fieldsBlock(entry.fields, '    ');
  if (entry.data_root) return `{\n${inner}\n  }`;
  // data_key: the key is present (it carries the payload) → required.
  return `{\n    ${entry.data_key}: {\n${fieldsBlock(entry.fields, '      ')}\n    };\n  }`;
};

const pascal = (t) => t.split('_').map((p) => p.charAt(0) + p.slice(1).toLowerCase()).join('');

const build = () => {
  const header = `// AUTO-GENERATED by scripts/gen-types.mjs from scripts/lib/manifest.mjs.
// DO NOT EDIT BY HAND. Run \`node scripts/gen-types.mjs\` to regenerate.
// ADDITIVE: opt-in per-type scene typing. The canonical Scene/SceneData in
// ./types.ts are unchanged; use SceneOf<'BITS'> when you want narrowing.

export type SceneTypeName =\n${MANIFEST_TYPES.map((t) => `  | '${t}'`).join('\n')};

// Fields every scene carries regardless of type (mirrors ./types.ts Scene).
export interface SceneCommon<T extends SceneTypeName> {
  id: string;
  type: T;
  narration: string;
  durationFrames?: number;
  timingSource?: string;
  background?: string;
  transition?: string;
  fx?: string;
  pip?: Record<string, unknown>;
  audio?: string;
}
`;

  const arms = MANIFEST_TYPES.map((t) => {
    const name = `${pascal(t)}Scene`;
    return `export type ${name} = SceneCommon<'${t}'> & { data: ${dataShape(MANIFEST[t])} };`;
  }).join('\n\n');

  const mapEntries = MANIFEST_TYPES.map((t) => `  ${t.includes('-') ? `'${t}'` : t}: ${pascal(t)}Scene;`).join('\n');
  const union = MANIFEST_TYPES.map((t) => `${pascal(t)}Scene`).join('\n  | ');

  const footer = `
export interface SceneByType {
${mapEntries}
}

// A scene narrowed to one type: SceneOf<'BITS'> knows data.bits is present.
export type SceneOf<T extends SceneTypeName> = SceneByType[T];

// The full discriminated union (narrow on \`.type\`).
export type TypedScene =
  | ${union};
`;

  return `${header}\n${arms}\n${footer}`;
};

const argv = process.argv.slice(2);
const out = build();

if (argv[0] === '--check') {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== out) {
    console.error(`✗ ${OUT} is STALE — run: node scripts/gen-types.mjs`);
    process.exit(1);
  }
  console.log(`✓ TYPES CHECK PASSED (${OUT} matches the manifest; ${MANIFEST_TYPES.length} types)`);
  process.exit(0);
}

fs.writeFileSync(OUT, out);
console.log(`✓ wrote ${OUT} — ${MANIFEST_TYPES.length} per-type scene arms + SceneOf<T> (additive).`);
