#!/usr/bin/env node
// Regenerates src/topicsIndex.ts by scanning topics/*/. Run after adding a topic.
import fs from 'node:fs';

const dirs = fs.existsSync('topics')
  ? fs.readdirSync('topics').filter((d) => !d.startsWith('_') && fs.existsSync(`topics/${d}/long.json`))
  : [];
const lines = [
  '// AUTO-GENERATED by scripts/gen-index.mjs — do not edit by hand.',
  "import {VideoSpec} from './types';",
];
const entries = [];
dirs.forEach((slug, i) => {
  lines.push(`import long${i} from '../topics/${slug}/long.json';`);
  const hasShorts = fs.existsSync(`topics/${slug}/shorts.json`);
  if (hasShorts) lines.push(`import shorts${i} from '../topics/${slug}/shorts.json';`);
  entries.push(
    `  {slug: '${slug}', long: long${i} as unknown as VideoSpec, shorts: ${hasShorts ? `shorts${i} as unknown as VideoSpec` : 'null'}},`,
  );
});
lines.push('', 'export interface TopicEntry {slug: string; long: VideoSpec; shorts: VideoSpec | null;}', '', 'export const topics: TopicEntry[] = [', ...entries, '];', '');
fs.writeFileSync('src/topicsIndex.ts', lines.join('\n'));
console.log(`✓ src/topicsIndex.ts — ${dirs.length} topic(s): ${dirs.join(', ') || '(none)'}`);
