// THE SHORTCUT TABLE, IN A FORM A HUMAN CAN READ.
//
// `briefs/vscode-shortcuts/verified.json` is the machine record: every chord on the Windows card,
// pressed for real against `code serve-web` in Chromium, with the observable that had to move.
// This turns it into `briefs/vscode-shortcuts/VERIFIED.md`, which is what the course is written
// FROM — so no beat can teach a shortcut this machine has not demonstrated (LAW 0m, LAW 3).
//
// It also joins in the `when` clause each chord actually carries in this build, from the
// cross-check, because that is the difference between "Ctrl+C copies a line" and "Ctrl+C copies a
// line only when the editor has focus and nothing is selected" — and the second one is the thing
// worth teaching.
import fs from 'node:fs';

const verified = JSON.parse(fs.readFileSync('briefs/vscode-shortcuts/verified.json', 'utf8'));
const cross = fs.existsSync('out/probe/keys/crosscheck.json')
  ? JSON.parse(fs.readFileSync('out/probe/keys/crosscheck.json', 'utf8'))
  : {rows: []};

// WHICH BINDING ACTUALLY WINS.
//
// The docs are explicit: "Rules are evaluated from BOTTOM to TOP. The first rule that matches both
// the key and the when clause is accepted." So the LAST rule listed on a chord is the first one
// considered, not the last. Reporting `hits[0]` had `ctrl+x` teaching `notebook.cell.cut` — true
// that it is bound, false that it is what runs when you press it in an editor.
//
// Even bottom-first is only a best guess without evaluating every `when` against a live context,
// so a chord carrying several bindings says so out loud rather than pretending to one answer. The
// behaviour is what the probe verified; this column is provenance, not proof.
const whenFor = new Map();
for (const r of cross.rows ?? []) {
  if (!r.hits?.length) continue;
  const first = r.hits[r.hits.length - 1];
  whenFor.set(r.key, {command: first.command, when: first.when, count: r.hits.length});
}

const ICON = {pass: 'yes', fail: 'NO', error: 'ERROR', unverified: '—'};
const byCat = new Map();
for (const r of verified.results) {
  if (!byCat.has(r.cat)) byCat.set(r.cat, []);
  byCat.get(r.cat).push(r);
}

const out = [];
out.push('# VS Code shortcuts, verified on this machine');
out.push('');
out.push(`Build: **${verified.build}** · Surface: **${verified.surface}** · Measured: **${verified.measured ?? 'see verified.json'}**`);
out.push('');
out.push(`**${verified.pass} verified · ${verified.fail} failing · ${verified.unverified} unverified**, of ${verified.results.length} pressable chords.`);
out.push('');
out.push('Generated by `node scripts/keys-report.mjs` from `verified.json`. Do not hand-edit.');
out.push('');
out.push('"Verified" means the chord was PRESSED against a real workbench and the specific thing');
out.push('that command does was observed to happen. It does not mean "the shortcut is listed in the');
out.push('documentation" — the printed Windows card is a desktop document and 6 of its chords have');
out.push('no binding in this build at all. "Unverified" rows carry the measured reason; none of them');
out.push('is a guess.');
out.push('');

for (const [cat, rows] of byCat) {
  out.push(`## ${cat}`);
  out.push('');
  out.push('| Chord | Does | Verified | Binding considered first | Only when |');
  out.push('|---|---|---|---|---|');
  for (const r of rows) {
    const w = whenFor.get(r.keys);
    const status = r.status === 'unverified' ? `— *${r.why}*` : ICON[r.status] ?? r.status;
    const cmd = w ? '`' + w.command + '`' + (w.count > 1 ? ` <br>*(+${w.count - 1} more on this chord)*` : '') : '—';
    out.push(`| \`${r.keys}\` | ${r.label} | ${status} | ${cmd} | ${w?.when ? '`' + w.when + '`' : 'always' } |`);
  }
  out.push('');
}

const unbound = (cross.rows ?? []).filter((r) => !r.mouse && !r.hits?.length);
if (unbound.length) {
  out.push('## On the card, but not bound in this build');
  out.push('');
  out.push('All browser casualties — VS Code for the Web cannot take a chord the browser claims first.');
  out.push('');
  out.push('| Chord | Card says | Why not here |');
  out.push('|---|---|---|');
  const WHY = {
    'ctrl+shift+w': 'closes the browser window',
    'ctrl+=': 'browser zoom in',
    'ctrl+-': 'browser zoom out',
    'ctrl+k r': 'reveals the file in the OS file manager, which a web page cannot reach',
  };
  for (const r of unbound) {
    out.push(`| \`${r.key}\` | ${r.label} | ${WHY[r.key] ?? 'no binding in this build'} |`);
  }
  out.push('');
}

fs.writeFileSync('briefs/vscode-shortcuts/VERIFIED.md', out.join('\n') + '\n');
console.log(`briefs/vscode-shortcuts/VERIFIED.md — ${verified.results.length} chords, ${byCat.size} categories, ${unbound.length} unbound`);
