#!/usr/bin/env python3
"""iAuteur AI provider adapter — ONE `.complete(prompt)` across any AI API.

This is the single non-deterministic step in the automated pipeline: it takes a
prompt string (generated by the existing deterministic scripts) and returns the
model's text. Everything else (lint, normalize, assemble, fix-loop) stays the
judge, exactly as in the manual copy-paste flow.

Engines (selected by config; ZERO required third-party deps for the core path —
the OpenAI-compatible chat-completions call is a plain HTTPS POST via stdlib):

  azure           classic Azure OpenAI chat completions
                  {endpoint}/openai/deployments/{deployment}/chat/completions?api-version=...
                  auth header: api-key
  azure_v1        Azure OpenAI v1 surface: {endpoint}/openai/v1/chat/completions
                  auth header: Authorization: Bearer  (model = deployment name)
  openai          OpenAI OR any OpenAI-compatible base_url — covers Hugging Face
                  router (https://router.huggingface.co/v1), Groq, Together,
                  OpenRouter, Ollama, local vLLM / LM Studio, etc.
  litellm         OPTIONAL — only used if the `litellm` package is installed;
                  unlocks the non-OpenAI-shaped tail (Bedrock, Vertex, Anthropic
                  native, Cohere, …). Import-guarded; never required.

SECURITY: API keys are read ONLY from the process env or a gitignored `.env`.
They are NEVER logged, echoed, printed, or written to any tracked file. The
`--dry-run` and status paths mask the key.

Verified against live docs (2026-07-22): OpenAI-compatible /v1/chat/completions
is the universal standard; HF Inference Providers is a drop-in OpenAI-compatible
router; Azure OpenAI is reachable with api-key on the classic deployments URL.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# .env loading (stdlib — no python-dotenv dependency). Never overwrites an env
# var that is already set in the process, so real env wins over the file.
# ---------------------------------------------------------------------------

def load_env(path: Path | None = None) -> None:
    envfile = path or (ROOT / ".env")
    try:
        text = envfile.read_text(encoding="utf-8")
    except OSError:
        return
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = val


# ---------------------------------------------------------------------------
# Provider presets — NON-SECRET defaults (base URLs, auth style, key env name).
# The webui also ships these in webui/ai_providers.json for the settings UI;
# this dict is the runtime source of truth for the adapter.
# ---------------------------------------------------------------------------

PRESETS: dict[str, dict] = {
    "azure": {
        "engine": "azure",
        "key_env": "AZURE_OPENAI_API_KEY",
        "label": "Azure OpenAI (classic deployments)",
    },
    "azure_v1": {
        "engine": "azure_v1",
        "key_env": "AZURE_OPENAI_API_KEY",
        "label": "Azure OpenAI (v1 surface)",
    },
    "openai": {
        "engine": "openai",
        "base_url": "https://api.openai.com/v1",
        "key_env": "OPENAI_API_KEY",
        "label": "OpenAI",
    },
    "huggingface": {
        "engine": "openai",
        "base_url": "https://router.huggingface.co/v1",
        "key_env": "HF_TOKEN",
        "label": "Hugging Face Inference Providers (router)",
    },
    "groq": {
        "engine": "openai",
        "base_url": "https://api.groq.com/openai/v1",
        "key_env": "GROQ_API_KEY",
        "label": "Groq",
    },
    "together": {
        "engine": "openai",
        "base_url": "https://api.together.xyz/v1",
        "key_env": "TOGETHER_API_KEY",
        "label": "Together AI",
    },
    "openrouter": {
        "engine": "openai",
        "base_url": "https://openrouter.ai/api/v1",
        "key_env": "OPENROUTER_API_KEY",
        "label": "OpenRouter",
    },
    "ollama": {
        "engine": "openai",
        "base_url": "http://localhost:11434/v1",
        "key_env": "OLLAMA_API_KEY",  # ollama ignores the key; any value works
        "label": "Ollama (local)",
    },
    "litellm": {
        "engine": "litellm",
        "key_env": "LITELLM_API_KEY",
        "label": "LiteLLM (100+ providers, optional package)",
    },
    "custom": {
        "engine": "openai",
        "key_env": "IAUTEUR_AI_API_KEY",
        "label": "Custom OpenAI-compatible endpoint",
    },
}


class ProviderError(RuntimeError):
    """A configuration or upstream API error that should stop the pipeline."""


# ---------------------------------------------------------------------------
# Config resolution: preset < generic IAUTEUR_AI_* < provider-specific env.
# ---------------------------------------------------------------------------

def _first_env(*names: str) -> str | None:
    for n in names:
        v = os.environ.get(n)
        if v:
            return v
    return None


def resolve_config(overrides: dict | None = None) -> dict:
    """Build the effective provider config from env (+ optional explicit dict)."""
    load_env()
    ov = {k: v for k, v in (overrides or {}).items() if v not in (None, "")}

    provider = (ov.get("provider") or os.environ.get("IAUTEUR_AI_PROVIDER") or "").strip().lower()
    if not provider:
        # Infer: Azure creds present? else generic base_url? else unset.
        if os.environ.get("AZURE_OPENAI_ENDPOINT"):
            provider = "azure"
        elif _first_env("IAUTEUR_AI_BASE_URL"):
            provider = "custom"
        else:
            provider = ""
    preset = PRESETS.get(provider, PRESETS["custom"])
    engine = ov.get("engine") or preset["engine"]

    def num(name_generic, name_specific, default):
        v = ov.get(name_generic) or _first_env(name_specific, f"IAUTEUR_AI_{name_generic.upper()}")
        try:
            return type(default)(v) if v is not None else default
        except (TypeError, ValueError):
            return default

    cfg = {
        "provider": provider or "custom",
        "engine": engine,
        "max_tokens": int(num("max_tokens", "AZURE_OPENAI_MAX_TOKENS", 4000)),
        "temperature": float(num("temperature", "AZURE_OPENAI_TEMPERATURE", 0.3)),
        "timeout": int(num("timeout", "AZURE_OPENAI_TIMEOUT", 120)),
        "label": preset.get("label", provider),
    }

    key_env = preset.get("key_env", "IAUTEUR_AI_API_KEY")
    cfg["api_key"] = ov.get("api_key") or _first_env(key_env, "IAUTEUR_AI_API_KEY")
    cfg["key_env"] = key_env

    if engine in ("azure", "azure_v1"):
        cfg["endpoint"] = (ov.get("endpoint") or os.environ.get("AZURE_OPENAI_ENDPOINT") or "").rstrip("/")
        cfg["api_version"] = ov.get("api_version") or os.environ.get("AZURE_OPENAI_API_VERSION") or "2024-12-01-preview"
        cfg["model"] = (
            ov.get("model")
            or os.environ.get("AZURE_OPENAI_DEPLOYMENT_NAME")
            or os.environ.get("IAUTEUR_AI_MODEL")
            or ""
        )
    else:
        cfg["base_url"] = (
            ov.get("base_url")
            or os.environ.get("IAUTEUR_AI_BASE_URL")
            or preset.get("base_url")
            or ""
        ).rstrip("/")
        cfg["model"] = ov.get("model") or os.environ.get("IAUTEUR_AI_MODEL") or preset.get("model") or ""

    return cfg


def _mask(key: str | None) -> str:
    if not key:
        return "(missing)"
    if len(key) <= 8:
        return "***"
    return f"{key[:4]}…{key[-2:]}"


def describe(cfg: dict | None = None) -> dict:
    """Non-secret status for the settings UI. NEVER includes the key value."""
    c = cfg or resolve_config()
    return {
        "provider": c["provider"],
        "engine": c["engine"],
        "label": c["label"],
        "model": c.get("model", ""),
        "endpoint": c.get("endpoint", ""),
        "base_url": c.get("base_url", ""),
        "api_version": c.get("api_version", ""),
        "max_tokens": c["max_tokens"],
        "temperature": c["temperature"],
        "timeout": c["timeout"],
        "key_env": c["key_env"],
        "key_present": bool(c.get("api_key")),
        "key_hint": _mask(c.get("api_key")),
    }


def validate_config(cfg: dict) -> list[str]:
    """Return a list of human-readable problems (empty = ready to call)."""
    errs: list[str] = []
    if not cfg.get("api_key"):
        errs.append(f"No API key found (set {cfg['key_env']} in .env or the environment).")
    if cfg["engine"] in ("azure", "azure_v1"):
        if not cfg.get("endpoint"):
            errs.append("Azure needs AZURE_OPENAI_ENDPOINT.")
        if not cfg.get("model"):
            errs.append("Azure needs AZURE_OPENAI_DEPLOYMENT_NAME (the model deployment).")
    elif cfg["engine"] == "openai":
        if not cfg.get("base_url"):
            errs.append("Set a base_url (IAUTEUR_AI_BASE_URL) for the OpenAI-compatible endpoint.")
        if not cfg.get("model"):
            errs.append("Set a model (IAUTEUR_AI_MODEL).")
    elif cfg["engine"] == "litellm":
        if not cfg.get("model"):
            errs.append("LiteLLM needs a model string (IAUTEUR_AI_MODEL, e.g. 'bedrock/anthropic.claude-3').")
    return errs


# ---------------------------------------------------------------------------
# Request building + HTTP (stdlib).
# ---------------------------------------------------------------------------

def _build_request(cfg: dict, messages: list[dict]) -> tuple[str, dict, dict]:
    """Return (url, headers, payload) for the resolved engine. No key in logs."""
    payload: dict = {
        "messages": messages,
        "max_tokens": cfg["max_tokens"],
        "temperature": cfg["temperature"],
    }
    if cfg["engine"] == "azure":
        url = f"{cfg['endpoint']}/openai/deployments/{cfg['model']}/chat/completions?api-version={cfg['api_version']}"
        headers = {"api-key": cfg["api_key"]}
    elif cfg["engine"] == "azure_v1":
        url = f"{cfg['endpoint']}/openai/v1/chat/completions"
        headers = {"Authorization": f"Bearer {cfg['api_key']}"}
        payload["model"] = cfg["model"]
    else:  # openai / any OpenAI-compatible base_url
        url = f"{cfg['base_url']}/chat/completions"
        headers = {"Authorization": f"Bearer {cfg['api_key']}"}
        payload["model"] = cfg["model"]
    return url, headers, payload


def _post(url: str, headers: dict, payload: dict, timeout: int) -> dict:
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url, data=data, method="POST",
        headers={**headers, "Content-Type": "application/json", "Accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


_RETRYABLE = {408, 409, 429, 500, 502, 503, 504}


def _call_http(cfg: dict, messages: list[dict], retries: int = 3) -> str:
    url, headers, payload = _build_request(cfg, messages)
    last: Exception | None = None
    dropped_sampling = False
    for attempt in range(retries + 1):
        try:
            resp = _post(url, headers, payload, cfg["timeout"])
            choices = resp.get("choices") or []
            if not choices:
                raise ProviderError(f"No choices in response: {json.dumps(resp)[:400]}")
            msg = choices[0].get("message") or {}
            content = msg.get("content")
            if content is None:
                raise ProviderError(f"No message content: {json.dumps(choices[0])[:400]}")
            return content if isinstance(content, str) else json.dumps(content)
        except urllib.error.HTTPError as e:
            body = ""
            try:
                body = e.read().decode("utf-8", "replace")
            except Exception:
                pass
            # Azure/OpenAI content filter — surface clearly, not retryable.
            if e.code == 400 and "content_filter" in body.lower():
                raise ProviderError("The provider's content filter blocked this request.") from e
            # Some models reject temperature/max_tokens — retry once without them.
            if e.code == 400 and not dropped_sampling and (
                "temperature" in body.lower() or "max_tokens" in body.lower()
                or "max_completion_tokens" in body.lower()
            ):
                dropped_sampling = True
                payload.pop("temperature", None)
                mt = payload.pop("max_tokens", None)
                if mt is not None and "max_completion_tokens" in body.lower():
                    payload["max_completion_tokens"] = mt
                continue
            last = ProviderError(f"HTTP {e.code} from provider: {body[:400] or e.reason}")
            if e.code not in _RETRYABLE or attempt == retries:
                raise last from e
        except (urllib.error.URLError, TimeoutError) as e:
            last = ProviderError(f"Network error reaching provider: {getattr(e, 'reason', e)}")
            if attempt == retries:
                raise last from e
        time.sleep(min(2 ** attempt, 8))
    raise last or ProviderError("Unknown provider error")


def _call_litellm(cfg: dict, messages: list[dict]) -> str:
    try:
        import litellm  # type: ignore
    except ImportError as e:
        raise ProviderError(
            "The 'litellm' engine needs the litellm package. Install it (pip install litellm) "
            "or choose an OpenAI-compatible provider instead."
        ) from e
    resp = litellm.completion(
        model=cfg["model"],
        messages=messages,
        api_key=cfg.get("api_key"),
        api_base=cfg.get("base_url") or None,
        max_tokens=cfg["max_tokens"],
        temperature=cfg["temperature"],
        timeout=cfg["timeout"],
    )
    return resp["choices"][0]["message"]["content"]


class LLMClient:
    """Thin, engine-agnostic chat client. `complete()` is the only entry point."""

    def __init__(self, overrides: dict | None = None):
        self.cfg = resolve_config(overrides)
        problems = validate_config(self.cfg)
        if problems:
            raise ProviderError("AI provider not configured:\n  - " + "\n  - ".join(problems))

    def complete(self, prompt: str, system: str | None = None) -> str:
        messages: list[dict] = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})
        if self.cfg["engine"] == "litellm":
            return _call_litellm(self.cfg, messages)
        return _call_http(self.cfg, messages)


# ---------------------------------------------------------------------------
# JSON extraction — models wrap JSON in prose / ```fences```. Pull the object.
# ---------------------------------------------------------------------------

def strip_fences(text: str) -> str:
    t = text.strip()
    if t.startswith("```"):
        # drop the opening ``` / ```json / ```tsx line and the trailing ```
        first_nl = t.find("\n")
        if first_nl != -1:
            t = t[first_nl + 1:]
        if t.rstrip().endswith("```"):
            t = t.rstrip()[:-3]
    return t.strip()


def extract_json(text: str):
    """Return the first complete JSON object/array found in `text` (parsed)."""
    t = strip_fences(text)
    # Fast path: already valid.
    try:
        return json.loads(t)
    except json.JSONDecodeError:
        pass
    # Find the first { or [ and balance it (string-aware).
    start = None
    for i, ch in enumerate(t):
        if ch in "{[":
            start = i
            break
    if start is None:
        raise ProviderError("No JSON object/array found in model reply.")
    open_ch = t[start]
    close_ch = "}" if open_ch == "{" else "]"
    depth, in_str, esc = 0, False, False
    for i in range(start, len(t)):
        ch = t[i]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
        elif ch == open_ch:
            depth += 1
        elif ch == close_ch:
            depth -= 1
            if depth == 0:
                return json.loads(t[start:i + 1])
    raise ProviderError("Unbalanced JSON in model reply.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _read_arg(text: str | None, file: str | None) -> str | None:
    if text is not None:
        return text
    if file:
        return Path(file).read_text(encoding="utf-8")
    return None


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="iAuteur AI provider adapter")
    p.add_argument("--prompt")
    p.add_argument("--prompt-file")
    p.add_argument("--system")
    p.add_argument("--system-file")
    p.add_argument("--provider", help="override IAUTEUR_AI_PROVIDER")
    p.add_argument("--model", help="override model / deployment")
    p.add_argument("--dry-run", action="store_true", help="print the request (key masked); do NOT call")
    p.add_argument("--json", action="store_true", help="extract + print the JSON object from the reply")
    p.add_argument("--status", action="store_true", help="print resolved provider status (no key) as JSON")
    p.add_argument("--test", action="store_true", help="1-token connectivity ping")
    args = p.parse_args(argv)

    overrides = {}
    if args.provider:
        overrides["provider"] = args.provider
    if args.model:
        overrides["model"] = args.model
    cfg = resolve_config(overrides)

    if args.status:
        print(json.dumps(describe(cfg)))
        return 0

    problems = validate_config(cfg)

    if args.dry_run:
        prompt = _read_arg(args.prompt, args.prompt_file) or "(no prompt)"
        system = _read_arg(args.system, args.system_file)
        messages = ([{"role": "system", "content": system}] if system else []) + [
            {"role": "user", "content": prompt}
        ]
        if cfg["engine"] == "litellm":
            preview = {"engine": "litellm", "model": cfg["model"], "messages": messages}
        else:
            url, headers, payload = _build_request({**cfg, "api_key": "***"}, messages)
            preview = {"url": url, "headers": {**headers, **({"api-key": "***"} if "api-key" in headers else {"Authorization": "Bearer ***"})}, "payload": payload}
        print(json.dumps({"config": describe(cfg), "request": preview, "problems": problems}, indent=2))
        return 0

    if problems:
        print(json.dumps({"ok": False, "errors": problems}))
        return 1

    if args.test:
        t0 = time.time()
        try:
            reply = LLMClient(overrides).complete("Reply with the single word: OK")
            print(json.dumps({"ok": True, "model": cfg["model"], "latency_ms": int((time.time() - t0) * 1000), "reply": reply.strip()[:40]}))
            return 0
        except ProviderError as e:
            print(json.dumps({"ok": False, "error": str(e)}))
            return 1

    prompt = _read_arg(args.prompt, args.prompt_file)
    if prompt is None:
        p.error("provide --prompt or --prompt-file (or use --status / --dry-run / --test)")
    system = _read_arg(args.system, args.system_file)
    try:
        reply = LLMClient(overrides).complete(prompt, system)
    except ProviderError as e:
        print(json.dumps({"ok": False, "error": str(e)}), file=sys.stderr)
        return 1
    if args.json:
        sys.stdout.write(json.dumps(extract_json(reply)))
    else:
        sys.stdout.write(reply)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
