// AUTO-GENERATED by scripts/gen-types.mjs from scripts/lib/manifest.mjs.
// DO NOT EDIT BY HAND. Run `node scripts/gen-types.mjs` to regenerate.
// ADDITIVE: opt-in per-type scene typing. The canonical Scene/SceneData in
// ./types.ts are unchanged; use SceneOf<'BITS'> when you want narrowing.

export type SceneTypeName =
  | 'PRODUCTION_GRIND'
  | 'SCENE_FORGE'
  | 'VIDEO_PLAYER'
  | 'CHAT_TRIO'
  | 'PROMPT_HANDOUT'
  | 'APP_WINDOW'
  | 'CHECK_SWEEP'
  | 'PROMPT_HANDOFF'
  | 'TOPIC_INTAKE'
  | 'PIPELINE_GATE'
  | 'ASPECT_TWIN'
  | 'RESKIN_CAROUSEL'
  | 'WORD_ANCHOR_RAIL'
  | 'BUDGET_METER_ROW'
  | 'LAB_ASSEMBLY'
  | 'CAST_BOARD'
  | 'SPEC_TO_FRAME'
  | 'BATCH_SWEEP'
  | 'PIPELINE_GANTT'
  | 'HOOK'
  | 'TITLE_CARD'
  | 'CONCEPT_DIAGRAM'
  | 'KINETIC_TEXT'
  | 'STEP_FLOW'
  | 'LIST_BUILD'
  | 'RECAP'
  | 'STAT_CALLOUT'
  | 'OUTRO_CTA'
  | 'QUOTE_SPOTLIGHT'
  | 'STICKY_NOTE'
  | 'STAT_PANELS'
  | 'CHAT_MOCKUP'
  | 'SPLIT_PATHS'
  | 'BAR_COMPARE'
  | 'NOTIFICATION'
  | 'FLIP_CARD'
  | 'TIMELINE'
  | 'REVEAL'
  | 'LOWER_THIRD'
  | 'CHAPTER'
  | 'COUNTDOWN'
  | 'CREDITS_ROLL'
  | 'SUBSCRIBE_REMINDER'
  | 'LINE_CHART'
  | 'DONUT'
  | 'PROGRESS'
  | 'QUADRANT'
  | 'FUNNEL'
  | 'WATERFALL'
  | 'DIAGRAM'
  | 'PIPELINE'
  | 'LAYERED_STACK'
  | 'GRID_ARRAY'
  | 'SPEC_COMPARE'
  | 'NEURAL_NET'
  | 'PICTOGRAM'
  | 'RADAR'
  | 'CANDLESTICK'
  | 'BOX_PLOT'
  | 'TREEMAP'
  | 'SANKEY'
  | 'ICON_GRID'
  | 'ICON_CALLOUT'
  | 'ICON_BURST'
  | 'LOGO_WALL'
  | 'LOGO_VERSUS'
  | 'LOGO_TIMELINE'
  | 'CODE_WINDOW'
  | 'CODE_EDITOR'
  | 'TERMINAL_SESSION'
  | 'LOG_STREAM'
  | 'CODE_DIFF'
  | 'ERROR_TRACE'
  | 'WINDOW_FRAME'
  | 'AUTOMATION_RUN'
  | 'DOM_INSPECT'
  | 'NETWORK_WATERFALL'
  | 'DEVICE_FRAME'
  | 'CLOUD_ARCH'
  | 'K8S_CLUSTER'
  | 'KERNEL_BOUNDARY'
  | 'COST_METER'
  | 'SLO_GAUGE'
  | 'ERD'
  | 'IAC_PLAN'
  | 'AGENT_HARNESS'
  | 'KNOWLEDGE_GRAPH'
  | 'RETRIEVAL_RANK'
  | 'MODEL_STAGES'
  | 'CONFIDENCE_GATE'
  | 'SANDBOX_BOX'
  | 'FORMULA'
  | 'TRADEOFF_SCALE'
  | 'MOLECULE'
  | 'DNA_HELIX'
  | 'LABELED_FIGURE'
  | 'VECTOR_FIELD'
  | 'CIRCUIT_FLOW'
  | 'BITS'
  | 'MEMORY'
  | 'PACKET'
  | 'NUMBER_BASE'
  | 'POINTER_DIAGRAM'
  | 'ENCRYPTION'
  | 'CALL_STACK'
  | 'QUEUE'
  | 'BOOLEAN_LOGIC_GATES'
  | 'HASH_FUNCTION'
  | 'SORTING_VISUAL'
  | 'CLOCK_SIGNAL'
  | 'DATACENTER'
  | 'TRANSFORMER_BLOCK'
  | 'CACHE_PYRAMID'
  | 'GPU_CLUSTER'
  | 'ZOOM_SCALE'
  | 'DIE_SHOT'
  | 'TOKENIZER'
  | 'FILE_TREE'
  | 'DATABASE_TABLE'
  | 'GIT_BRANCH'
  | 'STATE_MACHINE'
  | 'EMBEDDING_SPACE'
  | 'API_REQUEST_RESPONSE'
  | 'PROCESS_TABLE'
  | 'TEST_MATRIX'
  | 'TEST_RUNNER'
  | 'CONTEXT_METER'
  | 'DRILL_IN'
  | 'TICKER_TAPE'
  | 'MAP_RADAR'
  | 'EVAL_DASHBOARD'
  | 'CHANNEL_CARD'
  | 'PHOTO'
  | 'SOUND_WAVE'
  | 'LOGO_REVEAL'
  | 'CAROUSEL'
  | 'GALLERY'
  | 'COMPARISON_SLIDER'
  | 'PHOTO_STACK'
  | 'IMAGE_SCENE'
  | 'ACTIVITY_CARD'
  | 'LOCATION_MAP'
  | 'VIDEO_HERO'
  | 'VIDEO_SPOTLIGHT'
  | 'MEDIA_CALLOUT'
  | 'MEDIA_COMPARE'
  | 'MEDIA_STAT_OVERLAY'
  | 'SCREENSHOT_CASCADE'
  | 'FLOATING_QUOTE_PILL'
  | 'OVERLAY_SPLIT_DEFINITIONS'
  | 'CYCLE_LOOP'
  | 'STEP_STACK_OVERLAY'
  | 'TITLE_BANNER_FOCUS'
  | 'TALKING_POINTS'
  | 'SLIDE_BULLETS_PIP'
  | 'CAPTION_KINETIC_OVERLAY'
  | 'PHOTO_TIMELINE';

// Fields every scene carries regardless of type (mirrors ./types.ts Scene).
export interface SceneCommon<T extends SceneTypeName> {
  id: string;
  type: T;
  narration: string;
  durationFrames?: number;
  timingSource?: string;
  background?: string;
  transition?: string;
  fx?: string;
  pip?: Record<string, unknown>;
  audio?: string;
}

export type ProductionGrindScene = SceneCommon<'PRODUCTION_GRIND'> & { data: {
    productionGrind: {
      headline?: string;
      windowTitle: string;
      takeLabel?: string;
      chores: Array<Record<string, unknown>>;
      tracks?: string[];
      totalLabel?: string;
      footNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type SceneForgeScene = SceneCommon<'SCENE_FORGE'> & { data: {
    sceneForge: {
      headline?: string;
      rows: Array<Record<string, unknown>>;
      targetIndex: number;
      askLabel?: string;
      stages?: string[];
      doneLabel?: string;
      footNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type VideoPlayerScene = SceneCommon<'VIDEO_PLAYER'> & { data: {
    videoPlayer: {
      headline?: string;
      clips: Array<Record<string, unknown>>;
      runtime?: string;
      startAt?: number;
      badge?: string;
      footNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type ChatTrioScene = SceneCommon<'CHAT_TRIO'> & { data: {
    chatTrio: {
      headline?: string;
      assistants: Array<Record<string, unknown>>;
      pasted: string;
      answerLabel?: string;
      answerLines?: number;
      answerJson?: string[];
      answerFile?: string;
      footNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type PromptHandoutScene = SceneCommon<'PROMPT_HANDOUT'> & { data: {
    promptHandout: {
      headline?: string;
      panelTitle: string;
      lines: string[];
      copyLabel?: string;
      copiedLabel?: string;
      hint?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type AppWindowScene = SceneCommon<'APP_WINDOW'> & { data: {
    appWindow: {
      headline?: string;
      windowTitle: string;
      steps?: string[];
      activeStep?: number;
      screenTitle?: string;
      fields: Array<Record<string, unknown>>;
      typeIndex?: number;
      button?: string;
      buttonDone?: string;
      caption?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type CheckSweepScene = SceneCommon<'CHECK_SWEEP'> & { data: {
    checkSweep: {
      headline?: string;
      subjectLabel: string;
      checks: Array<Record<string, unknown>>;
      caughtIndex?: number;
      caughtNote?: string;
      fixNote?: string;
      verdict?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type PromptHandoffScene = SceneCommon<'PROMPT_HANDOFF'> & { data: {
    promptHandoff: {
      headline?: string;
      outLabel: string;
      backLabel: string;
      assistants?: Array<Record<string, unknown>>;
      appLabel?: string;
      footNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type TopicIntakeScene = SceneCommon<'TOPIC_INTAKE'> & { data: {
    topicIntake: {
      headline?: string;
      fieldLabel: string;
      typed: string;
      choices?: Array<Record<string, unknown>>;
      caption?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type PipelineGateScene = SceneCommon<'PIPELINE_GATE'> & { data: {
    pipelineGate: {
      headline: string;
      proposerLabel: string;
      gateLabel: string;
      outputLabel: string;
      passLabel?: string;
      rejectLabel?: string;
      checks?: string[];
      footNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type AspectTwinScene = SceneCommon<'ASPECT_TWIN'> & { data: {
    aspectTwin: {
      headline: string;
      sourceLabel: string;
      wideLabel: string;
      tallLabel: string;
      variantLabels?: string[];
      countLabel?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type ReskinCarouselScene = SceneCommon<'RESKIN_CAROUSEL'> & { data: {
    reskin: {
      headline: string;
      sourceLabel: string;
      packs: Array<Record<string, unknown>>;
      tileTitle: string;
      footNote?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type WordAnchorRailScene = SceneCommon<'WORD_ANCHOR_RAIL'> & { data: {
    anchorRail: {
      headline: string;
      words: string[];
      marks: Array<Record<string, unknown>>;
      playhead?: number;
      footNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type BudgetMeterRowScene = SceneCommon<'BUDGET_METER_ROW'> & { data: {
    budgetMeter: {
      headline: string;
      rows: Array<Record<string, unknown>>;
      used: number[];
      cap: number;
      capLabel?: string;
      rejectNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type LabAssemblyScene = SceneCommon<'LAB_ASSEMBLY'> & { data: {
    labAssembly: {
      headline: string;
      stages: Array<Record<string, unknown>>;
      verdict?: string;
      rollbackNote?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type CastBoardScene = SceneCommon<'CAST_BOARD'> & { data: {
    castBoard: {
      headline: string;
      beatLabel: string;
      candidates: Array<Record<string, unknown>>;
      chosenIndex: number;
      verdict?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type SpecToFrameScene = SceneCommon<'SPEC_TO_FRAME'> & { data: {
    specToFrame: {
      headline: string;
      specLines: string[];
      frameLabel: string;
      frameBars?: number[];
      specCaption?: string;
      frameCaption?: string;
      color?: string;
      source?: string;
      atWord?: number;
    };
  } };

export type BatchSweepScene = SceneCommon<'BATCH_SWEEP'> & { data: {
    batchSweep: {
      headline: string;
      rows?: number;
      slow: Record<string, unknown>;
      fast: Record<string, unknown>;
      atWord?: number;
      source?: string;
    };
  } };

export type PipelineGanttScene = SceneCommon<'PIPELINE_GANTT'> & { data: {
    pipelineGantt: {
      headline?: string;
      stages: string[];
      count?: number;
      color?: string;
      caption?: string;
      atWord?: number;
      source?: string;
    };
  } };

export type HookScene = SceneCommon<'HOOK'> & { data: {
    headline: string;
    subtext?: string;
    heroAsset?: string;
    headlineAtWord?: number;
    heroAtWord?: number;
  } };

export type TitleCardScene = SceneCommon<'TITLE_CARD'> & { data: {
    title: string;
    subtitle?: string;
  } };

export type ConceptDiagramScene = SceneCommon<'CONCEPT_DIAGRAM'> & { data: {
    nodes: Array<Record<string, unknown>>;
    edges?: Array<Record<string, unknown>>;
  } };

export type KineticTextScene = SceneCommon<'KINETIC_TEXT'> & { data: {
    kinetic: {
      text: string;
      fx?: string;
      sub?: string;
      color?: string;
      atWord?: number;
    };
  } };

export type StepFlowScene = SceneCommon<'STEP_FLOW'> & { data: {
    steps: Array<Record<string, unknown>>;
    source?: string;
  } };

export type ListBuildScene = SceneCommon<'LIST_BUILD'> & { data: {
    heading?: string;
    items: Array<Record<string, unknown>>;
  } };

export type RecapScene = SceneCommon<'RECAP'> & { data: {
    heading?: string;
    points: Array<Record<string, unknown>>;
  } };

export type StatCalloutScene = SceneCommon<'STAT_CALLOUT'> & { data: {
    value: number;
    prefix?: string;
    suffix?: string;
    label: string;
    atWord?: number;
    source?: string;
    logos?: unknown;
  } };

export type OutroCtaScene = SceneCommon<'OUTRO_CTA'> & { data: {
    message: string;
    sub?: string;
  } };

export type QuoteSpotlightScene = SceneCommon<'QUOTE_SPOTLIGHT'> & { data: {
    quote: string;
    person?: Record<string, unknown>;
    source?: string;
    atWord?: number;
  } };

export type StickyNoteScene = SceneCommon<'STICKY_NOTE'> & { data: {
    stickyNote: {
      notes: Array<Record<string, unknown>>;
      color?: string;
      columns?: number;
      headline?: string;
      atWord?: number;
      source?: string;
    };
  } };

export type StatPanelsScene = SceneCommon<'STAT_PANELS'> & { data: {
    stats: Array<Record<string, unknown>>;
    verdict?: Record<string, unknown>;
    source?: string;
  } };

export type ChatMockupScene = SceneCommon<'CHAT_MOCKUP'> & { data: {
    panelLabel?: string;
    messages: Array<Record<string, unknown>>;
    source?: string;
  } };

export type SplitPathsScene = SceneCommon<'SPLIT_PATHS'> & { data: {
    center?: Record<string, unknown>;
    left: Record<string, unknown>;
    right: Record<string, unknown>;
    source?: string;
  } };

export type BarCompareScene = SceneCommon<'BAR_COMPARE'> & { data: {
    bars: Array<Record<string, unknown>>;
    maxValue?: number;
    source?: string;
  } };

export type NotificationScene = SceneCommon<'NOTIFICATION'> & { data: {
    notifications: Array<Record<string, unknown>>;
  } };

export type FlipCardScene = SceneCommon<'FLIP_CARD'> & { data: {
    flip: {
      front: Record<string, unknown>;
      back: Record<string, unknown>;
      atWord?: number;
    };
  } };

export type TimelineScene = SceneCommon<'TIMELINE'> & { data: {
    timeline: {
      milestones: Array<Record<string, unknown>>;
    };
  } };

export type RevealScene = SceneCommon<'REVEAL'> & { data: {
    reveal: {
      statement: string;
      kicker?: string;
      sub?: string;
      atWord?: number;
    };
  } };

export type LowerThirdScene = SceneCommon<'LOWER_THIRD'> & { data: {
    lowerThird: {
      kicker?: string;
      title: string;
      subtitle?: string;
      asset?: string;
      atWord?: number;
    };
  } };

export type ChapterScene = SceneCommon<'CHAPTER'> & { data: {
    chapter: {
      number: string;
      title: string;
      subtitle?: string;
    };
  } };

export type CountdownScene = SceneCommon<'COUNTDOWN'> & { data: {
    countdown: {
      from: number;
      label?: string;
      go?: string;
      atWord?: number;
    };
  } };

export type CreditsRollScene = SceneCommon<'CREDITS_ROLL'> & { data: {
    credits: {
      title?: string;
      rows: Array<Record<string, unknown>>;
      speed?: number;
    };
  } };

export type SubscribeReminderScene = SceneCommon<'SUBSCRIBE_REMINDER'> & { data: {
    subscribe: {
      text?: string;
      sub?: string;
      handle?: string;
      atWord?: number;
    };
  } };

export type LineChartScene = SceneCommon<'LINE_CHART'> & { data: {
    lineChart: {
      series: Array<Record<string, unknown>>;
      xAxis?: Array<Record<string, unknown>>;
      yMax?: number;
      yUnit?: string;
      area?: boolean;
      atWord?: number;
    };
  } };

export type DonutScene = SceneCommon<'DONUT'> & { data: {
    donut: {
      segments: Array<Record<string, unknown>>;
      variant?: string;
      centerValue?: string;
      centerLabel?: string;
      atWord?: number;
    };
  } };

export type ProgressScene = SceneCommon<'PROGRESS'> & { data: {
    progress: {
      items: Array<Record<string, unknown>>;
      variant?: string;
    };
  } };

export type QuadrantScene = SceneCommon<'QUADRANT'> & { data: {
    quadrant: {
      xAxis: Record<string, unknown>;
      yAxis: Record<string, unknown>;
      points: Array<Record<string, unknown>>;
    };
  } };

export type FunnelScene = SceneCommon<'FUNNEL'> & { data: {
    funnel: {
      stages: Array<Record<string, unknown>>;
      unit?: string;
    };
  } };

export type WaterfallScene = SceneCommon<'WATERFALL'> & { data: {
    waterfallChart: {
      bars: Array<Record<string, unknown>>;
      unit?: string;
    };
  } };

export type DiagramScene = SceneCommon<'DIAGRAM'> & { data: {
    diagram: {
      layout: string;
      nodes: Array<Record<string, unknown>>;
      edges?: Array<Record<string, unknown>>;
      direction?: string;
    };
  } };

export type PipelineScene = SceneCommon<'PIPELINE'> & { data: {
    pipeline: {
      headline?: string;
      stages: Array<Record<string, unknown>>;
      tokenLabel?: string;
      loop?: boolean;
      atWord?: number;
    };
  } };

export type LayeredStackScene = SceneCommon<'LAYERED_STACK'> & { data: {
    stack: {
      headline?: string;
      layers: Array<Record<string, unknown>>;
      signal?: string;
      atWord?: number;
    };
  } };

export type GridArrayScene = SceneCommon<'GRID_ARRAY'> & { data: {
    grid: {
      rows: number;
      cols: number;
      mode?: string;
      label?: string;
      legendA?: string;
      legendB?: string;
      atWord?: number;
    };
  } };

export type SpecCompareScene = SceneCommon<'SPEC_COMPARE'> & { data: {
    compare: {
      headline?: string;
      a: Record<string, unknown>;
      b: Record<string, unknown>;
      rows: Array<Record<string, unknown>>;
      atWord?: number;
    };
  } };

export type NeuralNetScene = SceneCommon<'NEURAL_NET'> & { data: {
    net: {
      headline?: string;
      layers: number[];
      labels?: string[];
      atWord?: number;
    };
  } };

export type PictogramScene = SceneCommon<'PICTOGRAM'> & { data: {
    pictogram: {
      rows: Array<Record<string, unknown>>;
      icon?: string;
      perIcon?: number;
      unit?: string;
    };
  } };

export type RadarScene = SceneCommon<'RADAR'> & { data: {
    radar: {
      axes: string[];
      series: Array<Record<string, unknown>>;
      max?: number;
      unit?: string;
    };
  } };

export type CandlestickScene = SceneCommon<'CANDLESTICK'> & { data: {
    candlestick: {
      candles: Array<Record<string, unknown>>;
      ma?: number[];
      prefix?: string;
      unit?: string;
    };
  } };

export type BoxPlotScene = SceneCommon<'BOX_PLOT'> & { data: {
    boxPlot: {
      boxes: Array<Record<string, unknown>>;
      prefix?: string;
      unit?: string;
    };
  } };

export type TreemapScene = SceneCommon<'TREEMAP'> & { data: {
    treemap: {
      items: Array<Record<string, unknown>>;
      unit?: string;
    };
  } };

export type SankeyScene = SceneCommon<'SANKEY'> & { data: {
    sankey: {
      nodes: Array<Record<string, unknown>>;
      links: Array<Record<string, unknown>>;
      unit?: string;
    };
  } };

export type IconGridScene = SceneCommon<'ICON_GRID'> & { data: {
    iconGrid: {
      items: Array<Record<string, unknown>>;
      cols?: number;
    };
  } };

export type IconCalloutScene = SceneCommon<'ICON_CALLOUT'> & { data: {
    iconCallout: {
      icon: string;
      heading: string;
      sub?: string;
      points?: string[];
      atWord?: number;
    };
  } };

export type IconBurstScene = SceneCommon<'ICON_BURST'> & { data: {
    iconBurst: {
      center: Record<string, unknown>;
      spokes: Array<Record<string, unknown>>;
      atWord?: number;
    };
  } };

export type LogoWallScene = SceneCommon<'LOGO_WALL'> & { data: {
    logoWall: {
      logos: Array<Record<string, unknown>>;
      cols?: number;
    };
  } };

export type LogoVersusScene = SceneCommon<'LOGO_VERSUS'> & { data: {
    logoVersus: {
      left: Record<string, unknown>;
      right: Record<string, unknown>;
      winner?: string;
      atWord?: number;
    };
  } };

export type LogoTimelineScene = SceneCommon<'LOGO_TIMELINE'> & { data: {
    logoTimeline: {
      entries: Array<Record<string, unknown>>;
    };
  } };

export type CodeWindowScene = SceneCommon<'CODE_WINDOW'> & { data: {
    code: {
      lines: Array<Record<string, unknown>>;
      output?: Array<Record<string, unknown>>;
      filename?: string;
      language?: string;
      runLabel?: string;
      atWord?: number;
    };
  } };

export type CodeEditorScene = SceneCommon<'CODE_EDITOR'> & { data: {
    editor: {
      lines: string[];
      tabs?: Array<Record<string, unknown>>;
      lang?: string;
      highlight?: Record<string, unknown>;
      squiggle?: Record<string, unknown>;
      variant?: string;
      atWord?: number;
    };
  } };

export type TerminalSessionScene = SceneCommon<'TERMINAL_SESSION'> & { data: {
    terminal: {
      commands: Array<Record<string, unknown>>;
      promptLabel?: string;
      cwd?: string;
      atWord?: number;
    };
  } };

export type LogStreamScene = SceneCommon<'LOG_STREAM'> & { data: {
    logs: {
      lines: Array<Record<string, unknown>>;
      highlight?: number;
      rate?: string;
      atWord?: number;
    };
  } };

export type CodeDiffScene = SceneCommon<'CODE_DIFF'> & { data: {
    diff: {
      rows: Array<Record<string, unknown>>;
      fileName?: string;
      stat?: Record<string, unknown>;
      atWord?: number;
    };
  } };

export type ErrorTraceScene = SceneCommon<'ERROR_TRACE'> & { data: {
    callStack: {
      frames: Array<Record<string, unknown>>;
      mode?: string;
      exception?: string;
      culprit?: number;
      atWord?: number;
    };
  } };

export type WindowFrameScene = SceneCommon<'WINDOW_FRAME'> & { data: {
    window: {
      content: Record<string, unknown>;
      variant?: string;
      url?: string;
      title?: string;
      devtools?: Record<string, unknown>;
      atWord?: number;
    };
  } };

export type AutomationRunScene = SceneCommon<'AUTOMATION_RUN'> & { data: {
    auto: {
      content: Record<string, unknown>;
      steps: Array<Record<string, unknown>>;
      url?: string;
      runner?: string;
      atWord?: number;
    };
  } };

export type DomInspectScene = SceneCommon<'DOM_INSPECT'> & { data: {
    dom: {
      nodes: Array<Record<string, unknown>>;
      selector?: string;
      highlight?: number;
      atWord?: number;
    };
  } };

export type NetworkWaterfallScene = SceneCommon<'NETWORK_WATERFALL'> & { data: {
    waterfall: {
      requests: Array<Record<string, unknown>>;
      totalMs?: number;
      atWord?: number;
    };
  } };

export type DeviceFrameScene = SceneCommon<'DEVICE_FRAME'> & { data: {
    device: {
      content: Record<string, unknown>;
      os?: string;
      notification?: Record<string, unknown>;
      atWord?: number;
    };
  } };

export type CloudArchScene = SceneCommon<'CLOUD_ARCH'> & { data: {
    cloud: {
      nodes: Array<Record<string, unknown>>;
      boundaries?: Array<Record<string, unknown>>;
      edges?: Array<Record<string, unknown>>;
      provider?: string;
      atWord?: number;
    };
  } };

export type K8sClusterScene = SceneCommon<'K8S_CLUSTER'> & { data: {
    k8s: {
      nodes: Array<Record<string, unknown>>;
      mode?: string;
      controlPlane?: string;
      fromReplicas?: number;
      toReplicas?: number;
      atWord?: number;
    };
  } };

export type KernelBoundaryScene = SceneCommon<'KERNEL_BOUNDARY'> & { data: {
    kernel: {
      userLabel?: string;
      kernelLabel?: string;
      syscall?: string;
      result?: string;
      steps?: Array<Record<string, unknown>>;
      userChips?: string[];
      atWord?: number;
    };
  } };

export type CostMeterScene = SceneCommon<'COST_METER'> & { data: {
    cost: {
      value: number;
      budget: number;
      unit?: string;
      period?: string;
      atWord?: number;
    };
  } };

export type SloGaugeScene = SceneCommon<'SLO_GAUGE'> & { data: {
    slo: {
      availability: number;
      target?: number;
      budgetSpent?: number;
      period?: string;
      atWord?: number;
    };
  } };

export type ErdScene = SceneCommon<'ERD'> & { data: {
    erd: {
      tables: Array<Record<string, unknown>>;
      relations?: Array<Record<string, unknown>>;
      atWord?: number;
    };
  } };

export type IacPlanScene = SceneCommon<'IAC_PLAN'> & { data: {
    iac: {
      rows: Array<Record<string, unknown>>;
      atWord?: number;
    };
  } };

export type AgentHarnessScene = SceneCommon<'AGENT_HARNESS'> & { data: {
    harness: {
      rings: Array<Record<string, unknown>>;
      agent?: string;
      guardrail?: Record<string, unknown>;
      atWord?: number;
    };
  } };

export type KnowledgeGraphScene = SceneCommon<'KNOWLEDGE_GRAPH'> & { data: {
    kg: {
      nodes: Array<Record<string, unknown>>;
      edges: Array<Record<string, unknown>>;
      queryPath?: string[];
      atWord?: number;
    };
  } };

export type RetrievalRankScene = SceneCommon<'RETRIEVAL_RANK'> & { data: {
    retrieval: {
      chunks: Array<Record<string, unknown>>;
      rerankAtWord?: number;
      fuseAtWord?: number;
      atWord?: number;
    };
  } };

export type ModelStagesScene = SceneCommon<'MODEL_STAGES'> & { data: {
    modelStages: {
      prompt: string;
      stages: Array<Record<string, unknown>>;
      atWord?: number;
    };
  } };

export type ConfidenceGateScene = SceneCommon<'CONFIDENCE_GATE'> & { data: {
    confidence: {
      value: number;
      threshold: number;
      mode?: string;
      reason?: string;
      style?: string;
      atWord?: number;
    };
  } };

export type SandboxBoxScene = SceneCommon<'SANDBOX_BOX'> & { data: {
    sandbox: {
      allowed: string[];
      blocked: string[];
      label?: string;
      atWord?: number;
    };
  } };

export type FormulaScene = SceneCommon<'FORMULA'> & { data: {
    formula: {
      parts: Array<Record<string, unknown>>;
      label?: string;
    };
  } };

export type TradeoffScaleScene = SceneCommon<'TRADEOFF_SCALE'> & { data: {
    tradeoff: {
      headline?: string;
      left: Record<string, unknown>;
      right: Record<string, unknown>;
      lean?: number;
      caption?: string;
      atWord?: number;
      source?: string;
    };
  } };

export type MoleculeScene = SceneCommon<'MOLECULE'> & { data: {
    molecule: {
      atoms: Array<Record<string, unknown>>;
      bonds: Array<Record<string, unknown>>;
      name?: string;
      atWord?: number;
    };
  } };

export type DnaHelixScene = SceneCommon<'DNA_HELIX'> & { data: {
    dnaHelix: {
      pairs: Array<Record<string, unknown>>;
      atWord?: number;
    };
  } };

export type LabeledFigureScene = SceneCommon<'LABELED_FIGURE'> & { data: {
    labeledFigure: {
      subject: string;
      callouts: Array<Record<string, unknown>>;
      atWord?: number;
    };
  } };

export type VectorFieldScene = SceneCommon<'VECTOR_FIELD'> & { data: {
    vectorField: {
      mode?: string;
      cols?: number;
      rows?: number;
      pattern?: string;
      legend?: string;
      body?: string;
      bodyLabel?: string;
      forces?: Array<Record<string, unknown>>;
      atWord?: number;
    };
  } };

export type CircuitFlowScene = SceneCommon<'CIRCUIT_FLOW'> & { data: {
    circuitFlow: {
      components: Array<Record<string, unknown>>;
      currentLabel?: string;
      atWord?: number;
    };
  } };

export type BitsScene = SceneCommon<'BITS'> & { data: {
    bits: {
      value: number;
      bits?: number;
      label?: string;
      showPlaceValues?: boolean;
      atWord?: number;
    };
  } };

export type MemoryScene = SceneCommon<'MEMORY'> & { data: {
    memory: {
      cells: Array<Record<string, unknown>>;
      label?: string;
      columns?: number;
      highlight?: number;
      pointerLabel?: string;
      atWord?: number;
    };
  } };

export type PacketScene = SceneCommon<'PACKET'> & { data: {
    packet: {
      hops: Array<Record<string, unknown>>;
      packetLabel?: string;
      atWord?: number;
    };
  } };

export type NumberBaseScene = SceneCommon<'NUMBER_BASE'> & { data: {
    numberBase: {
      value: number;
      label?: string;
      atWord?: number;
    };
  } };

export type PointerDiagramScene = SceneCommon<'POINTER_DIAGRAM'> & { data: {
    pointers: {
      nodes: Array<Record<string, unknown>>;
      headLabel?: string;
      atWord?: number;
    };
  } };

export type EncryptionScene = SceneCommon<'ENCRYPTION'> & { data: {
    encryption: {
      plaintext?: string;
      ciphertext?: string;
      keyLabel?: string;
      mode?: string;
      atWord?: number;
    };
  } };

export type CallStackScene = SceneCommon<'CALL_STACK'> & { data: {
    callStack: {
      frames: Array<Record<string, unknown>>;
      headline?: string;
      mode?: string;
      atWord?: number;
    };
  } };

export type QueueScene = SceneCommon<'QUEUE'> & { data: {
    queue: {
      items: Array<Record<string, unknown>>;
      headline?: string;
      frontLabel?: string;
      backLabel?: string;
      atWord?: number;
    };
  } };

export type BooleanLogicGatesScene = SceneCommon<'BOOLEAN_LOGIC_GATES'> & { data: {
    logic: {
      gates: Array<Record<string, unknown>>;
      headline?: string;
      atWord?: number;
    };
  } };

export type HashFunctionScene = SceneCommon<'HASH_FUNCTION'> & { data: {
    hash: {
      input?: string;
      algo?: string;
      digest?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type SortingVisualScene = SceneCommon<'SORTING_VISUAL'> & { data: {
    sort: {
      values: number[];
      label?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type ClockSignalScene = SceneCommon<'CLOCK_SIGNAL'> & { data: {
    clock: {
      cycles?: number;
      label?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type DatacenterScene = SceneCommon<'DATACENTER'> & { data: {
    datacenter: {
      variant?: string;
      racks?: Array<Record<string, unknown>>;
      units?: Array<Record<string, unknown>>;
      spineLabel?: string;
      rackLabel?: string;
      highlight?: number;
      headline?: string;
      atWord?: number;
    };
  } };

export type TransformerBlockScene = SceneCommon<'TRANSFORMER_BLOCK'> & { data: {
    transformer: {
      blocks: Array<Record<string, unknown>>;
      repeatFrom?: number;
      repeatTo?: number;
      repeatLabel?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type CachePyramidScene = SceneCommon<'CACHE_PYRAMID'> & { data: {
    pyramid: {
      tiers: Array<Record<string, unknown>>;
      axisTop?: string;
      axisBottom?: string;
      variant?: string;
      mode?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type GpuClusterScene = SceneCommon<'GPU_CLUSTER'> & { data: {
    gpuCluster: {
      nodes?: number;
      gpusPerNode?: number;
      interconnect?: string;
      totalLabel?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type ZoomScaleScene = SceneCommon<'ZOOM_SCALE'> & { data: {
    zoomScale: {
      levels: Array<Record<string, unknown>>;
      headline?: string;
      atWord?: number;
    };
  } };

export type DieShotScene = SceneCommon<'DIE_SHOT'> & { data: {
    die: {
      cols: number;
      rows: number;
      blocks: Array<Record<string, unknown>>;
      chipLabel?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type TokenizerScene = SceneCommon<'TOKENIZER'> & { data: {
    tokenizer: {
      tokens: Array<Record<string, unknown>>;
      text?: string;
      showVectors?: boolean;
      headline?: string;
      atWord?: number;
    };
  } };

export type FileTreeScene = SceneCommon<'FILE_TREE'> & { data: {
    fileTree: {
      nodes: Array<Record<string, unknown>>;
      highlight?: number;
      headline?: string;
      atWord?: number;
    };
  } };

export type DatabaseTableScene = SceneCommon<'DATABASE_TABLE'> & { data: {
    database: {
      columns: string[];
      rows: Array<Record<string, unknown>>;
      tableName?: string;
      query?: string;
      highlight?: number[];
      headline?: string;
      atWord?: number;
    };
  } };

export type GitBranchScene = SceneCommon<'GIT_BRANCH'> & { data: {
    git: {
      lanes: string[];
      commits: Array<Record<string, unknown>>;
      links?: Array<Record<string, unknown>>;
      headline?: string;
      atWord?: number;
    };
  } };

export type StateMachineScene = SceneCommon<'STATE_MACHINE'> & { data: {
    stateMachine: {
      states: Array<Record<string, unknown>>;
      transitions: Array<Record<string, unknown>>;
      active?: number;
      variant?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type EmbeddingSpaceScene = SceneCommon<'EMBEDDING_SPACE'> & { data: {
    embedding: {
      points: Array<Record<string, unknown>>;
      clusters?: string[];
      axisX?: string;
      axisY?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type ApiRequestResponseScene = SceneCommon<'API_REQUEST_RESPONSE'> & { data: {
    api: {
      method?: string;
      path?: string;
      requestLines?: string[];
      status?: string;
      statusText?: string;
      responseLines?: string[];
      clientLabel?: string;
      serverLabel?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type ProcessTableScene = SceneCommon<'PROCESS_TABLE'> & { data: {
    proc: {
      rows: Array<Record<string, unknown>>;
      sortBy?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type TestMatrixScene = SceneCommon<'TEST_MATRIX'> & { data: {
    testMatrix: {
      rows: string[];
      cols: string[];
      cells: Array<Record<string, unknown>>;
      emphasize?: Record<string, unknown>;
      headline?: string;
      atWord?: number;
    };
  } };

export type TestRunnerScene = SceneCommon<'TEST_RUNNER'> & { data: {
    testRunner: {
      nodes: Array<Record<string, unknown>>;
      passed?: number;
      failed?: number;
      failIndex?: number;
      expected?: string;
      actual?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type ContextMeterScene = SceneCommon<'CONTEXT_METER'> & { data: {
    context: {
      segments: Array<Record<string, unknown>>;
      windowTokens?: number;
      verdict?: string;
      headline?: string;
      atWord?: number;
    };
  } };

export type DrillInScene = SceneCommon<'DRILL_IN'> & { data: {
    drillIn: {
      overview: Record<string, unknown>;
      focusId: string;
      detail: Record<string, unknown>;
      pushAtWord?: number;
      headline?: string;
      atWord?: number;
    };
  } };

export type TickerTapeScene = SceneCommon<'TICKER_TAPE'> & { data: {
    ticker: {
      entries: Array<Record<string, unknown>>;
      featured?: string;
      rows?: number;
      atWord?: number;
    };
  } };

export type MapRadarScene = SceneCommon<'MAP_RADAR'> & { data: {
    mapRadar: {
      blips: Array<Record<string, unknown>>;
      rings?: number;
      ringLabels?: string[];
      sweepLabel?: string;
      atWord?: number;
    };
  } };

export type EvalDashboardScene = SceneCommon<'EVAL_DASHBOARD'> & { data: {
    evalDash: {
      metrics: Array<Record<string, unknown>>;
      headline?: string;
      atWord?: number;
    };
  } };

export type ChannelCardScene = SceneCommon<'CHANNEL_CARD'> & { data: {
    handle?: string;
    tagline?: string;
    atWord?: number;
  } };

export type PhotoScene = SceneCommon<'PHOTO'> & { data: {
    photo: {
      asset: string;
      caption?: string;
      kicker?: string;
      pan?: string;
      atWord?: number;
    };
  } };

export type SoundWaveScene = SceneCommon<'SOUND_WAVE'> & { data: {
    wave: {
      label?: string;
      bars?: number;
      atWord?: number;
    };
  } };

export type LogoRevealScene = SceneCommon<'LOGO_REVEAL'> & { data: {
    logo: {
      name?: string;
      tagline?: string;
      asset?: string;
      atWord?: number;
    };
  } };

export type CarouselScene = SceneCommon<'CAROUSEL'> & { data: {
    carousel: {
      items: Array<Record<string, unknown>>;
      speed?: number;
      atWord?: number;
    };
  } };

export type GalleryScene = SceneCommon<'GALLERY'> & { data: {
    gallery: {
      tiles: Array<Record<string, unknown>>;
      columns?: number;
      variant?: string;
    };
  } };

export type ComparisonSliderScene = SceneCommon<'COMPARISON_SLIDER'> & { data: {
    comparison: {
      before: Record<string, unknown>;
      after: Record<string, unknown>;
      atWord?: number;
    };
  } };

export type PhotoStackScene = SceneCommon<'PHOTO_STACK'> & { data: {
    photoStack: {
      cards: Array<Record<string, unknown>>;
    };
  } };

export type ImageSceneScene = SceneCommon<'IMAGE_SCENE'> & { data: {
    image: {
      asset: string;
      variant?: string;
      caption?: string;
      pip?: Record<string, unknown>;
      atWord?: number;
    };
  } };

export type ActivityCardScene = SceneCommon<'ACTIVITY_CARD'> & { data: {
    activity: {
      value: string;
      data: Array<Record<string, unknown>>;
      title?: string;
      trend?: string;
      trendColor?: string;
      range?: string;
      atWord?: number;
    };
  } };

export type LocationMapScene = SceneCommon<'LOCATION_MAP'> & { data: {
    locationMap: {
      location?: string;
      coordinates?: string;
      status?: string;
      atWord?: number;
    };
  } };

export type VideoHeroScene = SceneCommon<'VIDEO_HERO'> & { data: {
    videoHero: {
      src?: string;
      headline?: string;
      kicker?: string;
      sub?: string;
      treatment?: string;
      zoom?: boolean;
      atWord?: number;
    };
  } };

export type VideoSpotlightScene = SceneCommon<'VIDEO_SPOTLIGHT'> & { data: {
    videoSpotlight: {
      src?: string;
      kind?: string;
      name?: string;
      role?: string;
      kicker?: string;
      atWord?: number;
    };
  } };

export type MediaCalloutScene = SceneCommon<'MEDIA_CALLOUT'> & { data: {
    mediaCallout: {
      callouts: Array<Record<string, unknown>>;
      src?: string;
      kind?: string;
      headline?: string;
      treatment?: string;
    };
  } };

export type MediaCompareScene = SceneCommon<'MEDIA_COMPARE'> & { data: {
    mediaCompare: {
      a: Record<string, unknown>;
      b: Record<string, unknown>;
      headline?: string;
      mode?: string;
      vs?: boolean;
      atWord?: number;
    };
  } };

export type MediaStatOverlayScene = SceneCommon<'MEDIA_STAT_OVERLAY'> & { data: {
    mediaStat: {
      stats: Array<Record<string, unknown>>;
      src?: string;
      kind?: string;
      headline?: string;
      treatment?: string;
    };
  } };

export type ScreenshotCascadeScene = SceneCommon<'SCREENSHOT_CASCADE'> & { data: {
    screenshotCascade: {
      shots: Array<Record<string, unknown>>;
      headline?: string;
    };
  } };

export type FloatingQuotePillScene = SceneCommon<'FLOATING_QUOTE_PILL'> & { data: {
    floatingQuote: {
      quote: string;
      attribution?: string;
      src?: string;
      kind?: string;
      atWord?: number;
    };
  } };

export type OverlaySplitDefinitionsScene = SceneCommon<'OVERLAY_SPLIT_DEFINITIONS'> & { data: {
    splitDefs: {
      left: Record<string, unknown>;
      right: Record<string, unknown>;
      src?: string;
      kind?: string;
    };
  } };

export type CycleLoopScene = SceneCommon<'CYCLE_LOOP'> & { data: {
    cycleLoop: {
      nodes: Array<Record<string, unknown>>;
      headline?: string;
      src?: string;
      kind?: string;
    };
  } };

export type StepStackOverlayScene = SceneCommon<'STEP_STACK_OVERLAY'> & { data: {
    stepStack: {
      steps: Array<Record<string, unknown>>;
      headline?: string;
      chip?: string;
      dock?: string;
      src?: string;
      kind?: string;
    };
  } };

export type TitleBannerFocusScene = SceneCommon<'TITLE_BANNER_FOCUS'> & { data: {
    titleBanner: {
      title: string;
      kicker?: string;
      subtitle?: string;
      src?: string;
      kind?: string;
      atWord?: number;
    };
  } };

export type TalkingPointsScene = SceneCommon<'TALKING_POINTS'> & { data: {
    talkingPoints: {
      points: Array<Record<string, unknown>>;
      headline?: string;
      lead?: string;
      media?: string;
      src?: string;
      kind?: string;
      atWord?: number;
    };
  } };

export type SlideBulletsPipScene = SceneCommon<'SLIDE_BULLETS_PIP'> & { data: {
    slideBullets: {
      heading: string;
      bullets: Array<Record<string, unknown>>;
      src?: string;
      kind?: string;
    };
  } };

export type CaptionKineticOverlayScene = SceneCommon<'CAPTION_KINETIC_OVERLAY'> & { data: {
    captionKinetic: {
      caption: string;
      position?: string;
      src?: string;
      kind?: string;
      atWord?: number;
    };
  } };

export type PhotoTimelineScene = SceneCommon<'PHOTO_TIMELINE'> & { data: {
    photoTimeline: {
      entries: Array<Record<string, unknown>>;
      headline?: string;
    };
  } };

export interface SceneByType {
  PRODUCTION_GRIND: ProductionGrindScene;
  SCENE_FORGE: SceneForgeScene;
  VIDEO_PLAYER: VideoPlayerScene;
  CHAT_TRIO: ChatTrioScene;
  PROMPT_HANDOUT: PromptHandoutScene;
  APP_WINDOW: AppWindowScene;
  CHECK_SWEEP: CheckSweepScene;
  PROMPT_HANDOFF: PromptHandoffScene;
  TOPIC_INTAKE: TopicIntakeScene;
  PIPELINE_GATE: PipelineGateScene;
  ASPECT_TWIN: AspectTwinScene;
  RESKIN_CAROUSEL: ReskinCarouselScene;
  WORD_ANCHOR_RAIL: WordAnchorRailScene;
  BUDGET_METER_ROW: BudgetMeterRowScene;
  LAB_ASSEMBLY: LabAssemblyScene;
  CAST_BOARD: CastBoardScene;
  SPEC_TO_FRAME: SpecToFrameScene;
  BATCH_SWEEP: BatchSweepScene;
  PIPELINE_GANTT: PipelineGanttScene;
  HOOK: HookScene;
  TITLE_CARD: TitleCardScene;
  CONCEPT_DIAGRAM: ConceptDiagramScene;
  KINETIC_TEXT: KineticTextScene;
  STEP_FLOW: StepFlowScene;
  LIST_BUILD: ListBuildScene;
  RECAP: RecapScene;
  STAT_CALLOUT: StatCalloutScene;
  OUTRO_CTA: OutroCtaScene;
  QUOTE_SPOTLIGHT: QuoteSpotlightScene;
  STICKY_NOTE: StickyNoteScene;
  STAT_PANELS: StatPanelsScene;
  CHAT_MOCKUP: ChatMockupScene;
  SPLIT_PATHS: SplitPathsScene;
  BAR_COMPARE: BarCompareScene;
  NOTIFICATION: NotificationScene;
  FLIP_CARD: FlipCardScene;
  TIMELINE: TimelineScene;
  REVEAL: RevealScene;
  LOWER_THIRD: LowerThirdScene;
  CHAPTER: ChapterScene;
  COUNTDOWN: CountdownScene;
  CREDITS_ROLL: CreditsRollScene;
  SUBSCRIBE_REMINDER: SubscribeReminderScene;
  LINE_CHART: LineChartScene;
  DONUT: DonutScene;
  PROGRESS: ProgressScene;
  QUADRANT: QuadrantScene;
  FUNNEL: FunnelScene;
  WATERFALL: WaterfallScene;
  DIAGRAM: DiagramScene;
  PIPELINE: PipelineScene;
  LAYERED_STACK: LayeredStackScene;
  GRID_ARRAY: GridArrayScene;
  SPEC_COMPARE: SpecCompareScene;
  NEURAL_NET: NeuralNetScene;
  PICTOGRAM: PictogramScene;
  RADAR: RadarScene;
  CANDLESTICK: CandlestickScene;
  BOX_PLOT: BoxPlotScene;
  TREEMAP: TreemapScene;
  SANKEY: SankeyScene;
  ICON_GRID: IconGridScene;
  ICON_CALLOUT: IconCalloutScene;
  ICON_BURST: IconBurstScene;
  LOGO_WALL: LogoWallScene;
  LOGO_VERSUS: LogoVersusScene;
  LOGO_TIMELINE: LogoTimelineScene;
  CODE_WINDOW: CodeWindowScene;
  CODE_EDITOR: CodeEditorScene;
  TERMINAL_SESSION: TerminalSessionScene;
  LOG_STREAM: LogStreamScene;
  CODE_DIFF: CodeDiffScene;
  ERROR_TRACE: ErrorTraceScene;
  WINDOW_FRAME: WindowFrameScene;
  AUTOMATION_RUN: AutomationRunScene;
  DOM_INSPECT: DomInspectScene;
  NETWORK_WATERFALL: NetworkWaterfallScene;
  DEVICE_FRAME: DeviceFrameScene;
  CLOUD_ARCH: CloudArchScene;
  K8S_CLUSTER: K8sClusterScene;
  KERNEL_BOUNDARY: KernelBoundaryScene;
  COST_METER: CostMeterScene;
  SLO_GAUGE: SloGaugeScene;
  ERD: ErdScene;
  IAC_PLAN: IacPlanScene;
  AGENT_HARNESS: AgentHarnessScene;
  KNOWLEDGE_GRAPH: KnowledgeGraphScene;
  RETRIEVAL_RANK: RetrievalRankScene;
  MODEL_STAGES: ModelStagesScene;
  CONFIDENCE_GATE: ConfidenceGateScene;
  SANDBOX_BOX: SandboxBoxScene;
  FORMULA: FormulaScene;
  TRADEOFF_SCALE: TradeoffScaleScene;
  MOLECULE: MoleculeScene;
  DNA_HELIX: DnaHelixScene;
  LABELED_FIGURE: LabeledFigureScene;
  VECTOR_FIELD: VectorFieldScene;
  CIRCUIT_FLOW: CircuitFlowScene;
  BITS: BitsScene;
  MEMORY: MemoryScene;
  PACKET: PacketScene;
  NUMBER_BASE: NumberBaseScene;
  POINTER_DIAGRAM: PointerDiagramScene;
  ENCRYPTION: EncryptionScene;
  CALL_STACK: CallStackScene;
  QUEUE: QueueScene;
  BOOLEAN_LOGIC_GATES: BooleanLogicGatesScene;
  HASH_FUNCTION: HashFunctionScene;
  SORTING_VISUAL: SortingVisualScene;
  CLOCK_SIGNAL: ClockSignalScene;
  DATACENTER: DatacenterScene;
  TRANSFORMER_BLOCK: TransformerBlockScene;
  CACHE_PYRAMID: CachePyramidScene;
  GPU_CLUSTER: GpuClusterScene;
  ZOOM_SCALE: ZoomScaleScene;
  DIE_SHOT: DieShotScene;
  TOKENIZER: TokenizerScene;
  FILE_TREE: FileTreeScene;
  DATABASE_TABLE: DatabaseTableScene;
  GIT_BRANCH: GitBranchScene;
  STATE_MACHINE: StateMachineScene;
  EMBEDDING_SPACE: EmbeddingSpaceScene;
  API_REQUEST_RESPONSE: ApiRequestResponseScene;
  PROCESS_TABLE: ProcessTableScene;
  TEST_MATRIX: TestMatrixScene;
  TEST_RUNNER: TestRunnerScene;
  CONTEXT_METER: ContextMeterScene;
  DRILL_IN: DrillInScene;
  TICKER_TAPE: TickerTapeScene;
  MAP_RADAR: MapRadarScene;
  EVAL_DASHBOARD: EvalDashboardScene;
  CHANNEL_CARD: ChannelCardScene;
  PHOTO: PhotoScene;
  SOUND_WAVE: SoundWaveScene;
  LOGO_REVEAL: LogoRevealScene;
  CAROUSEL: CarouselScene;
  GALLERY: GalleryScene;
  COMPARISON_SLIDER: ComparisonSliderScene;
  PHOTO_STACK: PhotoStackScene;
  IMAGE_SCENE: ImageSceneScene;
  ACTIVITY_CARD: ActivityCardScene;
  LOCATION_MAP: LocationMapScene;
  VIDEO_HERO: VideoHeroScene;
  VIDEO_SPOTLIGHT: VideoSpotlightScene;
  MEDIA_CALLOUT: MediaCalloutScene;
  MEDIA_COMPARE: MediaCompareScene;
  MEDIA_STAT_OVERLAY: MediaStatOverlayScene;
  SCREENSHOT_CASCADE: ScreenshotCascadeScene;
  FLOATING_QUOTE_PILL: FloatingQuotePillScene;
  OVERLAY_SPLIT_DEFINITIONS: OverlaySplitDefinitionsScene;
  CYCLE_LOOP: CycleLoopScene;
  STEP_STACK_OVERLAY: StepStackOverlayScene;
  TITLE_BANNER_FOCUS: TitleBannerFocusScene;
  TALKING_POINTS: TalkingPointsScene;
  SLIDE_BULLETS_PIP: SlideBulletsPipScene;
  CAPTION_KINETIC_OVERLAY: CaptionKineticOverlayScene;
  PHOTO_TIMELINE: PhotoTimelineScene;
}

// A scene narrowed to one type: SceneOf<'BITS'> knows data.bits is present.
export type SceneOf<T extends SceneTypeName> = SceneByType[T];

// The full discriminated union (narrow on `.type`).
export type TypedScene =
  | ProductionGrindScene
  | SceneForgeScene
  | VideoPlayerScene
  | ChatTrioScene
  | PromptHandoutScene
  | AppWindowScene
  | CheckSweepScene
  | PromptHandoffScene
  | TopicIntakeScene
  | PipelineGateScene
  | AspectTwinScene
  | ReskinCarouselScene
  | WordAnchorRailScene
  | BudgetMeterRowScene
  | LabAssemblyScene
  | CastBoardScene
  | SpecToFrameScene
  | BatchSweepScene
  | PipelineGanttScene
  | HookScene
  | TitleCardScene
  | ConceptDiagramScene
  | KineticTextScene
  | StepFlowScene
  | ListBuildScene
  | RecapScene
  | StatCalloutScene
  | OutroCtaScene
  | QuoteSpotlightScene
  | StickyNoteScene
  | StatPanelsScene
  | ChatMockupScene
  | SplitPathsScene
  | BarCompareScene
  | NotificationScene
  | FlipCardScene
  | TimelineScene
  | RevealScene
  | LowerThirdScene
  | ChapterScene
  | CountdownScene
  | CreditsRollScene
  | SubscribeReminderScene
  | LineChartScene
  | DonutScene
  | ProgressScene
  | QuadrantScene
  | FunnelScene
  | WaterfallScene
  | DiagramScene
  | PipelineScene
  | LayeredStackScene
  | GridArrayScene
  | SpecCompareScene
  | NeuralNetScene
  | PictogramScene
  | RadarScene
  | CandlestickScene
  | BoxPlotScene
  | TreemapScene
  | SankeyScene
  | IconGridScene
  | IconCalloutScene
  | IconBurstScene
  | LogoWallScene
  | LogoVersusScene
  | LogoTimelineScene
  | CodeWindowScene
  | CodeEditorScene
  | TerminalSessionScene
  | LogStreamScene
  | CodeDiffScene
  | ErrorTraceScene
  | WindowFrameScene
  | AutomationRunScene
  | DomInspectScene
  | NetworkWaterfallScene
  | DeviceFrameScene
  | CloudArchScene
  | K8sClusterScene
  | KernelBoundaryScene
  | CostMeterScene
  | SloGaugeScene
  | ErdScene
  | IacPlanScene
  | AgentHarnessScene
  | KnowledgeGraphScene
  | RetrievalRankScene
  | ModelStagesScene
  | ConfidenceGateScene
  | SandboxBoxScene
  | FormulaScene
  | TradeoffScaleScene
  | MoleculeScene
  | DnaHelixScene
  | LabeledFigureScene
  | VectorFieldScene
  | CircuitFlowScene
  | BitsScene
  | MemoryScene
  | PacketScene
  | NumberBaseScene
  | PointerDiagramScene
  | EncryptionScene
  | CallStackScene
  | QueueScene
  | BooleanLogicGatesScene
  | HashFunctionScene
  | SortingVisualScene
  | ClockSignalScene
  | DatacenterScene
  | TransformerBlockScene
  | CachePyramidScene
  | GpuClusterScene
  | ZoomScaleScene
  | DieShotScene
  | TokenizerScene
  | FileTreeScene
  | DatabaseTableScene
  | GitBranchScene
  | StateMachineScene
  | EmbeddingSpaceScene
  | ApiRequestResponseScene
  | ProcessTableScene
  | TestMatrixScene
  | TestRunnerScene
  | ContextMeterScene
  | DrillInScene
  | TickerTapeScene
  | MapRadarScene
  | EvalDashboardScene
  | ChannelCardScene
  | PhotoScene
  | SoundWaveScene
  | LogoRevealScene
  | CarouselScene
  | GalleryScene
  | ComparisonSliderScene
  | PhotoStackScene
  | ImageSceneScene
  | ActivityCardScene
  | LocationMapScene
  | VideoHeroScene
  | VideoSpotlightScene
  | MediaCalloutScene
  | MediaCompareScene
  | MediaStatOverlayScene
  | ScreenshotCascadeScene
  | FloatingQuotePillScene
  | OverlaySplitDefinitionsScene
  | CycleLoopScene
  | StepStackOverlayScene
  | TitleBannerFocusScene
  | TalkingPointsScene
  | SlideBulletsPipScene
  | CaptionKineticOverlayScene
  | PhotoTimelineScene;
