import {VideoSpec, Scene} from './types';
import {TRANSITIONS} from './SceneTransition';
import galleryJson from '../specs/gallery.json';
import widgetsJson from '../specs/widgets.json';

// COMPONENT SHOWCASE — a single kitchen-sink spec that exercises the FULL scene
// library so each design's <design>-wide/-short composition plays through EVERY
// component in that design's grammar. Merges the two existing showcase specs
// (gallery = 16 types, widgets = media/UI types) and adds the dynamic types
// neither covers (DIAGRAM, KINETIC_TEXT, REVEAL, CAROUSEL, ACTIVITY_CARD,
// LOCATION_MAP, PHOTO, SOUND_WAVE, LOGO_REVEAL, CREDITS_ROLL, …). Every scene
// gets a different transition so transition variety shows too.
const gallery = galleryJson as unknown as VideoSpec;
const widgets = widgetsJson as unknown as VideoSpec;

const extra = [
  {id: 'x-batchsweep', type: 'BATCH_SWEEP', narration: "A batch sweep demo scene shows this component.", durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {batchSweep: {"atWord":4,"fast":{"color":"green","label":"Multi-select","stat":"12s"},"headline":"One at a time, or [all at once]","rows":7,"slow":{"color":"red","label":"Single-record modal","stat":"3h 20m"},"source":"illustrative"}}},
  {id: 'x-pipelinegantt', type: 'PIPELINE_GANTT', narration: "A pipeline gantt demo scene shows this component.", durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {pipelineGantt: {"atWord":3,"caption":"One instruction finishes every cycle","color":"blue","count":4,"headline":"Five stages, [overlapped]","source":"illustrative","stages":["IF","ID","EX","MEM","WB"]}}},
  {id: 'x-title', type: 'TITLE_CARD', narration: 'A title card opens the section, in this design.', durationFrames: 150, timingSource: 'estimated', background: 'zoneA', data: {title: 'Every Component', subtitle: 'in every design'}},
  {id: 'x-tradeoff', type: 'TRADEOFF_SCALE', narration: 'Every engineering choice is a tradeoff on a balance beam.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {tradeoff: {headline: 'Speed vs [safety]', left: {label: 'Move fast', sub: 'ship daily', asset: 'lucide:rabbit', color: 'orange'}, right: {label: 'Stay safe', sub: 'review everything', asset: 'lucide:shield', color: 'blue'}, lean: 0.4, caption: 'Every team picks a point on this beam', atWord: 6, source: 'illustrative'}}},
  {id: 'x-kt1', type: 'KINETIC_TEXT', narration: 'Kinetic text types itself out on the screen.', durationFrames: 150, timingSource: 'estimated', background: 'zoneB', data: {kinetic: {fx: 'typewriter', text: 'Predict the next token.', sub: 'kinetic typewriter', color: 'blue', atWord: 1}}},
  {id: 'x-kt2', type: 'KINETIC_TEXT', narration: 'Or it can pop in per character with a spring.', durationFrames: 140, timingSource: 'estimated', background: 'zoneC', data: {kinetic: {fx: 'pop', text: 'Pop, pop, pop!', sub: 'per-char spring', color: 'orange', atWord: 1}}},
  {id: 'x-kt3', type: 'KINETIC_TEXT', narration: 'Or glitch for a harder, cyber edge.', durationFrames: 140, timingSource: 'estimated', background: 'zoneA', data: {kinetic: {fx: 'glitch', text: 'Signal / noise', sub: 'rgb split', color: 'purple', atWord: 1}}},
  {id: 'x-diagram', type: 'DIAGRAM', narration: 'A flow diagram links ideas in order, step by step here.', durationFrames: 220, timingSource: 'estimated', background: 'zoneB', data: {headline: 'How it [flows]', headlineColor: 'blue', diagram: {layout: 'flow', nodes: [{id: 'a', label: 'Input', sub: 'your text', asset: 'lucide:type', color: 'blue', atWord: 1}, {id: 'b', label: 'Model', sub: 'compute', asset: 'lucide:cpu', color: 'purple', atWord: 4}, {id: 'c', label: 'Output', sub: 'tokens', asset: 'lucide:sparkles', color: 'green', atWord: 7}], edges: [{from: 'a', to: 'b', atWord: 3}, {from: 'b', to: 'c', atWord: 6}]}}},
  {id: 'x-concept', type: 'CONCEPT_DIAGRAM', narration: 'A concept map shows two related nodes and a link.', durationFrames: 180, timingSource: 'estimated', background: 'zoneC', data: {headline: 'Client and [server]', headlineColor: 'green', nodes: [{id: 'a', label: 'Client', asset: 'lucide:monitor', atWord: 1}, {id: 'b', label: 'Server', asset: 'lucide:server', atWord: 3}], edges: [{from: 'a', to: 'b', atWord: 2}]}},
  {id: 'x-bits', type: 'BITS', narration: 'Computers store everything as bits, ones and zeros.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {bits: {value: 210, bits: 8, label: 'one byte = 8 bits', color: 'green', atWord: 1}}},
  {id: 'x-memory', type: 'MEMORY', narration: 'Memory is numbered boxes, each holding one value here.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {memory: {label: 'Reading address 0x02', color: 'blue', highlight: 2, pointerLabel: 'ptr', cells: [{addr: '0x00', value: '42'}, {addr: '0x01', value: '7'}, {addr: '0x02', value: '99', color: 'blue'}, {addr: '0x03', value: '13'}, {addr: '0x04', value: '0'}, {addr: '0x05', value: '255'}], atWord: 1}}},
  {id: 'x-packet', type: 'PACKET', narration: 'Your request travels the network in hops to the server.', durationFrames: 240, timingSource: 'estimated', background: 'zoneC', data: {packet: {headline: 'How a request [travels]', packetLabel: 'GET /index.html', color: 'blue', hops: [{label: 'Your device', asset: 'lucide:laptop', color: 'blue'}, {label: 'Router', asset: 'lucide:router', color: 'purple'}, {label: 'ISP', asset: 'lucide:network', color: 'orange'}, {label: 'Server', asset: 'lucide:server', color: 'green'}], atWord: 1}}},
  {id: 'x-pipeline', type: 'PIPELINE', narration: 'A CPU runs every instruction through the same five stages.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {pipeline: {headline: 'The [instruction] pipeline', tokenLabel: 'instruction', color: 'blue', stages: [{label: 'Fetch', sub: 'read from cache', asset: 'lucide:download'}, {label: 'Decode', sub: 'read the opcode', asset: 'lucide:binary'}, {label: 'Execute', sub: 'run the ALU', asset: 'lucide:cpu'}, {label: 'Memory', sub: 'load / store', asset: 'lucide:database'}, {label: 'Write-back', sub: 'update register', asset: 'lucide:save'}], atWord: 1}}},
  {id: 'x-pipeline-ci', type: 'PIPELINE', narration: 'A CI run lints, builds, tests, then deploys.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {pipeline: {headline: 'The [CI/CD] run', variant: 'ci', color: 'blue', stages: [{label: 'Lint', status: 'pass', ms: '4.2 s'}, {label: 'Build', status: 'pass', ms: '38 s'}, {label: 'Unit tests', status: 'fail', ms: '12 s', reason: 'expected 200, got 500 on /health'}, {label: 'Deploy', status: 'pending', ms: '--'}], atWord: 1}}},
  {id: 'x-pipeline-boot', type: 'PIPELINE', narration: 'A machine boots firmware, kernel, then services.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {pipeline: {headline: 'The [boot] sequence', variant: 'boot', color: 'orange', stages: [{label: 'Firmware', ms: '120 ms', color: 'orange'}, {label: 'Bootloader', ms: '40 ms', color: 'orange'}, {label: 'Kernel', ms: '310 ms', color: 'blue'}, {label: 'Init', ms: '80 ms', color: 'blue'}, {label: 'Services', ms: '1.2 s', color: 'green'}], atWord: 1}}},
  {id: 'x-pipeline-serverless', type: 'PIPELINE', narration: 'An upload triggers a function, a queue, then a store.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {pipeline: {headline: 'An [event] chain', variant: 'serverless', tokenLabel: 'event', color: 'purple', stages: [{label: 'S3 upload', badge: 'trigger', asset: 'lucide:upload', color: 'green'}, {label: 'Lambda', badge: 'function', asset: 'lucide:zap', color: 'orange'}, {label: 'SQS', badge: 'queue', asset: 'lucide:layers', color: 'blue'}, {label: 'DynamoDB', badge: 'store', asset: 'lucide:database', color: 'purple'}], atWord: 1}}},
  {id: 'x-pipeline-journey', type: 'PIPELINE', narration: 'An end-to-end journey: login, search, cart, pay.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {pipeline: {headline: 'The [checkout] journey', variant: 'journey', color: 'green', tokenLabel: 'New user', stages: [{label: 'Login', badge: 'auth', status: 'pass'}, {label: 'Search', badge: 'search', status: 'pass'}, {label: 'Add to cart', badge: 'cart', status: 'pass'}, {label: 'Pay', badge: 'payments', status: 'fail', reason: 'gateway timeout after 30s'}], atWord: 1}}},
  {id: 'x-stack', type: 'LAYERED_STACK', narration: 'Every request travels down the network stack, layer by layer.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {stack: {headline: 'The [network] stack', signal: 'down', color: 'green', layers: [{label: 'Application', sub: 'HTTP · DNS · TLS', color: 'green'}, {label: 'Transport', sub: 'TCP · UDP', color: 'blue'}, {label: 'Network', sub: 'IP · routing', color: 'purple'}, {label: 'Link', sub: 'Ethernet · Wi-Fi', color: 'orange'}, {label: 'Physical', sub: 'bits on the wire', color: 'yellow'}], atWord: 1}}},
  {id: 'x-grid', type: 'GRID_ARRAY', narration: 'A GPU has thousands of cores that all compute at once.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {grid: {headline: 'Thousands of [cores] at once', rows: 8, cols: 12, mode: 'wave', label: 'Cores compute in a parallel sweep', legendA: 'active', legendB: 'idle', color: 'green', atWord: 1}}},
  {id: 'x-compare', type: 'SPEC_COMPARE', narration: 'How do the two flagship GPUs stack up head to head?', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {source: 'illustrative', compare: {headline: 'Flagship [GPUs] compared', a: {name: 'GeForce', color: 'green', asset: 'si:nvidia'}, b: {name: 'Radeon', color: 'red', asset: 'si:amd'}, rows: [{label: 'Shader cores', a: '16,384', b: '6,144', winner: 'a'}, {label: 'Memory', a: '24 GB', b: '20 GB', winner: 'a'}, {label: 'Bandwidth', a: '1 TB/s', b: '960 GB/s', winner: 'a'}, {label: 'Board power', a: '450 W', b: '355 W', winner: 'b'}], atWord: 1}}},
  {id: 'x-die', type: 'DIE_SHOT', narration: 'On an Apple Silicon die, every block has its place.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {die: {headline: 'Inside the [chip]', chipLabel: 'Apple M-series', cols: 4, rows: 4, color: 'blue', blocks: [{label: 'P-cores', sub: 'performance', x: 1, y: 1, w: 2, h: 1, color: 'blue'}, {label: 'E-cores', sub: 'efficiency', x: 1, y: 2, w: 2, h: 1, color: 'blue'}, {label: 'GPU', sub: 'cores', x: 3, y: 1, w: 2, h: 2, color: 'green'}, {label: 'Neural Engine', sub: '16 cores', x: 1, y: 3, w: 2, h: 1, color: 'purple'}, {label: 'System Cache', x: 3, y: 3, w: 2, h: 1, color: 'yellow'}, {label: 'Unified Memory', x: 1, y: 4, w: 4, h: 1, color: 'orange'}], atWord: 1}}},
  {id: 'x-net', type: 'NEURAL_NET', narration: 'A neural network passes signals forward through its layers.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {net: {headline: 'The [forward] pass', color: 'purple', layers: [3, 5, 5, 2], labels: ['Input', 'Hidden', 'Hidden', 'Output'], atWord: 1}}},
  {id: 'x-dchall', type: 'DATACENTER', narration: 'A data center routes traffic through racks under a spine.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {datacenter: {headline: 'Inside the [data center]', variant: 'hall', spineLabel: 'Spine · core switch', color: 'blue', highlight: 3, racks: [{label: 'Web'}, {label: 'App'}, {label: 'Cache'}, {label: 'Database', color: 'red'}], atWord: 1}}},
  {id: 'x-dcrack', type: 'DATACENTER', narration: 'Each rack stacks compute, GPUs, storage, and networking.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {datacenter: {headline: 'One [rack], unit by unit', variant: 'rack', rackLabel: 'Rack 07', color: 'blue', highlight: 1, units: [{label: 'Compute', sub: '16 servers', u: 2, color: 'blue'}, {label: 'GPU', sub: '8x H100', u: 2, color: 'green'}, {label: 'Storage', sub: '2 PB', u: 1, color: 'orange'}, {label: 'Network', sub: 'leaf switch', u: 1, color: 'purple'}, {label: 'Power', sub: 'dual PDU', u: 1, color: 'yellow'}], atWord: 1}}},
  {id: 'x-transformer', type: 'TRANSFORMER_BLOCK', narration: 'A transformer stacks attention and feed-forward blocks.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {transformer: {headline: 'The [transformer] block', color: 'purple', repeatFrom: 2, repeatTo: 5, repeatLabel: 'x 12', blocks: [{label: 'Tokens', kind: 'io'}, {label: 'Embeddings', kind: 'io'}, {label: 'Multi-Head Attention', kind: 'attn'}, {label: 'Add & Norm', kind: 'norm'}, {label: 'Feed Forward', kind: 'ffn'}, {label: 'Add & Norm', kind: 'norm'}, {label: 'Output logits', kind: 'io'}], atWord: 1}}},
  {id: 'x-pyramid', type: 'CACHE_PYRAMID', narration: 'Memory is a hierarchy, fast and small at the top.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {pyramid: {headline: 'The [memory] hierarchy', axisTop: 'faster · smaller', axisBottom: 'bigger · slower', tiers: [{label: 'Registers', speed: '~0.3 ns', size: '1 KB', color: 'red'}, {label: 'L1 cache', speed: '~1 ns', size: '64 KB', color: 'orange'}, {label: 'L2 cache', speed: '~4 ns', size: '512 KB', color: 'yellow'}, {label: 'L3 cache', speed: '~12 ns', size: '32 MB', color: 'green'}, {label: 'RAM', speed: '~80 ns', size: '32 GB', color: 'blue'}, {label: 'SSD', speed: '~100 us', size: '2 TB', color: 'purple'}], atWord: 1}}},
  {id: 'x-callstack', type: 'CALL_STACK', narration: 'Every function call pushes a frame onto the stack.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {callStack: {headline: 'The [call] stack', color: 'purple', frames: [{fn: 'main()', sub: 'program entry'}, {fn: 'parseFile(path)', sub: 'path = a.txt'}, {fn: 'tokenize(src)', sub: 'src = ...'}, {fn: 'readLine()', sub: 'line = 42', color: 'green'}], atWord: 1}}},
  {id: 'x-tokenizer', type: 'TOKENIZER', narration: 'A model reads text by splitting it into tokens with ids.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {tokenizer: {headline: 'How a model reads [text]', text: 'Tokens map to numbers.', showVectors: true, color: 'blue', tokens: [{text: 'Token', id: 15496}, {text: 's', id: 82}, {text: ' map', id: 3975}, {text: ' to', id: 284}, {text: ' numbers', id: 3146}, {text: '.', id: 13}], atWord: 1}}},
  {id: 'x-filetree', type: 'FILE_TREE', narration: 'A project is just folders and files in a tree.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {fileTree: {headline: 'Inside a [project]', color: 'orange', highlight: 4, nodes: [{name: 'my-app', depth: 0, kind: 'folder'}, {name: 'src', depth: 1, kind: 'folder'}, {name: 'index.ts', depth: 2, kind: 'file'}, {name: 'components', depth: 2, kind: 'folder'}, {name: 'Button.tsx', depth: 3, kind: 'file', color: 'orange'}, {name: 'package.json', depth: 1, kind: 'file'}, {name: 'README.md', depth: 1, kind: 'file'}], atWord: 1}}},
  {id: 'x-database', type: 'DATABASE_TABLE', narration: 'A query scans the table and returns matching rows.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {database: {headline: 'How a [query] runs', tableName: 'users', query: 'WHERE active = true', color: 'green', columns: ['id', 'name', 'active'], rows: [['1', 'Ada', 'true'], ['2', 'Linus', 'false'], ['3', 'Grace', 'true'], ['4', 'Alan', 'false'], ['5', 'Katherine', 'true']], highlight: [0, 2, 4], atWord: 1}}},
  {id: 'x-git', type: 'GIT_BRANCH', narration: 'A feature branch diverges from main and merges back.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {git: {headline: 'A [branch] and merge', color: 'blue', lanes: ['main', 'feature'], commits: [{lane: 0, label: 'init'}, {lane: 0, label: 'setup'}, {lane: 1, label: 'feat A'}, {lane: 1, label: 'feat B'}, {lane: 0, label: 'merge'}], links: [{from: 1, to: 2}, {from: 3, to: 4}], atWord: 1}}},
  {id: 'x-fsm', type: 'STATE_MACHINE', narration: 'A traffic light is a simple finite state machine.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {stateMachine: {headline: 'A finite [state] machine', color: 'green', active: 1, states: [{label: 'Red', color: 'red'}, {label: 'Green', color: 'green'}, {label: 'Yellow', color: 'yellow'}], transitions: [{from: 0, to: 1, label: 'go'}, {from: 1, to: 2, label: 'caution'}, {from: 2, to: 0, label: 'stop'}], atWord: 1}}},
  {id: 'x-embedding', type: 'EMBEDDING_SPACE', narration: 'In embedding space, similar words cluster together.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {embedding: {headline: 'Meaning as [coordinates]', color: 'blue', axisX: 'dimension 1', axisY: 'dimension 2', clusters: ['animals', 'royalty', 'tech'], points: [{label: 'cat', x: 0.18, y: 0.72, cluster: 0}, {label: 'dog', x: 0.26, y: 0.8, cluster: 0}, {label: 'wolf', x: 0.14, y: 0.62, cluster: 0}, {label: 'king', x: 0.7, y: 0.78, cluster: 1}, {label: 'queen', x: 0.78, y: 0.7, cluster: 1}, {label: 'throne', x: 0.66, y: 0.86, cluster: 1}, {label: 'gpu', x: 0.5, y: 0.2, cluster: 2}, {label: 'server', x: 0.6, y: 0.28, cluster: 2}, {label: 'chip', x: 0.44, y: 0.14, cluster: 2}], atWord: 1}}},
  {id: 'x-queue', type: 'QUEUE', narration: 'A queue is first in, first out.', durationFrames: 190, timingSource: 'estimated', background: 'zoneC', data: {queue: {headline: 'First in, [first out]', color: 'purple', items: [{label: 'A'}, {label: 'B'}, {label: 'C'}, {label: 'D'}, {label: 'E'}], atWord: 1}}},
  {id: 'x-api', type: 'API_REQUEST_RESPONSE', narration: 'The client asks, the server answers.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {api: {headline: 'One [HTTP] round trip', color: 'blue', method: 'GET', path: '/api/users/42', requestLines: ['Accept: application/json'], status: '200', statusText: 'OK', responseLines: ['{ "id": 42,', '  "name": "Ada" }'], atWord: 1}}},
  {id: 'x-logic', type: 'BOOLEAN_LOGIC_GATES', narration: 'Logic gates turn ones and zeros into decisions.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {logic: {headline: 'The [logic] gates', color: 'blue', gates: [{type: 'AND', a: 1, b: 1}, {type: 'OR', a: 1, b: 0}, {type: 'XOR', a: 1, b: 1}, {type: 'NOT', a: 0}]}}},
  {id: 'x-hash', type: 'HASH_FUNCTION', narration: 'A hash turns any input into a fixed fingerprint.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {hash: {headline: 'A one-way [fingerprint]', color: 'blue', input: 'hello', algo: 'SHA-256', digest: '2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824'}}},
  {id: 'x-sort', type: 'SORTING_VISUAL', narration: 'A sorting algorithm puts the bars in order.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {sort: {headline: 'Putting it [in order]', color: 'blue', label: 'sorted', values: [7, 2, 9, 4, 1, 6, 3, 8, 5]}}},
  {id: 'x-clock', type: 'CLOCK_SIGNAL', narration: 'A clock signal is the heartbeat of every chip.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {clock: {headline: 'The [clock] that drives it all', color: 'purple', cycles: 5, label: 'clock ticks'}}},
  {id: 'x-gpucluster', type: 'GPU_CLUSTER', narration: 'Frontier models train on thousands of GPUs at once.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {gpuCluster: {headline: 'A training [cluster]', color: 'green', nodes: 4, gpusPerNode: 8, interconnect: 'NVLink · InfiniBand', totalLabel: 'GPUs training together'}}},
  {id: 'x-zoom', type: 'ZOOM_SCALE', narration: 'Zoom out from a transistor all the way to a data center.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {zoomScale: {headline: 'From [transistor] to data center', color: 'blue', levels: [{label: 'Transistor', sub: 'a switch', asset: 'lucide:toggle-left', scale: '5 nm', color: 'blue'}, {label: 'Core', sub: 'billions', asset: 'lucide:cpu', scale: '1 mm', color: 'purple'}, {label: 'Chip', sub: 'the SoC', asset: 'lucide:square-stack', scale: '1 cm', color: 'green'}, {label: 'Board', sub: 'a server', asset: 'lucide:server', scale: '0.5 m', color: 'orange'}, {label: 'Rack', sub: 'many servers', asset: 'lucide:columns-3', scale: '2 m', color: 'yellow'}, {label: 'Data center', sub: 'the cloud', asset: 'lucide:building-2', scale: '100 m', color: 'red'}]}}},
  {id: 'x-encryption', type: 'ENCRYPTION', narration: 'A key locks your message into unreadable ciphertext.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {encryption: {headline: 'Locking it with a [key]', color: 'purple', mode: 'encrypt', plaintext: 'hello world', ciphertext: 'U2FsdGVkX1+9dQ==', keyLabel: 'secret key'}}},
  {id: 'x-pointers', type: 'POINTER_DIAGRAM', narration: 'A linked list chains nodes together with pointers.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {pointers: {headline: 'A [linked] list', color: 'blue', headLabel: 'head', nodes: [{value: '12', next: 1, color: 'blue'}, {value: '99', next: 2, color: 'purple'}, {value: '7', next: 3, color: 'green'}, {value: '42', next: null, color: 'orange'}]}}},
  {id: 'x-numberbase', type: 'NUMBER_BASE', narration: 'The same number, in decimal, hex, and binary.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {numberBase: {headline: 'One number, three [bases]', color: 'green', value: 2026, label: 'the year'}}},
  {id: 'x-editor', type: 'CODE_EDITOR', narration: 'Code lives in an editor with tabs and a highlight.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {editor: {headline: 'Inside the [editor]', color: 'blue', lang: 'tsx', tabs: [{name: 'App.tsx', active: true}, {name: 'index.ts'}], lines: ["import React from 'react'", 'function App() {', '  const [n, setN] = useState(0)', '  const inc = () => setN(n + 1)', '  return <button onClick={inc}/>', '}'], highlight: {from: 3, to: 4, color: 'blue'}, squiggle: {line: 5, message: 'missing key prop'}, atWord: 1}}},
  {id: 'x-editor-split', type: 'CODE_EDITOR', narration: 'The split view runs the code beside the editor.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {editor: {headline: 'Run it in the [split] view', variant: 'split', color: 'blue', tabs: [{name: 'server.js', active: true}], lines: ["const app = express()", "app.get('/', (req, res) => {", "  res.send('hello')", '})', 'app.listen(3000)'], highlight: {from: 2, to: 3}, terminal: {promptLabel: 'node', cmd: 'node server.js', output: ['Server on :3000']}, atWord: 1}}},
  {id: 'x-terminal', type: 'TERMINAL_SESSION', narration: 'A command runs and its output streams back.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {terminal: {headline: 'Ship it from the [terminal]', color: 'green', promptLabel: 'root@prod', cwd: '~/app', commands: [{cmd: 'docker build -t app .', output: ['Step 1/3 : FROM node:20', 'Successfully built a1b2c3d4'], exitCode: 0}, {cmd: 'curl -sf localhost/health', output: ['{ "status": "ok" }'], exitCode: 0}], atWord: 1}}},
  {id: 'x-logs', type: 'LOG_STREAM', narration: 'Logs stream, and one error line pins and glows.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {logs: {headline: 'Reading the [logs]', color: 'blue', rate: '1.2k/s', highlight: 4, lines: [{level: 'info', tag: 'http', text: 'GET /api/users 200 in 12ms'}, {level: 'debug', tag: 'cache', text: 'hit user:42'}, {level: 'warn', tag: 'pool', text: 'connection pool at 80%'}, {level: 'debug', tag: 'vector', text: 'ANN search 30 candidates'}, {level: 'error', tag: 'payments', text: 'gateway timeout after 30s'}, {level: 'info', tag: 'retry', text: 'retrying in 2s'}, {level: 'info', tag: 'http', text: 'GET /health 200 in 2ms'}]}}},
  {id: 'x-diff', type: 'CODE_DIFF', narration: 'A pull request diff, deletions then additions.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {diff: {headline: 'Review the [diff]', color: 'blue', fileName: 'src/auth.ts', stat: {plus: 3, minus: 2}, rows: [{kind: 'ctx', text: 'export function login(user) {'}, {kind: 'del', text: '  return sign(user)'}, {kind: 'add', text: '  if (!user) throw new Error(401)'}, {kind: 'add', text: '  return sign(user, KEY)'}, {kind: 'add', text: '  // now with a secret key'}, {kind: 'del', text: '// TODO: refresh token'}, {kind: 'ctx', text: '}'}]}}},
  {id: 'x-errortrace', type: 'ERROR_TRACE', narration: 'A stack trace points to the frame that raised.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {callStack: {headline: 'The [stack] trace', color: 'red', exception: 'TypeError: user is not a function', culprit: 2, frames: [{fn: 'main', file: 'app.js', line: 12}, {fn: 'handleRequest', file: 'server.js', line: 88}, {fn: 'authenticate', file: 'auth.js', line: 45}, {fn: 'getUser', file: 'db.js', line: 23}, {fn: 'query', file: 'pg.js', line: 301}]}}},
  {id: 'x-window', type: 'WINDOW_FRAME', narration: 'A browser window shows a form and its devtools.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {window: {headline: 'Inside a [browser]', variant: 'browser', url: 'https://app.example.com/settings/billing/checkout', color: 'blue', content: {kind: 'form', fields: [{label: 'Email', value: 'ada@example.io'}, {label: 'Password', value: 'hunter2', focus: true}], submit: 'Sign in'}, devtools: {open: true, panel: 'console', logs: [{level: 'info', tag: 'auth', text: 'POST /login 200 in 40ms'}, {level: 'error', tag: 'api', text: '429 too many requests'}], atWord: 3}, atWord: 1}}},
  {id: 'x-window-mac', type: 'WINDOW_FRAME', narration: 'A desktop window can hold one big metric.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {window: {headline: 'A [desktop] window', variant: 'mac', title: 'Dashboard', color: 'green', content: {kind: 'metric', value: '1.2M', label: 'active users', trend: '+12%'}}}},
  {id: 'x-automation', type: 'AUTOMATION_RUN', narration: 'A Playwright test clicks, types, and asserts.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {auto: {headline: 'The [automated] test', url: 'https://shop.example.com/cart', runner: 'playwright', color: 'purple', content: {kind: 'form', fields: [{label: 'Card number', value: '4242 4242'}, {label: 'CVC', focus: true}], submit: 'Pay now'}, steps: [{action: 'goto', target: '/cart'}, {action: 'click', target: '#checkout', status: 'pass'}, {action: 'type', target: '#card', value: '4242', status: 'pass'}, {action: 'assert', target: 'success page', status: 'fail', reason: 'expected /success, got /error'}], atWord: 1}}},
  {id: 'x-dominspect', type: 'DOM_INSPECT', narration: 'Inspecting the DOM highlights the element on the page.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {dom: {headline: 'Inspecting the [DOM]', color: 'blue', selector: 'main > .card:nth-child(2) button.primary', highlight: 3, nodes: [{tag: 'body', depth: 0}, {tag: 'main', attr: 'class=app', depth: 1}, {tag: 'div', attr: 'class=card', depth: 2}, {tag: 'button', attr: 'class=primary', depth: 3}, {tag: 'span', depth: 4}]}}},
  {id: 'x-waterfall', type: 'NETWORK_WATERFALL', narration: 'The network panel shows where requests spend time.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {waterfall: {headline: 'The [network] waterfall', color: 'blue', totalMs: 842, requests: [{name: 'document', phases: [{phase: 'blocked', ms: 8}, {phase: 'dns', ms: 12}, {phase: 'connect', ms: 30}, {phase: 'ttfb', ms: 120}, {phase: 'download', ms: 40}], status: '200'}, {name: 'app.js', phases: [{phase: 'queue', ms: 10}, {phase: 'ttfb', ms: 60}, {phase: 'download', ms: 180}], status: '200'}, {name: 'api/user', phases: [{phase: 'blocked', ms: 5}, {phase: 'connect', ms: 20}, {phase: 'ttfb', ms: 300}, {phase: 'download', ms: 20}], status: '200'}, {name: 'track.js', phases: [{phase: 'blocked', ms: 60}, {phase: 'ttfb', ms: 200}, {phase: 'download', ms: 20}], status: '500'}]}}},
  {id: 'x-device', type: 'DEVICE_FRAME', narration: 'On mobile, a notification drops from the top.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {device: {headline: 'On the [phone]', os: 'ios', color: 'blue', content: {kind: 'cardGrid', cards: [{title: 'Inbox', sub: '3 new', asset: 'lucide:mail', color: 'blue'}, {title: 'Calendar', sub: '2 events', asset: 'lucide:calendar', color: 'green'}, {title: 'Tasks', sub: '5 due', asset: 'lucide:square-check', color: 'orange'}]}, notification: {app: 'Messages', text: 'Ada sent you a photo', atWord: 4}}}},
  {id: 'x-cloud', type: 'CLOUD_ARCH', narration: 'A cloud region nests a VPC and subnets around your services.', durationFrames: 220, timingSource: 'estimated', background: 'zoneB', data: {cloud: {headline: 'Inside a [cloud region]', provider: 'aws', color: 'blue', atWord: 1, boundaries: [{id: 'reg', label: 'us-east-1', kind: 'region', atWord: 1}, {id: 'vpc', label: 'vpc-prod', kind: 'vpc', parent: 'reg', atWord: 2}, {id: 'sn', label: 'subnet-private', kind: 'subnet', parent: 'vpc', atWord: 3}], nodes: [{id: 'alb', label: 'Load Balancer', asset: 'lucide:network', boundary: 'vpc', color: 'blue', atWord: 3}, {id: 'api', label: 'API service', asset: 'lucide:server', boundary: 'sn', color: 'green', atWord: 4}, {id: 'db', label: 'Postgres', sub: 'arn:aws:rds:db-prod', asset: 'lucide:database', boundary: 'sn', color: 'purple', atWord: 5}], edges: [{from: 'alb', to: 'api', label: 'REST', atWord: 4}, {from: 'api', to: 'db', atWord: 5}]}}},
  {id: 'x-k8s', type: 'K8S_CLUSTER', narration: 'A rolling update swaps pods from one version to the next with no downtime.', durationFrames: 220, timingSource: 'estimated', background: 'zoneC', data: {k8s: {headline: 'A zero-downtime [rollout]', mode: 'rollout', controlPlane: 'kube-apiserver', color: 'green', atWord: 1, nodes: [{label: 'node-1', pods: [{version: 'v1'}, {version: 'v1'}, {version: 'v1'}], atWord: 1}, {label: 'node-2', pods: [{version: 'v1'}, {version: 'v1'}], atWord: 1}]}}},
  {id: 'x-cost', type: 'COST_METER', narration: 'This month the cloud bill blew past the budget.', durationFrames: 190, timingSource: 'estimated', background: 'zoneA', data: {cost: {headline: 'Are we [over budget]?', value: 1420, budget: 1200, unit: '$', period: 'this month', color: 'yellow', atWord: 1}}},
  {id: 'x-slo', type: 'SLO_GAUGE', narration: 'Availability sits at three and a half nines, inside the error budget.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {slo: {headline: 'Meeting the [SLO]', availability: 99.95, target: 99.9, budgetSpent: 0.62, period: '30-day window', color: 'green', atWord: 1}}},
  {id: 'x-iac', type: 'IAC_PLAN', narration: 'The plan shows what will be added, changed and destroyed.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {iac: {headline: 'The [terraform plan]', color: 'orange', atWord: 1, rows: [{action: 'add', resource: 'aws_s3_bucket.assets', type: 's3', atWord: 2}, {action: 'change', resource: 'aws_iam_role.exec', type: 'iam', atWord: 3}, {action: 'destroy', resource: 'aws_instance.legacy_worker', type: 'ec2', atWord: 4}]}}},
  {id: 'x-erd', type: 'ERD', narration: 'Users place orders that each contain products.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {erd: {headline: 'The [database schema]', color: 'blue', atWord: 1, tables: [{id: 'users', name: 'users', color: 'blue', atWord: 1, columns: [{name: 'id', type: 'uuid', key: 'pk'}, {name: 'email', type: 'text'}]}, {id: 'orders', name: 'orders', color: 'green', atWord: 2, columns: [{name: 'id', type: 'uuid', key: 'pk'}, {name: 'user_id', type: 'uuid', key: 'fk'}, {name: 'total', type: 'numeric'}]}], relations: [{from: 'users', to: 'orders', label: 'places', fromCard: '1', toCard: 'N', atWord: 2}]}}},
  {id: 'x-imagelayers', type: 'LAYERED_STACK', narration: 'A Docker image builds in layers, unchanged ones served from cache.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {stack: {headline: 'The [image] build cache', variant: 'imageLayers', totalSize: '248 MB', color: 'blue', atWord: 1, layers: [{label: 'FROM node:20-alpine', size: '142 MB', cached: true}, {label: 'RUN npm ci', size: '98 MB', cached: true}, {label: 'COPY . .', size: '6 MB', rebuilt: true}, {label: 'CMD npm start', size: '0 B'}]}}},
  {id: 'x-container', type: 'PACKET', narration: 'The built image travels from Dockerfile to registry to host.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {packet: {headline: "An image's [journey]", variant: 'container', packetLabel: 'myapp:1.2', color: 'blue', atWord: 1, hops: [{label: 'Dockerfile', asset: 'lucide:file-code', color: 'blue'}, {label: 'Registry', asset: 'lucide:box', color: 'purple'}, {label: 'Host', asset: 'lucide:server', color: 'green'}], hopStatuses: ['done', 'done', 'running']}}},
  {id: 'x-servicemesh', type: 'DIAGRAM', narration: 'In a service mesh a sidecar proxy sits beside every service.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {headline: 'The [service mesh]', headlineColor: 'purple', diagram: {layout: 'flow', direction: 'horizontal', variant: 'mesh', meshLabel: 'p99 42ms', nodes: [{id: 'gw', label: 'Gateway', asset: 'lucide:network', color: 'blue', atWord: 1}, {id: 'svcA', label: 'Orders', asset: 'lucide:box', color: 'green', atWord: 2}, {id: 'svcB', label: 'Payments', asset: 'lucide:credit-card', color: 'purple', atWord: 3}], edges: [{from: 'gw', to: 'svcA', atWord: 2}, {from: 'svcA', to: 'svcB', atWord: 3}]}}},
  {id: 'x-proctable', type: 'PROCESS_TABLE', narration: 'The process table lists what is running; one runaway eats the CPU.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {proc: {headline: 'The [process] table', sortBy: 'cpu', color: 'blue', atWord: 1, rows: [{pid: '3390', name: 'ffmpeg', cpu: 96, mem: 41, runaway: true, atWord: 8}, {pid: '842', name: 'chrome', cpu: 22, mem: 34}, {pid: '1203', name: 'node', cpu: 14, mem: 12}, {pid: '2517', name: 'postgres', cpu: 8, mem: 20}, {pid: '1', name: 'systemd', cpu: 1, mem: 2}]}}},
  {id: 'x-kernel', type: 'KERNEL_BOUNDARY', narration: 'A read call crosses from user space into the kernel and returns bytes.', durationFrames: 220, timingSource: 'estimated', background: 'zoneC', data: {kernel: {headline: 'Crossing the [kernel] boundary', userLabel: 'User space', kernelLabel: 'Kernel', syscall: 'read()', result: 'bytes', userChips: ['your app'], color: 'purple', atWord: 1, steps: [{label: 'check perms', atWord: 6}, {label: 'read disk', atWord: 9}, {label: 'copy to buffer', atWord: 12}]}}},
  {id: 'x-permbits', type: 'BITS', narration: 'File permissions are nine bits: read, write, execute for owner, group, other.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {bits: {variant: 'permissions', perms: 'rwxr-xr-x', path: '/usr/local/bin/deploy.sh', label: 'chmod 755', color: 'green', atWord: 1}}},
  {id: 'x-testrunner', type: 'TEST_RUNNER', narration: 'The runner walks the spec tree; one test fails on the actual result.', durationFrames: 220, timingSource: 'estimated', background: 'zoneB', data: {testRunner: {headline: 'The [test] runner', color: 'green', atWord: 1, passed: 3, failed: 1, failIndex: 3, expected: 'account locked', actual: 'still active', nodes: [{name: 'auth', depth: 0, kind: 'describe'}, {name: 'logs in with valid creds', depth: 1, kind: 'it', status: 'pass', ms: '12ms'}, {name: 'rejects a bad password', depth: 1, kind: 'it', status: 'pass', ms: '8ms'}, {name: 'locks after five tries', depth: 1, kind: 'it', status: 'fail', ms: '31ms'}, {name: 'adds an item', depth: 1, kind: 'it', status: 'pass', ms: '5ms'}]}}},
  {id: 'x-testmatrix', type: 'TEST_MATRIX', narration: 'The matrix runs every browser against every flow; one cell is flaky.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {testMatrix: {headline: 'The [compatibility] matrix', color: 'blue', atWord: 1, emphasize: {r: 1, c: 1}, rows: ['Chrome', 'Firefox', 'Safari'], cols: ['Login', 'Cart', 'Pay'], cells: [{r: 0, c: 0, status: 'pass'}, {r: 0, c: 1, status: 'pass'}, {r: 0, c: 2, status: 'pass'}, {r: 1, c: 0, status: 'pass'}, {r: 1, c: 1, status: 'flaky'}, {r: 1, c: 2, status: 'pass'}, {r: 2, c: 0, status: 'pass'}, {r: 2, c: 1, status: 'pass'}, {r: 2, c: 2, status: 'fail'}]}}},
  {id: 'x-testpyramid', type: 'CACHE_PYRAMID', narration: 'The test pyramid: many fast unit tests, few slow end-to-end ones.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {pyramid: {headline: 'The [test] pyramid', variant: 'pyramid', color: 'green', atWord: 1, axisTop: 'few, slow', axisBottom: 'many, fast', tiers: [{label: 'E2E', stat: 'slow · costly', color: 'orange'}, {label: 'Integration', stat: 'medium', color: 'yellow'}, {label: 'Unit', stat: 'fast · cheap', color: 'green'}]}}},
  {id: 'x-buglife', type: 'STATE_MACHINE', narration: 'A bug goes new, triaged, in progress, fixed, verified, closed — unless it reopens.', durationFrames: 230, timingSource: 'estimated', background: 'zoneC', data: {stateMachine: {headline: "A [bug's] lifecycle", variant: 'lifecycle', color: 'orange', atWord: 1, states: [{label: 'New', atWord: 1}, {label: 'Triaged', atWord: 2}, {label: 'In Progress', atWord: 3, color: 'blue'}, {label: 'Fixed', atWord: 5}, {label: 'Verified', atWord: 6}, {label: 'Closed', atWord: 12}], transitions: [{from: 0, to: 1}, {from: 1, to: 2}, {from: 2, to: 3}, {from: 3, to: 4}, {from: 4, to: 5}, {from: 4, to: 2, dashed: true, color: 'orange', label: 'reopen'}]}}},
  {id: 'x-context', type: 'CONTEXT_METER', narration: 'The context window is shared between system, tools, history and free space.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {context: {headline: 'The [context] window', atWord: 1, windowTokens: 128000, verdict: '92k / 128k tokens used', segments: [{label: 'system', tokens: 4000, kind: 'system'}, {label: 'tools', tokens: 12000, kind: 'tools'}, {label: 'history', tokens: 76000, kind: 'history'}, {label: 'free', tokens: 36000, kind: 'free'}]}}},
  {id: 'x-harness', type: 'AGENT_HARNESS', narration: 'An agent sits inside rings of capability; a dangerous action bounces off the guardrail.', durationFrames: 230, timingSource: 'estimated', background: 'zoneB', data: {harness: {headline: 'The [agent] harness', agent: 'LLM core', color: 'blue', atWord: 1, rings: [{label: 'Information', chips: ['retrieval', 'memory']}, {label: 'Execution', chips: ['tools', 'code']}, {label: 'Feedback', chips: ['eval', 'guardrails']}], guardrail: {label: 'rm -rf /', ring: 1, reason: 'blocked by policy'}}}},
  {id: 'x-kg', type: 'KNOWLEDGE_GRAPH', narration: 'A knowledge graph links entities, classes and literals with a query path.', durationFrames: 220, timingSource: 'estimated', background: 'zoneC', data: {kg: {headline: 'A [knowledge] graph', color: 'blue', atWord: 1, seed: 3, queryPath: ['ada', 'analytical', 'cs'], nodes: [{id: 'ada', label: 'Ada', kind: 'entity', atWord: 1}, {id: 'person', label: 'Person', kind: 'class', atWord: 2}, {id: 'london', label: 'London', kind: 'entity', atWord: 3}, {id: '1815', label: '1815', kind: 'literal', atWord: 4}, {id: 'analytical', label: 'Analytical Engine', kind: 'entity', atWord: 5}, {id: 'cs', label: 'Computing', kind: 'class', atWord: 6}], edges: [{from: 'ada', to: 'person', label: 'is a', atWord: 2}, {from: 'ada', to: 'london', label: 'born in', atWord: 3}, {from: 'ada', to: '1815', label: 'born', atWord: 4}, {from: 'ada', to: 'analytical', label: 'worked on', atWord: 5}, {from: 'analytical', to: 'cs', label: 'field', atWord: 6}]}}},
  {id: 'x-retrieval', type: 'RETRIEVAL_RANK', narration: 'Retrieval pulls chunks, a reranker reorders them, hybrid search fuses the scores.', durationFrames: 230, timingSource: 'estimated', background: 'zoneA', data: {retrieval: {headline: '[Retrieve], then rerank', color: 'blue', atWord: 1, rerankAtWord: 5, fuseAtWord: 9, chunks: [{label: 'Doc A: pricing tiers', scoreA: 0.72, scoreFinal: 0.91, vec: 0.68, bm25: 0.80}, {label: 'Doc B: refund policy', scoreA: 0.81, scoreFinal: 0.62, vec: 0.55, bm25: 0.70}, {label: 'Doc C: SLA terms', scoreA: 0.64, scoreFinal: 0.78, vec: 0.72, bm25: 0.60}]}}},
  {id: 'x-modelstages', type: 'MODEL_STAGES', narration: 'The same prompt gets a different answer at each training stage.', durationFrames: 220, timingSource: 'estimated', background: 'zoneB', data: {modelStages: {headline: 'Same [prompt], different training', prompt: 'Write a haiku about the sea.', color: 'purple', atWord: 1, stages: [{label: 'Pre-train', method: 'raw', reply: 'and the sea and the sea and the sea', atWord: 1}, {label: 'SFT', method: 'supervised', reply: 'Blue waves meet the shore at quiet dawn', atWord: 3}, {label: 'RLHF', method: 'aligned', reply: 'Of course — here is your sea haiku:', atWord: 5}]}}},
  {id: 'x-confidence', type: 'CONFIDENCE_GATE', narration: 'A confidence gate stops the agent when certainty stays below the threshold.', durationFrames: 200, timingSource: 'estimated', background: 'zoneC', data: {confidence: {headline: 'The [confidence] gate', value: 41, threshold: 70, mode: 'block', reason: 'insufficient evidence', style: 'linear', color: 'red', atWord: 1}}},
  {id: 'x-sandbox', type: 'SANDBOX_BOX', narration: 'In a sandbox, safe calls pass while dangerous ones bounce off.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {sandbox: {headline: 'Inside the [sandbox]', label: 'sandbox', color: 'orange', atWord: 1, allowed: ['read file', 'fetch API'], blocked: ['rm -rf /', 'spawn shell']}}},
  {id: 'x-drillin', type: 'DRILL_IN', narration: 'Zoom into the API service and its internal layers appear.', durationFrames: 240, timingSource: 'estimated', background: 'zoneB', data: {drillIn: {headline: '[Drill] into the API', color: 'blue', focusId: 'API', pushAtWord: 5, atWord: 1, overview: {layout: 'flow', direction: 'horizontal', nodes: [{id: 'client', label: 'Client', asset: 'lucide:monitor', atWord: 1}, {id: 'api', label: 'API', asset: 'lucide:server', color: 'blue', atWord: 2}, {id: 'db', label: 'Database', asset: 'lucide:database', atWord: 3}], edges: [{from: 'client', to: 'api', atWord: 2}, {from: 'api', to: 'db', atWord: 3}]}, detail: {layout: 'flow', direction: 'horizontal', nodes: [{id: 'router', label: 'Router', atWord: 1}, {id: 'auth', label: 'Auth', color: 'purple', atWord: 1}, {id: 'handler', label: 'Handler', color: 'green', atWord: 1}, {id: 'orm', label: 'ORM', atWord: 1}], edges: [{from: 'router', to: 'auth', atWord: 1}, {from: 'auth', to: 'handler', atWord: 1}, {from: 'handler', to: 'orm', atWord: 1}]}}}},
  {id: 'x-eval', type: 'EVAL_DASHBOARD', narration: 'An eval dashboard tracks quality metrics; one is quietly degrading.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {evalDash: {headline: 'The [eval] dashboard', atWord: 1, metrics: [{label: 'Accuracy', value: 94, target: 90, unit: '%', color: 'green'}, {label: 'Faithfulness', value: 88, target: 85, unit: '%', color: 'blue'}, {label: 'Latency p95', value: 72, target: 80, degrading: true}, {label: 'Cost score', value: 63, target: 70, color: 'purple'}]}}},
  {id: 'x-videohero', type: 'VIDEO_HERO', narration: 'A full-bleed clip carries the headline in a legibility band.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {videoHero: {src: 'assets/video/demo_ui.mp4', kicker: 'DEMO', headline: 'The product, [in motion]', sub: 'a full-bleed clip with a disciplined headline band', color: 'orange', treatment: 'scrim', zoom: true, atWord: 3}}},
  {id: 'x-videospotlight', type: 'VIDEO_SPOTLIGHT', narration: 'A framed clip spotlights a guest with a name and role below.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {videoSpotlight: {src: 'assets/video/demo_webcam.mp4', kicker: 'GUEST', name: 'The Spotlight', role: 'framed clip + name + italic role', color: 'red', atWord: 1}}},
  {id: 'x-mediacallout', type: 'MEDIA_CALLOUT', narration: 'Callout pins track fixed regions of a clip or screenshot.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {mediaCallout: {src: 'assets/video/demo_ui.mp4', headline: 'Point at [the details]', color: 'orange', treatment: 'scrim', callouts: [{x: 0.28, y: 0.34, label: 'the control', color: 'orange', side: 'left', atWord: 2}, {x: 0.7, y: 0.6, label: 'the readout', color: 'blue', side: 'right', hw: 0.22, hh: 0.12, atWord: 5}]}}},
  {id: 'x-mediacompare', type: 'MEDIA_COMPARE', narration: 'Two clips compare side by side with a versus badge.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {mediaCompare: {headline: 'Before vs [after]', color: 'orange', vs: true, atWord: 1, a: {src: 'assets/video/demo_grid.mp4', label: 'Before', caption: 'the old flow', color: 'blue'}, b: {src: 'assets/video/demo_flow.mp4', label: 'After', caption: 'the new flow', color: 'green'}}}},
  {id: 'x-mediastat', type: 'MEDIA_STAT_OVERLAY', narration: 'A hero number lands over the footage in a glass card.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {mediaStat: {src: 'assets/video/demo_flow.mp4', headline: 'The numbers [that matter]', color: 'orange', stats: [{value: 1500000000, label: 'requests / day', color: 'orange', atWord: 1}, {value: 99, suffix: '%', label: 'uptime', color: 'green', atWord: 3}]}}},
  {id: 'x-videodevice', type: 'DEVICE_FRAME', narration: 'A live app demo plays inside the phone screen.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {device: {headline: 'The [app] in motion', os: 'ios', color: 'orange', content: {kind: 'clip', src: 'assets/video/demo_ui.mp4', label: 'App'}}}},
  {id: 'x-clipgrid', type: 'GALLERY', narration: 'A grid of short clips reveals one after another with captions.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {headline: 'The [clips] grid', headlineColor: 'orange', gallery: {variant: 'clips', tiles: [{src: 'assets/video/demo_ui.mp4', label: 'Interface', color: 'orange', atWord: 1}, {src: 'assets/video/demo_flow.mp4', label: 'Dataflow', color: 'blue', atWord: 2}, {src: 'assets/video/demo_grid.mp4', label: 'Layout', color: 'green', atWord: 3}]}}},
  {id: 'x-screenshotcascade', type: 'SCREENSHOT_CASCADE', narration: 'Screenshots cascade with depth and a highlight marks the key part.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {screenshotCascade: {headline: 'The [screenshots], stacked', color: 'blue', shots: [{src: 'assets/video/demo_ui.mp4', label: 'app.tsx', color: 'blue', atWord: 1}, {src: 'assets/video/demo_grid.mp4', label: 'grid.tsx', color: 'orange', highlight: {x: 0.3, y: 0.3, w: 0.4, h: 0.2}, atWord: 2}, {src: 'assets/video/demo_flow.mp4', label: 'flow.tsx', color: 'green', atWord: 3}]}}},
  {id: 'x-floatingquote', type: 'FLOATING_QUOTE_PILL', narration: 'A glass pill floats a key question over the footage.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {floatingQuote: {src: 'assets/video/demo_flow.mp4', quote: 'What if the whole pipeline could run in a single pass?', attribution: '— the core question', color: 'orange', atWord: 1}}},
  {id: 'x-splitdefs', type: 'OVERLAY_SPLIT_DEFINITIONS', narration: 'Two boxless definitions flank the speaker on either side.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {splitDefs: {src: 'assets/video/demo_ui.mp4', color: 'orange', left: {header: 'Precision', body: 'the fraction of retrieved items that are relevant', color: 'blue', atWord: 1}, right: {header: 'Recall', body: 'the fraction of relevant items that were retrieved', color: 'green', atWord: 3}}}, pip: {src: 'assets/video/demo_webcam.mp4', position: 'br', size: 'sm', label: 'HOST', atWord: 1, color: 'orange'}},
  {id: 'x-cycleloop', type: 'CYCLE_LOOP', narration: 'Four stages form a loop joined by dashed arrows over a blurred clip.', durationFrames: 220, timingSource: 'estimated', background: 'zoneB', data: {cycleLoop: {headline: 'The [feedback] loop', src: 'assets/video/demo_flow.mp4', color: 'orange', nodes: [{label: 'Collect', sub: 'data in', color: 'blue', atWord: 1}, {label: 'Train', sub: 'the model', color: 'purple', atWord: 2}, {label: 'Deploy', sub: 'to prod', color: 'green', atWord: 3}, {label: 'Measure', sub: 'and repeat', color: 'orange', atWord: 4}]}}},
  {id: 'x-stepstack', type: 'STEP_STACK_OVERLAY', narration: 'Numbered steps stack on one side while the speaker stays clear.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {stepStack: {src: 'assets/video/demo_grid.mp4', headline: 'Three [steps]', chip: 'filled', dock: 'left', color: 'orange', steps: [{label: 'Tokenize the input', sub: 'split text', color: 'blue', atWord: 1}, {label: 'Embed each token', sub: 'to vectors', color: 'purple', atWord: 2}, {label: 'Predict the next', sub: 'sample', color: 'green', atWord: 3}]}}},
  {id: 'x-titlebanner', type: 'TITLE_BANNER_FOCUS', narration: 'A glass title banner lands over a blurred clip for the big moment.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {titleBanner: {src: 'assets/video/demo_ui.mp4', kicker: 'CHAPTER ONE', title: 'How it [all] works', subtitle: 'the title moment, over blurred footage', color: 'orange', atWord: 1}}, pip: {src: 'assets/video/demo_webcam.mp4', position: 'br', size: 'sm', label: 'HOST', atWord: 1, color: 'orange'}},
  {id: 'x-subchip', type: 'CHANNEL_CARD', narration: 'A subscribe chip slides in over the footage with avatar and button.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {subChip: {src: 'assets/video/demo_flow.mp4', name: 'Tech Explained', handle: '@techexplained', avatar: 'lucide:cpu', color: 'orange', atWord: 1}}},
  {id: 'x-talkingpoints', type: 'TALKING_POINTS', narration: 'A framed clip sits beside the key talking points on the theme.', durationFrames: 210, timingSource: 'estimated', background: 'zoneC', data: {talkingPoints: {src: 'assets/video/demo_ui.mp4', media: 'left', headline: 'Why it [matters]', lead: 'three reasons this changes everything', color: 'orange', points: [{text: 'It runs in a single pass', color: 'blue', atWord: 2}, {text: 'It is fully deterministic', color: 'green', atWord: 4}, {text: 'It scales to billions', color: 'purple', atWord: 6}]}}},
  {id: 'x-slidebullets', type: 'SLIDE_BULLETS_PIP', narration: 'A slide reveals nested bullets word by word beside a corner webcam.', durationFrames: 220, timingSource: 'estimated', background: 'zoneA', data: {slideBullets: {heading: 'The [key] points', color: 'orange', bullets: [{text: 'First the top-level idea lands', color: 'blue', atWord: 1}, {text: 'a supporting detail underneath', level: 1, color: 'blue', atWord: 3}, {text: 'Then the second big idea', color: 'green', atWord: 5}, {text: 'with its own nested note', level: 1, color: 'green', atWord: 7}]}}, pip: {src: 'assets/video/demo_webcam.mp4', position: 'br', size: 'sm', label: 'HOST', atWord: 1, color: 'orange'}},
  {id: 'x-captionkinetic', type: 'CAPTION_KINETIC_OVERLAY', narration: 'A big caption lands word by word over the footage.', durationFrames: 200, timingSource: 'estimated', background: 'zoneB', data: {captionKinetic: {src: 'assets/video/demo_flow.mp4', caption: 'This changes [everything] you know', color: 'orange', position: 'bottom', atWord: 1}}},
  {id: 'x-phototimeline', type: 'PHOTO_TIMELINE', narration: 'Photos reveal along a timeline rail one date at a time.', durationFrames: 220, timingSource: 'estimated', background: 'zoneC', data: {photoTimeline: {headline: 'The [history]', color: 'orange', entries: [{src: 'assets/network.jpg', kind: 'image', label: 'The network', date: '2010', color: 'blue', atWord: 1}, {src: 'assets/datacenter.jpg', kind: 'image', label: 'The data center', date: '2015', color: 'orange', atWord: 3}, {src: 'assets/server-racks.jpg', kind: 'image', label: 'The racks', date: '2020', color: 'green', atWord: 5}]}}},
  {id: 'x-agentmesh', type: 'DIAGRAM', narration: 'An agent mesh: an orchestrator delegates to worker agents.', durationFrames: 210, timingSource: 'estimated', background: 'zoneA', data: {headline: 'An [agent] mesh', headlineColor: 'purple', diagram: {layout: 'hub', variant: 'agentMesh', nodes: [{id: 'orch', label: 'Orchestrator', role: 'planner', color: 'purple', atWord: 1}, {id: 'a1', label: 'Researcher', role: 'worker', color: 'blue', atWord: 2}, {id: 'a2', label: 'Coder', role: 'worker', color: 'green', atWord: 3}, {id: 'a3', label: 'Critic', role: 'reviewer', color: 'orange', atWord: 4}], edges: [{from: 'orch', to: 'a1', atWord: 2}, {from: 'orch', to: 'a2', atWord: 3}, {from: 'orch', to: 'a3', atWord: 4}]}}},
  {id: 'x-forecast', type: 'LINE_CHART', narration: 'A forecast shows history solid and the future as a dashed band.', durationFrames: 210, timingSource: 'estimated', background: 'zoneB', data: {lineChart: {atWord: 1, forecastFrom: 4, bandPct: 0.22, nowLabel: 'now', xAxis: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'], series: [{label: 'users', color: 'blue', values: [20, 28, 34, 45, 58, 72, 88]}]}}},
  {id: 'x-authflow', type: 'DIAGRAM', narration: 'In an OAuth flow a signed token rides back to the app.', durationFrames: 220, timingSource: 'estimated', background: 'zoneC', data: {headline: 'The [OAuth] flow', headlineColor: 'green', diagram: {layout: 'sequence', variant: 'auth', authToken: 'JWT', nodes: [{id: 'user', label: 'User', atWord: 1}, {id: 'app', label: 'App', atWord: 1}, {id: 'authsrv', label: 'Auth Server', atWord: 1}], edges: [{from: 'user', to: 'app', label: '1. login', atWord: 2}, {from: 'app', to: 'authsrv', label: '2. authorize', atWord: 3}, {from: 'authsrv', to: 'app', label: '3. token', atWord: 4}]}}},
  {id: 'x-reveal', type: 'REVEAL', narration: 'And then the whole point is revealed.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {headline: 'The [big idea].', reveal: {kicker: 'REVEAL', sub: 'a cinematic statement', color: 'blue', atWord: 1}}},
  {id: 'x-list', type: 'LIST_BUILD', narration: 'A list builds up one item at a time on screen.', durationFrames: 220, timingSource: 'estimated', background: 'zoneB', data: {heading: 'Three ideas', items: [{icon: 'lucide:scissors', text: 'Tokenize', detail: 'split the text', atWord: 1}, {icon: 'lucide:brain-circuit', text: 'Embed', detail: 'into vectors', atWord: 4}, {icon: 'lucide:sparkles', text: 'Predict', detail: 'the next token', atWord: 7}]}},
  {id: 'x-stat', type: 'STAT_CALLOUT', narration: 'A single hero number lands hard and clear.', durationFrames: 150, timingSource: 'estimated', background: 'zoneC', data: {value: 1500000000, label: 'parameters, and counting', atWord: 1, anim: 'pop'}},
  {id: 'x-carousel', type: 'CAROUSEL', narration: 'A carousel spins a ring of options past the viewer.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {carousel: {items: [{label: 'One', sub: 'first', asset: 'lucide:box', color: 'blue'}, {label: 'Two', sub: 'second', asset: 'lucide:layers', color: 'purple'}, {label: 'Three', sub: 'third', asset: 'lucide:star', color: 'green'}, {label: 'Four', sub: 'fourth', asset: 'lucide:zap', color: 'orange'}], atWord: 1}}},
  {id: 'x-activity', type: 'ACTIVITY_CARD', narration: 'A KPI card shows a value, a trend and a mini chart.', durationFrames: 180, timingSource: 'estimated', background: 'zoneB', data: {activity: {title: 'Activity', value: '21h', trend: '+12% this week', range: 'Weekly', color: 'blue', trendColor: 'green', atWord: 1, data: [{day: 'M', value: 8}, {day: 'T', value: 12}, {day: 'W', value: 9}, {day: 'T', value: 4}, {day: 'F', value: 14}, {day: 'S', value: 6}, {day: 'S', value: 3}]}}},
  {id: 'x-map', type: 'LOCATION_MAP', narration: 'A map card expands and drops a pin on a place.', durationFrames: 220, timingSource: 'estimated', background: 'zoneC', data: {locationMap: {location: 'San Francisco, CA', coordinates: '37.77 N, 122.41 W', status: 'Live', color: 'green', atWord: 1}}},
  {id: 'x-wave', type: 'SOUND_WAVE', narration: 'A sound wave pulses for audio and podcast moments.', durationFrames: 150, timingSource: 'estimated', background: 'zoneA', data: {headline: 'Now [listen].', wave: {label: 'episode 12', color: 'purple', bars: 40, atWord: 1}}},
  {id: 'x-logo', type: 'LOGO_REVEAL', narration: 'A logo draws itself in for the brand sting.', durationFrames: 170, timingSource: 'estimated', background: 'zoneB', data: {logo: {name: 'ACME AI', tagline: 'ship intelligence', asset: 'lucide:hexagon', color: 'blue', atWord: 1}}},
  {id: 'x-photo', type: 'PHOTO', narration: 'A full-bleed photo sets a real-world scene.', durationFrames: 180, timingSource: 'estimated', background: 'zoneA', data: {photo: {asset: 'img:server-racks.jpg', caption: 'inside a data center', kicker: 'THE MACHINE', color: 'blue', pan: 'in', atWord: 1}}},
  {id: 'x-sub', type: 'SUBSCRIBE_REMINDER', narration: 'A mid-roll nudge to subscribe.', durationFrames: 150, timingSource: 'estimated', background: 'zoneC', data: {subscribe: {text: 'Subscribe for more', sub: 'new videos weekly', handle: '@yourchannel', color: 'red', atWord: 1}}},
  {id: 'x-credits', type: 'CREDITS_ROLL', narration: 'And the credits roll at the very end.', durationFrames: 200, timingSource: 'estimated', background: 'zoneA', data: {credits: {title: 'Credits', rows: [{role: 'Director', name: 'Your Studio'}, {role: 'Music', name: 'Public Domain'}, {role: 'Built with', name: 'Remotion'}], color: 'blue'}}},
] as unknown as Scene[];

const BG = ['zoneA', 'zoneB', 'zoneC'] as const;
// gallery (opens with HOOK) + the extra dynamic types + widgets (drop its HOOK).
const raw = [...gallery.scenes, ...extra, ...widgets.scenes.slice(1)];
const scenes: Scene[] = raw.map((s, i) => ({
  ...s,
  id: `sc${String(i + 1).padStart(2, '0')}`,
  transition: TRANSITIONS[i % TRANSITIONS.length],
  background: s.background ?? BG[i % 3],
}));

export const showcaseSpec: VideoSpec = {
  meta: {topic: 'Component showcase — every scene type in this design', format: 'long', fps: 30, onePayoff: 'x', topicAxes: ['a', 'b']},
  brand: {theme: 'studio'},
  scenes,
};

// AUTHORITATIVE showcase scene index — the SINGLE SOURCE OF TRUTH for the matrix
// tooling (scripts/dump-showcase.mjs emits it to audit/showcase-scenes.json, which
// scripts/matrix-shots.mjs consumes). Derived from the SAME `scenes` array the
// composition renders, so still labels and frame offsets can NEVER drift. coverFrames
// is 0 for the showcase (no `cover`), so startFrame == the real composition frame.
// NEVER regex-parse this file's text to rebuild this — import this export.
const variantOf = (s: Scene): string | undefined => {
  const d = s.data as Record<string, unknown> | undefined;
  if (!d) return undefined;
  const g = (k: string, f: string): string | undefined => {
    const o = d[k] as Record<string, unknown> | undefined;
    return o && typeof o[f] === 'string' ? (o[f] as string) : undefined;
  };
  switch (s.type) {
    case 'PIPELINE': return g('pipeline', 'variant');
    case 'CODE_EDITOR': return g('editor', 'variant');
    case 'WINDOW_FRAME': return g('window', 'variant');
    case 'DIAGRAM': return g('diagram', 'variant');
    case 'LAYERED_STACK': return g('stack', 'variant');
    case 'PACKET': return g('packet', 'variant');
    case 'K8S_CLUSTER': return g('k8s', 'mode');
    case 'BITS': return g('bits', 'variant');
    case 'CACHE_PYRAMID': return g('pyramid', 'variant');
    case 'STATE_MACHINE': return g('stateMachine', 'variant');
    case 'ENCRYPTION': return g('encryption', 'mode');
    case 'CONFIDENCE_GATE': return g('confidence', 'mode');
    case 'CALL_STACK': return g('callStack', 'mode');
    default: return undefined;
  }
};

export interface ShowcaseSceneMeta {
  index: number;
  id: string;
  type: string;
  variant?: string;
  durationFrames: number;
  startFrame: number;
  midFrame: number;
}

export const showcaseScenes: ShowcaseSceneMeta[] = (() => {
  let off = 0;
  return scenes.map((s, i) => {
    const startFrame = off;
    off += s.durationFrames;
    return {
      index: i,
      id: s.id,
      type: s.type,
      variant: variantOf(s),
      durationFrames: s.durationFrames,
      startFrame,
      midFrame: startFrame + Math.floor(s.durationFrames * 0.55),
    };
  });
})();

// NEW-COMPONENTS SHOWCASE — a focused reel of just the recent-program components
// (Batches 1–7: IDE grammar → browser/automation → cloud/containers → OS →
// testing → AI systems), grouped by domain. Registered as <design>-new-wide /
// <design>-new-short so a reviewer can scrub the new work per design without the
// full ~70-scene kitchen sink. Add a new component's showcase id here when it ships.
const NEW_IDS = new Set([
  // Batch 1 — PIPELINE variants
  'x-pipeline-ci', 'x-pipeline-boot', 'x-pipeline-serverless', 'x-pipeline-journey',
  // Batch 2 — IDE grammar
  'x-editor', 'x-editor-split', 'x-terminal', 'x-logs', 'x-diff', 'x-errortrace',
  // Batch 3 — browser / automation
  'x-window', 'x-window-mac', 'x-automation', 'x-dominspect', 'x-waterfall', 'x-device',
  // Batch 4 — cloud & containers
  'x-cloud', 'x-k8s', 'x-cost', 'x-slo', 'x-iac', 'x-erd', 'x-imagelayers', 'x-container', 'x-servicemesh',
  // Batch 5 — operating systems
  'x-proctable', 'x-kernel', 'x-permbits',
  // Batch 6 — testing & quality
  'x-testrunner', 'x-testmatrix', 'x-testpyramid', 'x-buglife',
  // Batch 7 — AI systems + depth devices
  'x-context', 'x-harness', 'x-kg', 'x-retrieval', 'x-modelstages', 'x-confidence', 'x-sandbox', 'x-drillin', 'x-eval', 'x-agentmesh', 'x-forecast', 'x-authflow',
  // Program 3 · media family (Phase B1)
  'x-videohero', 'x-videospotlight', 'x-mediacallout', 'x-mediacompare', 'x-mediastat', 'x-videodevice', 'x-clipgrid', 'x-screenshotcascade', 'x-floatingquote', 'x-splitdefs', 'x-cycleloop', 'x-stepstack', 'x-titlebanner', 'x-subchip', 'x-talkingpoints', 'x-slidebullets', 'x-captionkinetic', 'x-phototimeline',
]);
const newOpener = {id: 'new-title', type: 'TITLE_CARD', narration: 'The new components, in this design.', durationFrames: 140, timingSource: 'estimated', background: 'zoneA', data: {title: 'New Components', subtitle: 'IDE · browser · cloud · OS · testing · AI · charts · icons · science'}} as unknown as Scene;
// Phase B2/B3/B4 components live as gallery demos (s6e2–s6e23), not in `extra`,
// so the new reel pulls them straight from the gallery scenes too.
const NEW_GALLERY_IDS = new Set([
  's6e2', 's6e3', 's6e4', 's6e5', 's6e6', 's6e7', 's6e8', 's6e9', // B2 charts: FUNNEL/WATERFALL/PICTOGRAM/RADAR/CANDLESTICK/BOX_PLOT/TREEMAP/SANKEY
  's6e10', 's6e11', 's6e12', 's6e13', 's6e14', 's6e15',          // B3 icons/logos
  's6e16', 's6e17', 's6e18', 's6e19', 's6e20', 's6e21', 's6e22', 's6e23', // B4 topic-general
]);
const newGallery = gallery.scenes.filter((s) => NEW_GALLERY_IDS.has((s as {id: string}).id));
const newRaw = [newOpener, ...extra.filter((s) => NEW_IDS.has((s as {id: string}).id)), ...newGallery];
const newScenes: Scene[] = newRaw.map((s, i) => ({
  ...s,
  id: `nc${String(i + 1).padStart(2, '0')}`,
  transition: TRANSITIONS[i % TRANSITIONS.length],
  background: s.background ?? BG[i % 3],
}));

export const newShowcaseSpec: VideoSpec = {
  meta: {topic: 'New components — the recent-program reel, in this design', format: 'long', fps: 30, onePayoff: 'x', topicAxes: ['a', 'b']},
  brand: {theme: 'studio'},
  scenes: newScenes,
};
