// AUTO-GENERATED by scripts/gen-index.mjs — do not edit by hand.
import {VideoSpec} from './types';
import long0 from '../topics/ai-search-trends-2026/long.json';
import shorts0 from '../topics/ai-search-trends-2026/shorts.json';
import long1 from '../topics/bonsai-27b-the-ai-model-that-runs-on-your-phone/long.json';
import shorts1 from '../topics/bonsai-27b-the-ai-model-that-runs-on-your-phone/shorts.json';
import long2 from '../topics/fluence-energy/long.json';
import shorts2 from '../topics/fluence-energy/shorts.json';
import long3 from '../topics/how-gps-knows-where-you-are/long.json';
import shorts3 from '../topics/how-gps-knows-where-you-are/shorts.json';
import long4 from '../topics/how-llms-work/long.json';
import shorts4 from '../topics/how-llms-work/shorts.json';
import long5 from '../topics/how-password-managers-actually-keep-your-secrets-safe/long.json';
import shorts5 from '../topics/how-password-managers-actually-keep-your-secrets-safe/shorts.json';
import long6 from '../topics/how-the-internet-works/long.json';
import shorts6 from '../topics/how-the-internet-works/shorts.json';
import long7 from '../topics/instagram-s-newest-ai-tool-didn-t-survive-the-week/long.json';
import shorts7 from '../topics/instagram-s-newest-ai-tool-didn-t-survive-the-week/shorts.json';
import long8 from '../topics/palette-136-tour/long.json';
import shorts8 from '../topics/palette-136-tour/shorts.json';
import long9 from '../topics/react-basics/long.json';
import shorts9 from '../topics/react-basics/shorts.json';
import long10 from '../topics/terawulf-anthropic-lease/long.json';
import shorts10 from '../topics/terawulf-anthropic-lease/shorts.json';
import long11 from '../topics/the-biggest-ai-stories-of-july-2026/long.json';
import shorts11 from '../topics/the-biggest-ai-stories-of-july-2026/shorts.json';
import long12 from '../topics/why-computers-get-0-1-plus-0-2-wrong/long.json';
import shorts12 from '../topics/why-computers-get-0-1-plus-0-2-wrong/shorts.json';
import long13 from '../topics/xrp-prediction/long.json';
import shorts13 from '../topics/xrp-prediction/shorts.json';

export interface TopicEntry {slug: string; long: VideoSpec; shorts: VideoSpec | null;}

export const topics: TopicEntry[] = [
  {slug: 'ai-search-trends-2026', long: long0 as unknown as VideoSpec, shorts: shorts0 as unknown as VideoSpec},
  {slug: 'bonsai-27b-the-ai-model-that-runs-on-your-phone', long: long1 as unknown as VideoSpec, shorts: shorts1 as unknown as VideoSpec},
  {slug: 'fluence-energy', long: long2 as unknown as VideoSpec, shorts: shorts2 as unknown as VideoSpec},
  {slug: 'how-gps-knows-where-you-are', long: long3 as unknown as VideoSpec, shorts: shorts3 as unknown as VideoSpec},
  {slug: 'how-llms-work', long: long4 as unknown as VideoSpec, shorts: shorts4 as unknown as VideoSpec},
  {slug: 'how-password-managers-actually-keep-your-secrets-safe', long: long5 as unknown as VideoSpec, shorts: shorts5 as unknown as VideoSpec},
  {slug: 'how-the-internet-works', long: long6 as unknown as VideoSpec, shorts: shorts6 as unknown as VideoSpec},
  {slug: 'instagram-s-newest-ai-tool-didn-t-survive-the-week', long: long7 as unknown as VideoSpec, shorts: shorts7 as unknown as VideoSpec},
  {slug: 'palette-136-tour', long: long8 as unknown as VideoSpec, shorts: shorts8 as unknown as VideoSpec},
  {slug: 'react-basics', long: long9 as unknown as VideoSpec, shorts: shorts9 as unknown as VideoSpec},
  {slug: 'terawulf-anthropic-lease', long: long10 as unknown as VideoSpec, shorts: shorts10 as unknown as VideoSpec},
  {slug: 'the-biggest-ai-stories-of-july-2026', long: long11 as unknown as VideoSpec, shorts: shorts11 as unknown as VideoSpec},
  {slug: 'why-computers-get-0-1-plus-0-2-wrong', long: long12 as unknown as VideoSpec, shorts: shorts12 as unknown as VideoSpec},
  {slug: 'xrp-prediction', long: long13 as unknown as VideoSpec, shorts: shorts13 as unknown as VideoSpec},
];
