// AUTO-GENERATED by scripts/gen-index.mjs — do not edit by hand.
import {VideoSpec} from './types';
import long0 from '../topics/ai-search-trends-2026/long.json';
import shorts0 from '../topics/ai-search-trends-2026/shorts.json';
import long1 from '../topics/how-llms-work/long.json';
import shorts1 from '../topics/how-llms-work/shorts.json';
import long2 from '../topics/how-the-internet-works/long.json';
import shorts2 from '../topics/how-the-internet-works/shorts.json';
import long3 from '../topics/react-basics/long.json';
import shorts3 from '../topics/react-basics/shorts.json';
import long4 from '../topics/terawulf-anthropic-lease/long.json';
import shorts4 from '../topics/terawulf-anthropic-lease/shorts.json';
import long5 from '../topics/xrp-prediction/long.json';
import shorts5 from '../topics/xrp-prediction/shorts.json';

export interface TopicEntry {slug: string; long: VideoSpec; shorts: VideoSpec | null;}

export const topics: TopicEntry[] = [
  {slug: 'ai-search-trends-2026', long: long0 as unknown as VideoSpec, shorts: shorts0 as unknown as VideoSpec},
  {slug: 'how-llms-work', long: long1 as unknown as VideoSpec, shorts: shorts1 as unknown as VideoSpec},
  {slug: 'how-the-internet-works', long: long2 as unknown as VideoSpec, shorts: shorts2 as unknown as VideoSpec},
  {slug: 'react-basics', long: long3 as unknown as VideoSpec, shorts: shorts3 as unknown as VideoSpec},
  {slug: 'terawulf-anthropic-lease', long: long4 as unknown as VideoSpec, shorts: shorts4 as unknown as VideoSpec},
  {slug: 'xrp-prediction', long: long5 as unknown as VideoSpec, shorts: shorts5 as unknown as VideoSpec},
];
